import type {
  AcsUniverseId,
  AcsVariableDefinition,
  UniverseDefinition,
  VariableCategory,
} from "./types";

export const ACS_UNIVERSE_DEFINITIONS: Record<
  AcsUniverseId,
  UniverseDefinition
> = {
  total_population: {
    id: "total_population",
    name: "Total Population",
    description: "All persons residing in the geographic entity.",
    parentUniverseId: null,
    baseTableId: "B01003",
    baseVariableId: "B01003_001",
  },
  population_18_and_over: {
    id: "population_18_and_over",
    name: "Population 18 Years and Over",
    description:
      "Voting-age population eligible by age for civic participation.",
    parentUniverseId: "total_population",
    baseTableId: "B09021",
    baseVariableId: "B09021_001",
  },
  citizen_population_18_and_over: {
    id: "citizen_population_18_and_over",
    name: "Citizen Voting-Age Population (CVAP)",
    description:
      "U.S. citizens aged 18 and over, the standard denominator for electoral representation and Voting Rights Act analysis.",
    parentUniverseId: "population_18_and_over",
    baseTableId: "B29001",
    baseVariableId: "B29001_001",
  },
  population_25_and_over: {
    id: "population_25_and_over",
    name: "Population 25 Years and Over",
    description:
      "Standard demographic universe for completed educational attainment measures.",
    parentUniverseId: "population_18_and_over",
    baseTableId: "B15003",
    baseVariableId: "B15003_001",
  },
  population_16_and_over: {
    id: "population_16_and_over",
    name: "Population 16 Years and Over",
    description:
      "Working-age population universe for labor force and employment status.",
    parentUniverseId: "total_population",
    baseTableId: "B23025",
    baseVariableId: "B23025_001",
  },
  civilian_labor_force_16_and_over: {
    id: "civilian_labor_force_16_and_over",
    name: "Civilian Labor Force",
    description:
      "Civilian noninstitutionalized persons aged 16 and over who are employed or actively seeking work.",
    parentUniverseId: "population_16_and_over",
    baseTableId: "B23025",
    baseVariableId: "B23025_003",
  },
  civilian_employed_16_and_over: {
    id: "civilian_employed_16_and_over",
    name: "Civilian Employed Population 16 Years and Over",
    description:
      "Civilians 16+ with active employment, universe for occupation and industry distributions.",
    parentUniverseId: "civilian_labor_force_16_and_over",
    baseTableId: "C24010",
    baseVariableId: "C24010_001",
  },
  civilian_noninstitutionalized_population: {
    id: "civilian_noninstitutionalized_population",
    name: "Civilian Noninstitutionalized Population",
    description:
      "Universe for health insurance and disability status measures.",
    parentUniverseId: "total_population",
    baseTableId: "B18101",
    baseVariableId: "B18101_001",
  },
  households: {
    id: "households",
    name: "Total Households",
    description: "All occupied housing units housing one or more individuals.",
    parentUniverseId: null,
    baseTableId: "B11001",
    baseVariableId: "B11001_001",
  },
  family_households: {
    id: "family_households",
    name: "Family Households",
    description: "Households consisting of two or more related individuals.",
    parentUniverseId: "households",
    baseTableId: "B11001",
    baseVariableId: "B11001_002",
  },
  occupied_housing_units: {
    id: "occupied_housing_units",
    name: "Occupied Housing Units",
    description: "Universe for housing tenure (owner vs. renter occupied).",
    parentUniverseId: null,
    baseTableId: "B25003",
    baseVariableId: "B25003_001",
  },
  renter_occupied_cash_rent: {
    id: "renter_occupied_cash_rent",
    name: "Renter-Occupied Housing Units Paying Cash Rent",
    description: "Universe for gross rent distributions and median gross rent.",
    parentUniverseId: "occupied_housing_units",
    baseTableId: "B25064",
    baseVariableId: "B25064_001",
  },
  owner_occupied_housing_units: {
    id: "owner_occupied_housing_units",
    name: "Owner-Occupied Housing Units",
    description:
      "Universe for owner home value distributions and median home value.",
    parentUniverseId: "occupied_housing_units",
    baseTableId: "B25077",
    baseVariableId: "B25077_001",
  },
  workers_16_and_over: {
    id: "workers_16_and_over",
    name: "Workers 16 Years and Over",
    description:
      "Universe for commuting mode, travel time to work, and vehicle availability.",
    parentUniverseId: "civilian_employed_16_and_over",
    baseTableId: "B08301",
    baseVariableId: "B08301_001",
  },
  poverty_universe: {
    id: "poverty_universe",
    name: "Population for Whom Poverty Status is Determined",
    description:
      "Universe for official poverty rate determinations (excludes institutionalized individuals, military group quarters, college dorms, and unrelated individuals under age 15).",
    parentUniverseId: "total_population",
    baseTableId: "B17001",
    baseVariableId: "B17001_001",
  },
};

export const ACS_VARIABLE_REGISTRY: AcsVariableDefinition[] = [
  // 1. Total Population
  {
    id: "B01003_001",
    estimateVariableId: "B01003_001E",
    moeVariableId: "B01003_001M",
    tableId: "B01003",
    label: "Total Population",
    category: "population",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    description: "Total resident population in the geography.",
  },

  // 2. Voting-Age & CVAP
  {
    id: "B09021_001",
    estimateVariableId: "B09021_001E",
    moeVariableId: "B09021_001M",
    tableId: "B09021",
    label: "Voting-Age Population (18+)",
    category: "voting_age_and_citizenship",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Population aged 18 years and over.",
  },
  {
    id: "B29001_001",
    estimateVariableId: "B29001_001E",
    moeVariableId: "B29001_001M",
    tableId: "B29001",
    label: "Citizen Voting-Age Population (CVAP)",
    category: "voting_age_and_citizenship",
    universeId: "citizen_population_18_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B09021_001",
    description:
      "Citizen population aged 18 years and over (electoral baseline).",
  },

  // 3. Age Structure
  {
    id: "B01002_001",
    estimateVariableId: "B01002_001E",
    moeVariableId: "B01002_001M",
    tableId: "B01002",
    label: "Median Age",
    category: "age_structure",
    universeId: "total_population",
    unit: "years",
    aggregationMethod: "median",
    description: "Median age of total resident population.",
  },
  {
    id: "AGE_UNDER_5",
    estimateVariableId: "AGE_UNDER_5_E",
    moeVariableId: "AGE_UNDER_5_M",
    tableId: "B01001",
    label: "Population Under 5 Years",
    category: "age_structure",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Resident population under 5 years of age.",
  },
  {
    id: "AGE_5_TO_17",
    estimateVariableId: "AGE_5_TO_17_E",
    moeVariableId: "AGE_5_TO_17_M",
    tableId: "B01001",
    label: "Population 5 to 17 Years (School Age)",
    category: "age_structure",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Resident school-age population 5 to 17 years.",
  },
  {
    id: "AGE_18_TO_24",
    estimateVariableId: "AGE_18_TO_24_E",
    moeVariableId: "AGE_18_TO_24_M",
    tableId: "B01001",
    label: "Population 18 to 24 Years",
    category: "age_structure",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Young adult population 18 to 24 years.",
  },
  {
    id: "AGE_25_TO_44",
    estimateVariableId: "AGE_25_TO_44_E",
    moeVariableId: "AGE_25_TO_44_M",
    tableId: "B01001",
    label: "Population 25 to 44 Years",
    category: "age_structure",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Early-to-mid career adult population 25 to 44 years.",
  },
  {
    id: "AGE_45_TO_64",
    estimateVariableId: "AGE_45_TO_64_E",
    moeVariableId: "AGE_45_TO_64_M",
    tableId: "B01001",
    label: "Population 45 to 64 Years",
    category: "age_structure",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Mature adult population 45 to 64 years.",
  },
  {
    id: "AGE_65_AND_OVER",
    estimateVariableId: "AGE_65_AND_OVER_E",
    moeVariableId: "AGE_65_AND_OVER_M",
    tableId: "B01001",
    label: "Population 65 Years and Over (Seniors)",
    category: "age_structure",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Senior resident population 65 years and over.",
  },

  // 4. Sex
  {
    id: "B01001_002",
    estimateVariableId: "B01001_002E",
    moeVariableId: "B01001_002M",
    tableId: "B01001",
    label: "Male Population",
    category: "sex",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Male resident population.",
  },
  {
    id: "B01001_026",
    estimateVariableId: "B01001_026E",
    moeVariableId: "B01001_026M",
    tableId: "B01001",
    label: "Female Population",
    category: "sex",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B01003_001",
    description: "Female resident population.",
  },

  // 5. Educational Attainment (Universe: Population 25+)
  {
    id: "B15003_001",
    estimateVariableId: "B15003_001E",
    moeVariableId: "B15003_001M",
    tableId: "B15003",
    label: "Population 25 Years and Over",
    category: "educational_attainment",
    universeId: "population_25_and_over",
    unit: "count",
    aggregationMethod: "sum",
    description:
      "Total population 25 years and over (educational attainment universe).",
  },
  {
    id: "EDU_LESS_THAN_HS",
    estimateVariableId: "EDU_LESS_THAN_HS_E",
    moeVariableId: "EDU_LESS_THAN_HS_M",
    tableId: "B15003",
    label: "Less than High School Diploma",
    category: "educational_attainment",
    universeId: "population_25_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B15003_001",
    description: "Persons 25+ without a high school diploma or equivalent.",
  },
  {
    id: "EDU_HS_GRAD",
    estimateVariableId: "EDU_HS_GRAD_E",
    moeVariableId: "EDU_HS_GRAD_M",
    tableId: "B15003",
    label: "High School Graduate (includes equivalency)",
    category: "educational_attainment",
    universeId: "population_25_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B15003_001",
    description:
      "Persons 25+ whose highest education is regular high school diploma or GED.",
  },
  {
    id: "EDU_SOME_COLLEGE_OR_ASSOC",
    estimateVariableId: "EDU_SOME_COLLEGE_OR_ASSOC_E",
    moeVariableId: "EDU_SOME_COLLEGE_OR_ASSOC_M",
    tableId: "B15003",
    label: "Some College or Associate Degree",
    category: "educational_attainment",
    universeId: "population_25_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B15003_001",
    description:
      "Persons 25+ with some college credit (no degree) or an Associate degree.",
  },
  {
    id: "B15003_022",
    estimateVariableId: "B15003_022E",
    moeVariableId: "B15003_022M",
    tableId: "B15003",
    label: "Bachelor Degree",
    category: "educational_attainment",
    universeId: "population_25_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B15003_001",
    description:
      "Persons 25+ whose highest educational attainment is a Bachelor degree.",
  },
  {
    id: "EDU_GRAD_OR_PROF",
    estimateVariableId: "EDU_GRAD_OR_PROF_E",
    moeVariableId: "EDU_GRAD_OR_PROF_M",
    tableId: "B15003",
    label: "Graduate or Professional Degree",
    category: "educational_attainment",
    universeId: "population_25_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B15003_001",
    description:
      "Persons 25+ with Masters, Professional (JD/MD), or Doctoral degree.",
  },

  // 6. Household Income (Universe: Households)
  {
    id: "B19013_001",
    estimateVariableId: "B19013_001E",
    moeVariableId: "B19013_001M",
    tableId: "B19013",
    label: "Median Household Income (Dollars)",
    category: "household_income",
    universeId: "households",
    unit: "dollars",
    aggregationMethod: "median",
    description:
      "Median household income in the past 12 months (inflation-adjusted dollars).",
  },
  {
    id: "B19025_001",
    estimateVariableId: "B19025_001E",
    moeVariableId: "B19025_001M",
    tableId: "B19025",
    label: "Aggregate Household Income (Dollars)",
    category: "household_income",
    universeId: "households",
    unit: "dollars",
    aggregationMethod: "sum",
    description:
      "Aggregate household income in the past 12 months across all households.",
  },
  {
    id: "B19001_001",
    estimateVariableId: "B19001_001E",
    moeVariableId: "B19001_001M",
    tableId: "B19001",
    label: "Total Households for Income Distribution",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    description: "Total households in income distribution universe.",
  },
  {
    id: "INC_UNDER_25K",
    estimateVariableId: "INC_UNDER_25K_E",
    moeVariableId: "INC_UNDER_25K_M",
    tableId: "B19001",
    label: "Household Income Under $25,000",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B19001_001",
    description: "Households with annual income under $25,000.",
  },
  {
    id: "INC_25K_TO_49K",
    estimateVariableId: "INC_25K_TO_49K_E",
    moeVariableId: "INC_25K_TO_49K_M",
    tableId: "B19001",
    label: "Household Income $25,000 to $49,999",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B19001_001",
    description: "Households with annual income between $25,000 and $49,999.",
  },
  {
    id: "INC_50K_TO_74K",
    estimateVariableId: "INC_50K_TO_74K_E",
    moeVariableId: "INC_50K_TO_74K_M",
    tableId: "B19001",
    label: "Household Income $50,000 to $74,999",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B19001_001",
    description: "Households with annual income between $50,000 and $74,999.",
  },
  {
    id: "INC_75K_TO_99K",
    estimateVariableId: "INC_75K_TO_99K_E",
    moeVariableId: "INC_75K_TO_99K_M",
    tableId: "B19001",
    label: "Household Income $75,000 to $99,999",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B19001_001",
    description: "Households with annual income between $75,000 and $99,999.",
  },
  {
    id: "INC_100K_TO_149K",
    estimateVariableId: "INC_100K_TO_149K_E",
    moeVariableId: "INC_100K_TO_149K_M",
    tableId: "B19001",
    label: "Household Income $100,000 to $149,999",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B19001_001",
    description: "Households with annual income between $100,000 and $149,999.",
  },
  {
    id: "INC_150K_TO_199K",
    estimateVariableId: "INC_150K_TO_199K_E",
    moeVariableId: "INC_150K_TO_199K_M",
    tableId: "B19001",
    label: "Household Income $150,000 to $199,999",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B19001_001",
    description: "Households with annual income between $150,000 and $199,999.",
  },
  {
    id: "INC_200K_PLUS",
    estimateVariableId: "INC_200K_PLUS_E",
    moeVariableId: "INC_200K_PLUS_M",
    tableId: "B19001",
    label: "Household Income $200,000 and Above",
    category: "household_income",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B19001_001",
    description: "Households with annual income $200,000 or more.",
  },

  // 7. Poverty (Universe: Poverty Universe)
  {
    id: "B17001_001",
    estimateVariableId: "B17001_001E",
    moeVariableId: "B17001_001M",
    tableId: "B17001",
    label: "Population for Whom Poverty Status is Determined",
    category: "poverty",
    universeId: "poverty_universe",
    unit: "count",
    aggregationMethod: "sum",
    description:
      "Total population for whom official poverty status is determined.",
  },
  {
    id: "B17001_002",
    estimateVariableId: "B17001_002E",
    moeVariableId: "B17001_002M",
    tableId: "B17001",
    label: "Income in Past 12 Months Below Poverty Level",
    category: "poverty",
    universeId: "poverty_universe",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B17001_001",
    description:
      "Persons with family income below the federal poverty threshold.",
  },
  {
    id: "B17001_031",
    estimateVariableId: "B17001_031E",
    moeVariableId: "B17001_031M",
    tableId: "B17001",
    label: "Income in Past 12 Months At or Above Poverty Level",
    category: "poverty",
    universeId: "poverty_universe",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B17001_001",
    description:
      "Persons with family income at or above federal poverty threshold.",
  },

  // 8. Employment Status (Universe: Population 16+)
  {
    id: "B23025_001",
    estimateVariableId: "B23025_001E",
    moeVariableId: "B23025_001M",
    tableId: "B23025",
    label: "Population 16 Years and Over",
    category: "employment_status",
    universeId: "population_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    description: "Total working-age population 16 years and over.",
  },
  {
    id: "B23025_002",
    estimateVariableId: "B23025_002E",
    moeVariableId: "B23025_002M",
    tableId: "B23025",
    label: "In Labor Force",
    category: "employment_status",
    universeId: "population_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B23025_001",
    description: "Persons 16+ in the labor force (civilian or armed forces).",
  },
  {
    id: "B23025_003",
    estimateVariableId: "B23025_003E",
    moeVariableId: "B23025_003M",
    tableId: "B23025",
    label: "Civilian Labor Force",
    category: "employment_status",
    universeId: "civilian_labor_force_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B23025_001",
    description: "Civilian population 16+ in the labor force.",
  },
  {
    id: "B23025_004",
    estimateVariableId: "B23025_004E",
    moeVariableId: "B23025_004M",
    tableId: "B23025",
    label: "Civilian Employed",
    category: "employment_status",
    universeId: "civilian_labor_force_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B23025_003",
    description: "Civilian employed workers aged 16 and over.",
  },
  {
    id: "B23025_005",
    estimateVariableId: "B23025_005E",
    moeVariableId: "B23025_005M",
    tableId: "B23025",
    label: "Civilian Unemployed",
    category: "employment_status",
    universeId: "civilian_labor_force_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B23025_003",
    description: "Civilian unemployed persons actively seeking employment.",
  },
  {
    id: "B23025_006",
    estimateVariableId: "B23025_006E",
    moeVariableId: "B23025_006M",
    tableId: "B23025",
    label: "Armed Forces",
    category: "employment_status",
    universeId: "population_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B23025_001",
    description: "Persons 16+ on active duty in the Armed Forces.",
  },
  {
    id: "B23025_007",
    estimateVariableId: "B23025_007E",
    moeVariableId: "B23025_007M",
    tableId: "B23025",
    label: "Not in Labor Force",
    category: "employment_status",
    universeId: "population_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B23025_001",
    description:
      "Persons 16+ not in the labor force (students, retirees, homemakers, etc.).",
  },

  // 9. Occupation & Industry (Universe: Civilian Employed 16+)
  {
    id: "C24010_001",
    estimateVariableId: "C24010_001E",
    moeVariableId: "C24010_001M",
    tableId: "C24010",
    label: "Civilian Employed Population 16 Years and Over",
    category: "occupation_and_industry",
    universeId: "civilian_employed_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    description: "Civilian employed population 16+ (occupation universe).",
  },
  {
    id: "OCC_MGMT_BIZ_SCI_ARTS",
    estimateVariableId: "OCC_MGMT_BIZ_SCI_ARTS_E",
    moeVariableId: "OCC_MGMT_BIZ_SCI_ARTS_M",
    tableId: "C24010",
    label: "Management, Business, Science, and Arts Occupations",
    category: "occupation_and_industry",
    universeId: "civilian_employed_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "C24010_001",
    description:
      "Workers in management, professional, scientific, legal, healthcare practitioner, and arts occupations.",
  },
  {
    id: "OCC_SERVICE",
    estimateVariableId: "OCC_SERVICE_E",
    moeVariableId: "OCC_SERVICE_M",
    tableId: "C24010",
    label: "Service Occupations",
    category: "occupation_and_industry",
    universeId: "civilian_employed_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "C24010_001",
    description:
      "Workers in healthcare support, protective service, food preparation, building cleaning, and personal care.",
  },
  {
    id: "OCC_SALES_OFFICE",
    estimateVariableId: "OCC_SALES_OFFICE_E",
    moeVariableId: "OCC_SALES_OFFICE_M",
    tableId: "C24010",
    label: "Sales and Office Occupations",
    category: "occupation_and_industry",
    universeId: "civilian_employed_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "C24010_001",
    description:
      "Workers in retail sales, office support, and administrative assistance.",
  },
  {
    id: "OCC_NAT_CONST_MAINT",
    estimateVariableId: "OCC_NAT_CONST_MAINT_E",
    moeVariableId: "OCC_NAT_CONST_MAINT_M",
    tableId: "C24010",
    label: "Natural Resources, Construction, and Maintenance Occupations",
    category: "occupation_and_industry",
    universeId: "civilian_employed_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "C24010_001",
    description:
      "Workers in farming, fishing, forestry, construction trades, extraction, and equipment maintenance.",
  },
  {
    id: "OCC_PROD_TRANS_MATERIAL",
    estimateVariableId: "OCC_PROD_TRANS_MATERIAL_E",
    moeVariableId: "OCC_PROD_TRANS_MATERIAL_M",
    tableId: "C24010",
    label: "Production, Transportation, and Material Moving Occupations",
    category: "occupation_and_industry",
    universeId: "civilian_employed_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "C24010_001",
    description:
      "Workers in manufacturing assembly, driving, logistics, and material handling.",
  },

  // 10. Housing Tenure (Universe: Occupied Housing Units)
  {
    id: "B25003_001",
    estimateVariableId: "B25003_001E",
    moeVariableId: "B25003_001M",
    tableId: "B25003",
    label: "Occupied Housing Units",
    category: "housing_tenure",
    universeId: "occupied_housing_units",
    unit: "count",
    aggregationMethod: "sum",
    description: "Total occupied housing units (housing tenure universe).",
  },
  {
    id: "B25003_002",
    estimateVariableId: "B25003_002E",
    moeVariableId: "B25003_002M",
    tableId: "B25003",
    label: "Owner-Occupied Housing Units",
    category: "housing_tenure",
    universeId: "occupied_housing_units",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B25003_001",
    description: "Housing units occupied by owner (homeownership baseline).",
  },
  {
    id: "B25003_003",
    estimateVariableId: "B25003_003E",
    moeVariableId: "B25003_003M",
    tableId: "B25003",
    label: "Renter-Occupied Housing Units",
    category: "housing_tenure",
    universeId: "occupied_housing_units",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B25003_001",
    description: "Housing units occupied by renters.",
  },

  // 11. Rent & Home Value
  {
    id: "B25064_001",
    estimateVariableId: "B25064_001E",
    moeVariableId: "B25064_001M",
    tableId: "B25064",
    label: "Median Gross Rent (Dollars)",
    category: "rent_and_home_value",
    universeId: "renter_occupied_cash_rent",
    unit: "dollars",
    aggregationMethod: "median",
    description:
      "Median monthly gross rent (contract rent plus estimated utilities) in cash-rent units.",
  },
  {
    id: "B25077_001",
    estimateVariableId: "B25077_001E",
    moeVariableId: "B25077_001M",
    tableId: "B25077",
    label: "Median Home Value (Dollars)",
    category: "rent_and_home_value",
    universeId: "owner_occupied_housing_units",
    unit: "dollars",
    aggregationMethod: "median",
    description:
      "Median estimated market value of owner-occupied housing units.",
  },

  // 12. Commuting (Universe: Workers 16+)
  {
    id: "B08301_001",
    estimateVariableId: "B08301_001E",
    moeVariableId: "B08301_001M",
    tableId: "B08301",
    label: "Total Workers 16 Years and Over",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    description:
      "Workers 16+ who commuted or worked from home (commuting universe).",
  },
  {
    id: "COMMUTE_DRIVE_ALONE",
    estimateVariableId: "COMMUTE_DRIVE_ALONE_E",
    moeVariableId: "COMMUTE_DRIVE_ALONE_M",
    tableId: "B08301",
    label: "Drove Alone to Work",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B08301_001",
    description:
      "Workers commuting by single-occupant automobile, truck, or van.",
  },
  {
    id: "COMMUTE_CARPOOL",
    estimateVariableId: "COMMUTE_CARPOOL_E",
    moeVariableId: "COMMUTE_CARPOOL_M",
    tableId: "B08301",
    label: "Carpooled to Work",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B08301_001",
    description: "Workers commuting in 2+ person carpool/vanpool.",
  },
  {
    id: "COMMUTE_PUBLIC_TRANSIT",
    estimateVariableId: "COMMUTE_PUBLIC_TRANSIT_E",
    moeVariableId: "COMMUTE_PUBLIC_TRANSIT_M",
    tableId: "B08301",
    label: "Public Transportation to Work (excl. taxi)",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B08301_001",
    description: "Workers commuting by bus, subway, rail, or ferry.",
  },
  {
    id: "COMMUTE_WALK",
    estimateVariableId: "COMMUTE_WALK_E",
    moeVariableId: "COMMUTE_WALK_M",
    tableId: "B08301",
    label: "Walked to Work",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B08301_001",
    description: "Workers walking to workplace.",
  },
  {
    id: "COMMUTE_OTHER_MEANS",
    estimateVariableId: "COMMUTE_OTHER_MEANS_E",
    moeVariableId: "COMMUTE_OTHER_MEANS_M",
    tableId: "B08301",
    label: "Other Means (Bicycle, Taxi, Motorcycle)",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B08301_001",
    description:
      "Workers commuting by bicycle, motorcycle, taxicab, or other means.",
  },
  {
    id: "COMMUTE_WORKED_FROM_HOME",
    estimateVariableId: "COMMUTE_WORKED_FROM_HOME_E",
    moeVariableId: "COMMUTE_WORKED_FROM_HOME_M",
    tableId: "B08301",
    label: "Worked from Home",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B08301_001",
    description: "Workers working remotely from residence.",
  },
  {
    id: "B08013_001",
    estimateVariableId: "B08013_001E",
    moeVariableId: "B08013_001M",
    tableId: "B08013",
    label: "Aggregate Travel Time to Work (Minutes)",
    category: "commuting",
    universeId: "workers_16_and_over",
    unit: "minutes",
    aggregationMethod: "sum",
    description:
      "Total travel time in minutes for all workers who do not work from home.",
  },

  // 13. Household Structure (Universe: Households)
  {
    id: "B11001_001",
    estimateVariableId: "B11001_001E",
    moeVariableId: "B11001_001M",
    tableId: "B11001",
    label: "Total Households",
    category: "household_structure",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    description: "Total resident households.",
  },
  {
    id: "B11001_002",
    estimateVariableId: "B11001_002E",
    moeVariableId: "B11001_002M",
    tableId: "B11001",
    label: "Family Households",
    category: "household_structure",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B11001_001",
    description: "Households with 2+ related individuals.",
  },
  {
    id: "B11001_003",
    estimateVariableId: "B11001_003E",
    moeVariableId: "B11001_003M",
    tableId: "B11001",
    label: "Married-Couple Family Households",
    category: "household_structure",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B11001_001",
    description: "Family households with married couples.",
  },
  {
    id: "B11001_006",
    estimateVariableId: "B11001_006E",
    moeVariableId: "B11001_006M",
    tableId: "B11001",
    label: "Female Householder, No Spouse Present",
    category: "household_structure",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B11001_001",
    description:
      "Family households headed by female householder with no spouse present.",
  },
  {
    id: "B11001_007",
    estimateVariableId: "B11001_007E",
    moeVariableId: "B11001_007M",
    tableId: "B11001",
    label: "Nonfamily Households",
    category: "household_structure",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B11001_001",
    description: "Households of unrelated individuals or single person.",
  },
  {
    id: "B11001_008",
    estimateVariableId: "B11001_008E",
    moeVariableId: "B11001_008M",
    tableId: "B11001",
    label: "Householder Living Alone",
    category: "household_structure",
    universeId: "households",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B11001_001",
    description: "Single-person households.",
  },
  {
    id: "B25010_001",
    estimateVariableId: "B25010_001E",
    moeVariableId: "B25010_001M",
    tableId: "B25010",
    label: "Average Household Size",
    category: "household_structure",
    universeId: "households",
    unit: "ratio",
    aggregationMethod: "mean",
    description: "Average number of occupants per occupied housing unit.",
  },

  // 14. Disability Status (Universe: Civilian Noninstitutionalized)
  {
    id: "B18101_001",
    estimateVariableId: "B18101_001E",
    moeVariableId: "B18101_001M",
    tableId: "B18101",
    label: "Civilian Noninstitutionalized Population",
    category: "disability",
    universeId: "civilian_noninstitutionalized_population",
    unit: "count",
    aggregationMethod: "sum",
    description:
      "Total civilian noninstitutionalized population (disability universe).",
  },
  {
    id: "DISABILITY_WITH",
    estimateVariableId: "DISABILITY_WITH_E",
    moeVariableId: "DISABILITY_WITH_M",
    tableId: "B18101",
    label: "With a Disability",
    category: "disability",
    universeId: "civilian_noninstitutionalized_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B18101_001",
    description:
      "Civilian noninstitutionalized persons with one or more sensory, physical, mental, or self-care disabilities.",
  },
  {
    id: "DISABILITY_WITHOUT",
    estimateVariableId: "DISABILITY_WITHOUT_E",
    moeVariableId: "DISABILITY_WITHOUT_M",
    tableId: "B18101",
    label: "No Disability",
    category: "disability",
    universeId: "civilian_noninstitutionalized_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B18101_001",
    description:
      "Civilian noninstitutionalized persons reporting no disability.",
  },

  // 15. Nativity & Citizenship (Universe: Total Population)
  {
    id: "B05001_001",
    estimateVariableId: "B05001_001E",
    moeVariableId: "B05001_001M",
    tableId: "B05001",
    label: "Total Population (Nativity/Citizenship)",
    category: "nativity_and_citizenship",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    description: "Total resident population for citizenship breakdown.",
  },
  {
    id: "CITIZEN_NATIVE_BORN_US",
    estimateVariableId: "CITIZEN_NATIVE_BORN_US_E",
    moeVariableId: "CITIZEN_NATIVE_BORN_US_M",
    tableId: "B05001",
    label: "U.S. Citizen, Born in the United States",
    category: "nativity_and_citizenship",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B05001_001",
    description: "Native-born citizens born in the 50 states or DC.",
  },
  {
    id: "CITIZEN_NATIVE_BORN_PR_ISLANDS",
    estimateVariableId: "CITIZEN_NATIVE_BORN_PR_ISLANDS_E",
    moeVariableId: "CITIZEN_NATIVE_BORN_PR_ISLANDS_M",
    tableId: "B05001",
    label: "U.S. Citizen, Born in Puerto Rico or U.S. Island Areas",
    category: "nativity_and_citizenship",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B05001_001",
    description:
      "Native-born citizens born in Puerto Rico, Guam, USVI, or Northern Marianas.",
  },
  {
    id: "CITIZEN_NATIVE_BORN_ABROAD",
    estimateVariableId: "CITIZEN_NATIVE_BORN_ABROAD_E",
    moeVariableId: "CITIZEN_NATIVE_BROAD_M",
    tableId: "B05001",
    label: "U.S. Citizen, Born Abroad of American Parents",
    category: "nativity_and_citizenship",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B05001_001",
    description: "Native-born citizens born abroad to U.S. citizen parent(s).",
  },
  {
    id: "CITIZEN_NATURALIZED",
    estimateVariableId: "CITIZEN_NATURALIZED_E",
    moeVariableId: "CITIZEN_NATURALIZED_M",
    tableId: "B05001",
    label: "U.S. Citizen by Naturalization",
    category: "nativity_and_citizenship",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B05001_001",
    description:
      "Foreign-born persons who have acquired U.S. citizenship through naturalization.",
  },
  {
    id: "NOT_A_US_CITIZEN",
    estimateVariableId: "NOT_A_US_CITIZEN_E",
    moeVariableId: "NOT_A_US_CITIZEN_M",
    tableId: "B05001",
    label: "Not a U.S. Citizen",
    category: "nativity_and_citizenship",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B05001_001",
    description:
      "Non-citizen residents (permanent residents, temporary visa holders, asylum recipients, undocumented residents).",
  },

  // 16. Race & Hispanic Origin Aggregate Characteristics (Universe: Total Population)
  {
    id: "B03002_001",
    estimateVariableId: "B03002_001E",
    moeVariableId: "B03002_001M",
    tableId: "B03002",
    label: "Total Population for Race and Hispanic Origin",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    description:
      "Total resident population for race and Hispanic origin distribution.",
  },
  {
    id: "RACE_WHITE_ALONE_NON_HISPANIC",
    estimateVariableId: "RACE_WHITE_ALONE_NON_HISPANIC_E",
    moeVariableId: "RACE_WHITE_ALONE_NON_HISPANIC_M",
    tableId: "B03002",
    label: "White Alone, Not Hispanic or Latino",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description: "Aggregate community baseline: Non-Hispanic White alone.",
  },
  {
    id: "RACE_BLACK_ALONE_NON_HISPANIC",
    estimateVariableId: "RACE_BLACK_ALONE_NON_HISPANIC_E",
    moeVariableId: "RACE_BLACK_ALONE_NON_HISPANIC_M",
    tableId: "B03002",
    label: "Black or African American Alone, Not Hispanic or Latino",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description:
      "Aggregate community baseline: Non-Hispanic Black/African American alone.",
  },
  {
    id: "RACE_AIAN_ALONE_NON_HISPANIC",
    estimateVariableId: "RACE_AIAN_ALONE_NON_HISPANIC_E",
    moeVariableId: "RACE_AIAN_ALONE_NON_HISPANIC_M",
    tableId: "B03002",
    label: "American Indian and Alaska Native Alone, Not Hispanic or Latino",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description:
      "Aggregate community baseline: Non-Hispanic American Indian & Alaska Native alone.",
  },
  {
    id: "RACE_ASIAN_ALONE_NON_HISPANIC",
    estimateVariableId: "RACE_ASIAN_ALONE_NON_HISPANIC_E",
    moeVariableId: "RACE_ASIAN_ALONE_NON_HISPANIC_M",
    tableId: "B03002",
    label: "Asian Alone, Not Hispanic or Latino",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description: "Aggregate community baseline: Non-Hispanic Asian alone.",
  },
  {
    id: "RACE_NHOPI_ALONE_NON_HISPANIC",
    estimateVariableId: "RACE_NHOPI_ALONE_NON_HISPANIC_E",
    moeVariableId: "RACE_NHOPI_ALONE_NON_HISPANIC_M",
    tableId: "B03002",
    label:
      "Native Hawaiian and Other Pacific Islander Alone, Not Hispanic or Latino",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description:
      "Aggregate community baseline: Non-Hispanic Native Hawaiian & Pacific Islander alone.",
  },
  {
    id: "RACE_SOME_OTHER_ALONE_NON_HISPANIC",
    estimateVariableId: "RACE_SOME_OTHER_ALONE_NON_HISPANIC_E",
    moeVariableId: "RACE_SOME_OTHER_ALONE_NON_HISPANIC_M",
    tableId: "B03002",
    label: "Some Other Race Alone, Not Hispanic or Latino",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description:
      "Aggregate community baseline: Non-Hispanic Some Other Race alone.",
  },
  {
    id: "RACE_TWO_OR_MORE_NON_HISPANIC",
    estimateVariableId: "RACE_TWO_OR_MORE_NON_HISPANIC_E",
    moeVariableId: "RACE_TWO_OR_MORE_NON_HISPANIC_M",
    tableId: "B03002",
    label: "Two or More Races, Not Hispanic or Latino",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description:
      "Aggregate community baseline: Non-Hispanic multiracial population.",
  },
  {
    id: "HISPANIC_OR_LATINO_ANY_RACE",
    estimateVariableId: "HISPANIC_OR_LATINO_ANY_RACE_E",
    moeVariableId: "HISPANIC_OR_LATINO_ANY_RACE_M",
    tableId: "B03002",
    label: "Hispanic or Latino (of Any Race)",
    category: "race_and_hispanic_origin",
    universeId: "total_population",
    unit: "count",
    aggregationMethod: "sum",
    denominatorVariableId: "B03002_001",
    description:
      "Aggregate community baseline: Hispanic or Latino population of any race.",
  },
];

export const ACS_VARIABLE_MAP = new Map<string, AcsVariableDefinition>(
  ACS_VARIABLE_REGISTRY.map((v) => [v.id, v]),
);

export function getAcsVariable(
  variableId: string,
): AcsVariableDefinition | undefined {
  return ACS_VARIABLE_MAP.get(variableId);
}

export function requireAcsVariable(variableId: string): AcsVariableDefinition {
  const variable = ACS_VARIABLE_MAP.get(variableId);
  if (!variable) {
    throw new Error(`Unknown ACS variable ID: "${variableId}"`);
  }
  return variable;
}

export function getVariablesByCategory(
  category: VariableCategory,
): AcsVariableDefinition[] {
  return ACS_VARIABLE_REGISTRY.filter((v) => v.category === category);
}

export function getVariablesByUniverse(
  universeId: AcsUniverseId,
): AcsVariableDefinition[] {
  return ACS_VARIABLE_REGISTRY.filter((v) => v.universeId === universeId);
}
