from pathlib import Path
import json, hashlib, random, statistics, math, zipfile
from collections import Counter
ROOT=Path('/mnt/data/depth1')
HEAD='4965f63c41fe69621c72f47725c0d2914257f3ea'
BASE=f'https://github.com/lamontaes/Political-Game-Git/blob/{HEAD}/'
SOURCES=[
 {'id':'code-beliefs','kind':'source-inspected','url':BASE+'src/simulation/political-belief-formation.ts','use':'Existing evaluator, personally sourced factors, private record, no-opinion and player/NPC boundary.'},
 {'id':'code-policy-pack','kind':'source-inspected','url':BASE+'src/simulation/policy-packs.ts','use':'Authored-fiction/sourced provenance, cross-pack issue references, optional proposition rows; inspected lines 1–210.'},
 {'id':'code-policy','kind':'source-inspected','url':BASE+'src/simulation/policy.ts','use':'Definition construction and parameter validation, inspected lines 1–230.'},
 {'id':'code-vocabulary','kind':'source-inspected','url':BASE+'src/simulation/policy-pack-us-state-and-local.ts','use':'Current 13-domain issue keys, actual issue rows read in lines 1–770. This is not a new count of the entire catalogue.'},
 {'id':'code-relationships','kind':'source-inspected','url':BASE+'src/simulation/queries.ts','use':'deriveRelationshipSummary and close-person event consumer, lines 210–290.'},
 {'id':'code-trait-pack','kind':'source-inspected','url':BASE+'src/simulation/people-trait-pack.ts','use':'Five underlying dimensions, scale, ordinary-life-only scope, current movability and contact-answer effects.'},
 {'id':'code-hazards','kind':'source-inspected','url':BASE+'src/simulation/crisis/hazard-producer.ts','use':'Monthly historical-report sampler and two-family mapping; lines 1–285 inspected.'},
 {'id':'code-crisis-types','kind':'source-inspected','url':BASE+'src/simulation/crisis/types.ts','use':'Existing hazard/health/damage/response/continuity records; lines 1–200 inspected.'},
 {'id':'census-weights','kind':'primary-external','url':'https://www.census.gov/data/developers/guidance/microdata-api-user-guide/additional-concepts-0331.html','use':'Survey person weights produce population estimates; do not transfer them to named game-character influence. Official indexed text read.'},
 {'id':'census-puma','kind':'primary-external','url':'https://www.census.gov/programs-surveys/geography/guidance/geo-areas/pumas.html','use':'PUMAs are statistical microdata areas, not exact residential locations. Do not claim a microdata record identifies a particular town resident.'},
 {'id':'census-docs','kind':'primary-external','url':'https://www.census.gov/programs-surveys/acs/microdata/documentation.html','use':'Year-specific codebooks, sample methodology and correct-weight documentation; documentation landing page read, no new national population dataset acquired.'},
 {'id':'bls-jolts','kind':'primary-external','url':'https://www.bls.gov/jlt/jltdef.htm','use':'Vacancy, hiring, internal promotion and separation are different events. The 30-day opening definition is not a required offer-expiry rule. Page states updated May 6, 2026.'},
 {'id':'epa-lifelines','kind':'primary-external','url':'https://www.epa.gov/waterresilience/femas-community-lifelines-construct','use':'Operational service functions and root causes; eighth water-systems lifeline. Page states updated June 10, 2026.'},
 {'id':'epa-dependencies','kind':'primary-external','url':'https://www.epa.gov/waterresilience/water-sector-interdependencies','use':'Energy/water/healthcare/supply-chain dependencies support a shared-impact graph, not fixed catastrophe escalation. Page states updated May 18, 2026.'},
 {'id':'noaa-catalog','kind':'primary-external','url':'https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdc%3AC00510/html','use':'Weather-event families, damage/injury reports and reporting delay; official catalogue metadata, not newly compiled hazard rates.'},
 {'id':'nws-reports','kind':'primary-external','url':'https://www.weather.gov/unr/storm_reports','use':'Different coverage periods and reported-event limitations; no probability that an unreported event never happened.'},
 {'id':'ssa-names','kind':'primary-external','url':'https://www.ssa.gov/oact/babynames/background.html','use':'Birth-year/sex recorded categories, shared names, suppression and pre-1937 coverage limits; not present gender-identity statistics. March 2026 extraction stated.'},
 {'id':'prior-personality','kind':'previous-project-research-reused','path':'Personality_Research_and_Catalogue.md','use':'Existing 121 candidates and 14 families; not a new survey, empirical prevalence dataset or blanket approval of every candidate.'},
 {'id':'current-queue','kind':'worker-report-read','url':'https://docs.google.com/document/d/1yVVxtG0YNaKsb85O5TF9ZkxGWWU5N9sSoQWM1qa_FVM/edit','use':'Read complete 16:34Z / 22-open / 44-answered render. Worker caller counts beyond independently inspected bodies remain reports.'},
]

def answer(key,title,status,owner,body,test,sources):
 return dict(requestId=key,title=title,status=status,receivingOwner=owner,answer=body,acceptance=test,sourceIds=sources)
ANS=[]
ANS.append(answer('what-the-simulated-people-are-a-sample-of','One population, two resolutions','resolved-design-implementation-needed','existing world/population + people + economy/elections owners',
'''Use one population with two levels of detail, not a weighted cast versus decorative scenery. Named residents are individually tracked members; aggregate cohorts carry the remaining residents. For each non-overlapping geographical cell, total residents = tracked residents + residual residents. Detailing an existing resident transfers one from residual to tracked, without changing total, employment, money, household demand or possible ballots. A genuine birth, death or move changes the appropriate totals once. A named institutional appointment is not a birth. Apply subgroup attributes consistently when materializing, so selecting a worker also removes that worker from the residual worker count.

The cast may include independently continuing neighbours, coworkers and community members, not just political vacancies or the player's acquaintances. Store a compact stable individual before deeper elaboration when needed. Population size does not prescribe a linear number of full biographies; select detail by causal relevance and measured performance, with no permanent per-town character cap. Decisions by aggregates must not manufacture a second set of named-person consequences.

Start regional cohorts from sourced compatible reference-period totals and distributions, reconcile correlated attributes rather than multiplying unrelated percentages. PUMS weights concern the sample's statistical representation, not a named fictional character's power. PUMA data is not an exact town address. Keep sourced baseline, simulated current state and published in-game estimates separate. Country/state/county/town totals must avoid overlap: use a canonical disjoint population base and derive views, rather than separately owning the same people at each level.

A contest should eventually use its actual represented electorate: eligible pool under game rules, participation, candidate choices and valid totals. Do not relabel existing basis points as counted people. Cohort counts may implement ballots without simulating each voter, while a tracked person's participation is included only once. Do not calculate national opinion from a convenience sample of senators and acquaintances. The existing campaign-curve hold is not reopened by this population answer; record its bridge as a separate integration dependency.''',
 'Materialize 100 pre-existing residents: totals and control-world output remain unchanged. Move one resident: origin -1 and destination +1, national net zero. Birth/death change exactly one count. Named voter extracted from a cohort is not an additional ballot. Cross-place comparison uses fixed geography/version.',
 ['current-queue','census-weights','census-puma','census-docs']))
ANS.append(answer('nobody-is-changed-by-what-happens','Connect the full belief input, not an empty function call','resolved-connection-implementation-needed','existing policy + people/beliefs + news/event owners',
'''(1) Put fictional policy propositions in the existing authored-fiction pack form, referring to existing sourced issue keys. A policy vocabulary source is not evidence that a fictional proposal was enacted. Do not import the synthetic demo as production content or disable the production boundary. Preserve the current useful issue IDs while the earlier 14-domain/13-domain crosswalk is received.

(2) First live occasion: a person legitimately encounters a concrete proposal through a conversation, a report, an office briefing or their experience of a supported operative policy. Record what they actually learned; connect relevant existing goals, values, appraisals, expertise and earlier views to the proposal. The evaluator receives these source-linked factors. Current source defaults to a moderate no-opinion consideration: an empty scheduled call does not supply personally meaningful reasons. A scheduler and one proposition row alone are insufficient for depth.

(3) Go THROUGH evaluatePoliticalBeliefFormation and applyNpcPoliticalBeliefFormation for NPCs. They already validate sources and persist a decision trace. The outcome can be no-opinion, defer, conflicted, tentative or settled support/opposition. Initial weak/secondhand evidence should normally be capable of tentative or unresolved results, not require a position. Conviction is not salience and neither is inflexibility.

Use a stable actor + proposition/selected proposal revision + new-evidence identity. Duplicate headlines and opening the Journal are not new evidence. Reconsider when new relevant facts, commitments or experience arrive; do not repeatedly reroll an unchanged issue until support appears. Private belief stays private; public declaration, promise and vote each have their own existing act. Never apply the NPC writer to the controlled player; give the player an explicit view/statement choice. Broad proposition-family preference is not unconditional agreement to every amount, target or exemption in a specific bill. Version/bind the actual proposal context before a consumer uses it to infer a bill-level position.''',
 'In an ordinary generated world, two differently situated NPCs encounter the same valid proposal and receive inspectable different factors; either may remain uncertain. An unexposed control knows nothing new. Re-reading the same article adds no second persuasion event. A change of material bill terms causes explicit reassessment, not reuse of an unrelated broad view.',
 ['code-beliefs','code-policy-pack','code-policy','code-vocabulary','current-queue']))
ANS.append(answer('where-a-persons-politics-comes-from','People have reasons before the party label','resolved-design-implementation-needed','existing people/beliefs + party/electorate owners',
'''Do not target or repair the reported 48% unaffiliated figure by assigning everyone a party. Separate unknown affiliation, deliberate independence, party sympathy, organizational membership and any jurisdiction-specific registration. Missing producer coverage is a defect; a genuine independent is not.

Actual goals, values, relevant information and lived consequences are primary inputs to a person's issue positions. Family and social history can supply known cues and identification, but not compulsory inherited beliefs. Temperament chiefly influences attention, confidence, openness, approach and expression, not a left/right lookup. Parties offer current platform positions, leadership and activity that people can know and evaluate; party labels must not directly overwrite an individual's views.

For generated adults, produce a coherent prior social/political history where supported rather than wait until their profile is opened. People can remain disengaged; awareness and affiliations can develop at different life stages. For changes, distinguish an issue disagreement, a changed leaning, a formal departure and joining a rival. New parties grow when people actually hear of them, see a reason to engage and choose to join or help; no automatic recruits per elapsed week. Shared workplace or local conditions can create different appraisals, not demographic unanimity.

Example is a test situation, not a fixed character: a thirty-year-old worker hears a colleague's proposal after their schedule changes. Their income needs, existing views, trust in the source and knowledge of the terms are relevant. They might support the proposal while staying with their current party, change their party leaning, or reject the claim. The result must be traceable to those inputs rather than a seeded stance selected solely from their ID.''',
 'Hold party fixed and vary meaningful knowledge/goals: an actor can differ on a proposal. Hold actor/state fixed and reopen the screen: no reroll. A known new party can recruit through a real invitation and consent while an unexposed control does not silently join. Independent remains an allowed explicit state.',
 ['code-beliefs','current-queue']))
ANS.append(answer('what-moves-a-relationship','Conduct changes the relationship; no click counter','resolved-design-with-labelled-test-rubric','existing people/relationships + ordinary work/content owners',
'''Replace the single closeness sum as the authoritative interpretation with the already approved actor-specific warmth, trust, respect, commitment and unresolved tension over the existing interaction/appraisal history. The current source treats most maintained interactions as positive, adds 1/2/3 and declares close at 3; conflict-prefixed records are negative regardless of a more nuanced outcome. These rules also feed whether a person is close to someone affected by an event. This is a consequential reader connection, not cosmetic labeling.

Record intent, attempt and fulfillment separately. Agreeing to help creates a commitment and may affect anticipation; delivering meaningful help supplies evidence about reliance. A competent result can increase respect without friendship. A disagreement can preserve affection, a breach can reduce trust without destroying shared history, and an apology need not restore what it acknowledges. Do not use the namespace alone to decide direction: a successful conflict resolution is not automatically harm.

A normal refusal is a recorded response, not automatically a grievance or punishment. A witnessed contemptuous rejection or refusal violating an actual duty can be appraised differently. Reserved people may prefer different encounter forms or initiate less often; they are not assigned worse relationship quality. Conciliatory people can choose repair without consenting to abuse; confrontational people can maintain loyal friendships. A long gap changes context and possible expectations, not an automatic affection tax. End contact/partnership with a real action or event; do not erase knowing someone.

The supplied conduct rubric gives qualitative direction and illustrative bounded contribution ranges for private test only. These are weights of evidence on separate interpretations, not emotional measurements or thresholds that promise friendship after N actions. Evidence deduplicates by the underlying encounter/obligation and acknowledges magnitude, stakes, consent, alternatives and actor interpretation. Test whether ordinary interactions can sustain an actual friendship over time without grinding.''',
 'Three greetings do not establish enduring trust or closeness. One significant fulfilled obligation is distinguishable from three promises. A recorded refusal survives as a response without a compulsory penalty. A repair interaction can reduce tension without erasing the breach. Ten idle years do not apply an affection tax.',
 ['code-relationships','code-trait-pack','current-queue','prior-personality']))
ANS.append(answer('ordinary-life-trait-set','Use the researched breadth across settings','resolved-reuse-and-connection','existing people/trait and legislative decision owners',
'''Retain the five underlying temperament dimensions. The previously delivered 121-candidate, 14-family catalogue is the research vocabulary; do not replace it with another arbitrary ceiling or silently make all 121 separate latent axes. Several named descriptors can be meaningful combinations or distinct additional tendencies. Skills, interests, temporary feelings and goals remain separately meaningful attributes of the same person.

Implement families in complete behavioral groups rather than all labels before any effect. Every added descriptor needs at least a clear meaning and nearest-neighbor distinction, a supported decision effect, an expression effect, a context where it should not matter, and interaction with other traits. 'Studious' is effort in acquiring knowledge, not knowledge granted at generation; 'cocky' is not competence; 'brazen' is not every kind of risk.

The inspected people-mind pack explicitly admits only life:ordinary scope. Extend the appropriate shared trait registration and existing decision adapters so the same person's traits can inform workplace, civic and governing contexts. Do not create a second legislative personality to replace their ordinary identity or bypass scoped admission accidentally. Scope controls relevance, not the existence of a different person in each room. No trait guarantees another person's agreement.''',
 'Follow one person from a work conversation to a public-role negotiation: identity and trait evidence stay the same, with context-specific goals/authority and different relevant considerations. A trait without a supported consumer is reported as unconnected, not counted as finished depth.',
 ['code-trait-pack','prior-personality','code-beliefs']))
ANS.append(answer('person-starting-trait-count','Small visible starting profile, not a small personality','resolved-labelled-private-baseline','existing people/character setup owners',
'''Keep the owner's one-or-two salient starting descriptors as the working adult baseline. For the first private comparison use a 50/50 one-versus-two draw; this is explicitly authored calibration, not a measured human distribution or an owner-selected exact percentage. It applies to salient descriptors, not deletion/zeroing of the five underlying dimensions. Existing meaningful generated traits are not discarded to satisfy a display budget.

Use the same underlying generation policy for NPCs and the player. The player can confirm/change/skip their suggested profile; observers see only justified impressions about others. Age informs plausible experiences and the evidence behind a disposition, not a fixed birthday that awards another trait. No automatic lifelong maximum, no count that rises every time another memory is written. Adding later nuance can mean clearer recognition of existing character as well as actual development. Strong adult moral/role labels should not be assigned to young children simply to fill two slots.''',
 'Generate adults with one/two salient descriptors while other represented dimensions remain available; verify same seed and version repeat. No automatic extra trait after a birthday or ten events. Observer card does not show unknown latent descriptors.',
 ['code-trait-pack','prior-personality','current-queue']))
ANS.append(answer('trait-prevalence-across-a-population','Separate authored sampling from human prevalence','resolved-private-calibration-not-empirical','existing people/trait generation owner',
'''No source in the existing game/mod research measures real-world prevalence of these 121 authored labels. Do not pretend that it does. The accompanying family sampling profile is a versioned private-playtest baseline, with a seed-repeatable one/two-descriptor experiment and its measured artificial output.

Select eligible descriptor families by the supplied weights for each initial slot, then choose distinct, genuinely distinguishable supported descriptors. Two compatible traits in the same family remain possible; organizational families are not exclusion rules. This prevents families with more synonyms from gaining frequency merely because they have more rows. Family selection and trait intensity are different. Extreme disruptive traits may have explicit lower authored weights within their family; do not infer crime, competence, honesty or politics from demographic identity. Circumstances may affect exposure, role selection and the expression of traits, not retroactively rewrite a person's personality to match a job title.

These are not neighbourhood quotas. Do not ensure exactly N vindictive people in every town. A different seed can yield a different mixture, and particular social networks can be nonrepresentative. Compare the cast a player meets with the larger simulated cohort before concluding that a cluster is a nationwide prevalence claim. The 14 families are organizational categories, not mutually exclusive kinds of human.''',
 'Adding ten prose variants/synonyms does not change family frequency. Artificial sample counts are labelled as simulated sampling results. Same configuration/seed repeats; unsupported descriptors are excluded visibly without silently making all others equivalent.',
 ['prior-personality','code-trait-pack','current-queue']))
ANS.append(answer('personality-change-bands','Calibrate with evidence and time, not more permission gates','resolved-private-test-comparison','existing people/trait-change + playtest owners',
'''The old repeated-pressure/permanent-perMove defect is not assumed current: the inspected pack already has bounded pressure, spacing and an unsettled floor. Keep the valid repair. Current settle periods of 8–15 years remain authored baseline values, not established psychology. The ordinary trait scale admits moderate and strong; do not silently feed a defining value merely because a movability table has a defining column.

Use two explicit private profiles in a controlled comparison. A is the current pack unchanged. B retains its settledByStrength, floor and pressure cap, but tests 2 years for reliability, 3 for sociability/conflict/risk, and 5 for deliberation; retain existing spacing initially to isolate the change. Settling here is the time for a changed tendency to become established, not the interval until its next change. These alternative years are authored exploration, not empirical rates, not a claim every person changes on a timer, and not an approval to force a fixed hierarchy forever. The owner approved this labelled experiment, not these exact numbers as final production truth.

Do not interpret an episode count as independent evidence: repeated phases/headlines of the same incident share provenance, while distinct events can happen on the same date. Spacing can limit correlated influence; it must not erase the fact that a distinct incident occurred. Immediate grief, confidence, grievance or a changed goal may precede any lasting trait shift. Many everyday situations should change those nearer states instead of rewriting temperament.

Retain persistence/reachability invariants already in the trait tests. Show a faint tendency under sustained evidence and a strong tendency under minor versus genuinely formative experiences. A whole lifetime is not expected to fill a quota of personality changes. Compare what the player experiences, not only whether either profile can pass a test that forces movement.''',
 'Baseline A versus B on the same events/randomness: report when a trait changes, when it does not, and intermediate temporary/relationship/goal consequences. Repeated retries with the same source add no evidence. No automatic change caused solely by a timer completing.',
 ['code-trait-pack','prior-personality','current-queue']))
ANS.append(answer('planning-words-that-became-product-rules','Assignment history cannot prohibit a game feature','resolved-authority-existing-owner-to-verify-current-source','existing art/client and coordination owners',
'''A work allocation is not a creative prohibition. Distinguish an explicit owner product restriction (with decision reference), a concrete missing dependency, and a temporary live work lease (owner/checkpoint). They cannot share one unexplained string that hides content as history. Old assignment initials, a missing worker plan or a stale worktree do not justify permanent feature gating.

The queue reports five d-held-people requests hidden by a September 15 allocation. This batch has not independently re-read their current source, so the existing owner verifies the exact current entries before touching them. Generation is not generally closed under current approved art scope. Remove an obsolete assignment hold when confirmed, reconcile each request against already delivered/currently needed work, then return needed work to its real queue; delete genuinely obsolete duplicate requests by existing policy. Do not resurrect completed work or self-approve images. Unknown lease ownership needs explicit coordination, not an automatic product ban or deletion of active work.

Apply the same distinction to 'awaiting researched coefficient' after DEPTH1: an adjustable labelled private assumption is now authorized inside settled behavior. The historical lack of a per-number approval cannot keep the whole system disabled. A true creative hold remains meaningful and must not be released by an expired engineering lease.''',
 'Expired/missing assignment owner is distinguishable from a current owner restriction and an actual dependency. Current completed art is not regenerated; still-needed requests are visible. No change to exact human review decisions.',
 ['current-queue']))
ANS.append(answer('temperament-marks-on-a-person-card','Readable observed character before eleven symbols','resolved-design-art-approval-separate','existing people-card/UI and art owners',
'''Use plain, prominent, short observed descriptors first. Optional small symbols may reinforce those words, but are not required for the behavior or card to ship and must not become an eleven-icon neutral/pole checklist. Keep the five underlying dimensions, and surface relevant known named traits as breadth arrives. 'Neither, much' need not occupy a dedicated symbol slot; balanced is not unknown, and unknown must not be displayed as balanced.

Show another person's descriptor only when justified by observation or legitimate information, using the existing observed/actual distinction. An early impression can be qualified and later revised. No meter/star/rating that suggests measured reliability. No universal green good/red bad moral classification. However, the text may honestly explain that unreliable follow-through matters for a specific commitment; a no-good-end art constraint does not abolish consequences.

The requested symbols remain optional candidates for existing art review, not automatic approval or an excuse to delay people depth. Do not put letters/numbers into generated image assets to encode facts; text is rendered by the interface, independent of the asset. These choices change presentation only, not personality-change intensity or the person's underlying traits.''',
 'A new acquaintance shows only an appropriately tentative known impression; repeated card opens reveal nothing new. A later contradiction can revise the impression. Plain text remains fully understandable with symbols absent.',
 ['current-queue','prior-personality']))
ANS.append(answer('cheating-covers-all-three','Three different acts, not one misconduct button','resolved-abstract-connection-contract','existing life/relationships, education and oversight/election owners',
'''Academic cheating: a particular represented assessment or submission breaches its applicable academic rules. An assessor, participant or evidence can expose it; an institution then applies its actual process and disposition. If undiscovered, any recorded result remains a result, but competence/knowledge is not magically created. No requirement to make the player perform routine homework or a how-to cheating minigame.

Romantic infidelity: conduct breaches the relationship's actual agreement, not merely the existence of another friend or a universal marriage flag. Discovery follows witnesses, disclosure or available evidence. Partners may disagree, end or attempt repair; no automatic breakup, omniscient partner, violence or universal reputation penalty. Consent and relationship terms remain specific to the people. This fits broader relationship scope but is not made a prerequisite for the current friendship/career milestone.

Election misconduct: record an abstract prohibited act by a responsible actor under the contest's rules, its evidence and any legitimate inquiry/remedy. Do not supply real-world methods, vulnerabilities or concealment instructions. Suspicion is not guilt; wrongdoing does not automatically reverse an election without the supported adjudication and result-correction route. If unobserved, actors without knowledge do not punish it; actual affected records/resources still follow the underlying act. Use existing history, evidence, press and institutional powers rather than a single 'cheating score'.

All three separate underlying act, belief about it, allegation, investigation and consequences. An unsuccessful attempt and a successful act differ. A label never becomes proof, and a character trait alone never declares someone guilty.''',
 'For each kind, contrast observed/unobserved and substantiated/unsubstantiated cases. Private consequences do not become universal public knowledge. Same episode cannot apply a penalty once per reader.',
 ['current-queue']))
ANS.append(answer('how-a-life-begins-and-grows-up','Family continuity supports the world; friendship/career comes first','partial-answer-scope-and-core-continuity','existing people/family + population owners',
'''Live population growth must include births, deaths and migration, not just new named candidates. That is part of the approved two-level population. Reuse existing family-addition, kinship, household and authority writers for named cases; aggregate demographic events must account for tracked individuals once. Election turnover should preferentially use coherent existing/revealed residents, not make demographic growth a side effect of needing a challenger.

A partnership, household membership, parenthood, caregiving and child authority are different relationships. Parent absence needs a reason where known (nonresident, separated, died, unknown), not a missing row interpreted as abandonment. Ending an adult partnership does not automatically end parenthood, erase contact or assign a child's care to nobody. Unknown is not immoral. Children need age-appropriate available choices and care/education context; sharing the scheduling/history machinery with adults is fine, while adult job/campaign permissions and adult-only content are not.

Mutual decision and 'not now' in the existing family-plan shape are compatible with agency. Do not require every birth to come from a formal partnership, nor interpret agreement as an immediate guaranteed child. Broader casual-dating, pregnancy/adoption and parenting content needs the specific implementation scope taken back to the owner when it materially changes the next milestone. This approval prioritizes FRIENDSHIPS and CAREER CHANGES; do not delay those behind a full fertility/courtship model or assume the owner just approved every detailed family design in the queue. Earlier broader accepted scope is not revoked.''',
 'A named person’s move changes household/place, not identity or prior friends. A child retains represented parents/known circumstances through household changes. Population growth does not depend on how many offices/screens are opened. Current priority work can ship without full family simulation.',
 ['current-queue','census-weights']))
ANS.append(answer('cross-gender-given-name-rate','Use name-specific source counts, not a universal crossing percentage','method-answer-data-compilation-still-needed','existing naming/source owner',
'''A single crossing percentage is not supported. Use the source's per-name, birth-year and recorded-sex counts as the factual naming evidence; a name may occur in multiple categories with different frequencies. Names shared across categories are not reserved for nonbinary characters. Never infer a person's gender from their generated or chosen name.

SSA records sex on applications, not a present-day gender-identity distribution; errors and naming changes mean rare cross-category entries cannot be equated automatically to transgender/nonbinary prevalence. Character identity stays an independently recorded input. Any mapping from historical naming evidence to current generated identity is an explicitly authored, editable game rule, with player-name override preserved. Do not call it a measured identity rate.

Suppressed counts below five are not observed zeros. Keep the published record's scope: national files exclude territory births, which have separate products. This batch answers the method, not a compiled numeric table; the data owner should receive actual source counts through the established data path before claiming factual frequency weights.''',
 'A genuinely shared name can be generated for more than one applicable identity; no name read-back changes gender. A suppressed cell is not treated as proven impossibility. Current named characters are not renamed after an importer update.',
 ['ssa-names','current-queue']))
ANS.append(answer('given-name-fashion-by-birth-year','Birth cohorts, not one timeless curated list','method-answer-data-compilation-still-needed','existing naming/source owner',
'''Use a documented release of annual SSA counts to draw plausible birth-cohort names, not a hand-written list of supposedly permissible decades. Adjacent-year smoothing, where chosen to reduce sparsity, is an authored sampling choice and must not invent data or hard-ban a known uncommon historical name. Extend the corpus with actually represented older names rather than merely filtering today's 346-name list. Historical rarity is not an impossibility claim.

SSA states the underlying U.S. births begin after 1879 and coverage before 1937 is incomplete. That limits historical certainty; record it rather than claiming complete 1880-era census coverage. Future birth years use an explicit projected game distribution, not fabricated future SSA observations. Preserve source spellings/normalization notes and the right territory scope. No existing person's name changes as they age, upon a new data release, or when their record becomes more detailed.

The two naming questions should share one acquisition/compilation rather than two surveys. This is not permission to delay present people/career connections while an exhaustive historical naming catalogue is built.''',
 'Older and younger sampled birth cohorts differ when supported by source counts, without hard decade discontinuities. Same saved person retains their name. No inferred age or gender is read from a name.',
 ['ssa-names','current-queue']))
ANS.append(answer('national-range-instrument-for-non-states','Distinct jurisdiction profiles, shared execution','resolved-architecture-factual-rows-remain','existing nationwide/government owner',
'''Do not infer D.C. or Puerto Rico's institutional topology from a range of states. Use their own recorded structural profiles with the same shared office/term/authority/legislature machinery; a separate profile is not a separate engine. Reuse the banked D.C. evidence. Puerto Rico scope is already approved, but its factual offices/qualification rows still require the separately queued compilation.

An approved authored game assumption may fill a compatible unresolved parameter inside an accurately identified institution; it cannot manufacture a state governor or a second chamber where there is none. A present-day source-observation timestamp is also not automatically the rule's historical commencement date. Do not let a source-fetch timestamp ban an otherwise approved contemporary game profile. Broader exact PR rules remain unresolved and are not fabricated by this connection answer.''',
 'Topology and action permissions derive from the jurisdiction profile, not membership in a hardcoded 50-state list. Known distinct offices remain distinct. Unsupported factual fields are explicit, while unrelated supported life/government actions continue.',
 ['current-queue']))
ANS.append(answer('example-county-treasurer-selection','Remove the schema example from production intake','not-a-research-assignment','existing source-owned research queue publisher',
'''The record explicitly labels itself a worked example for the request schema. Do not commission a 50-state treasurer survey from it. The queue owner should keep examples in example/test documentation rather than publish them as live asks, and remove this example from the active generated queue. If a real implementation later needs a specific selection rule, file that real need with its actual institution and field.''',
 'Generated live queue excludes a clearly marked schema example; genuine current requests remain present.',
 ['current-queue']))
# A separate bounded owner question is deliberately NOT counted as an answered design.
QUESTION={'requestId':'political-violence-what-to-ask-the-owner','status':'owner-question-prepared-not-resolved','question':'Should the player be able to initiate or order political violence, or only encounter it and decide how to respond?','boundary':'Either branch stays abstract and causally grounded. Existing permission for severe world events remains; this question does not decide graphic presentation, exact rates or detailed response powers. No real-world methods are provided.'}

# Meaningful mechanical recipes, not finite stories. Selected participants/places/amounts are runtime bindings.
RECIPES=[]
def recipe(key,group,trigger,actors,variants,links,result,never,issue=None):
 RECIPES.append(dict(key=key,group=group,trigger=trigger,participantRoles=actors,variationAxes=variants,connects=links,requiredResult=result,forbiddenShortcut=never,existingIssueKey=issue,status='design-ready-receiving-input-not-executable-schema'))
recipe('encounter-through-shared-work','friendship','Compatible people actually participate in the same work or project',['participants','optional introducer'],['task purpose','voluntary approach','knowledge','temperament','stakes'],['work','availability','contact','knowledge','relationship'],'A remembered introduction or conversation and any freely chosen next contact.','Same employer/proximity automatically means friends.')
recipe('reconnect-with-shared-past','friendship','A real old connection gains a present reason or opportunity to reconnect',['initiator','known contact'],['time since contact','shared event','present goal','message tone','availability'],['history','memory','private goals','communications'],'A specific response, alternative or nonresponse with preserved identity and context.','Teacher/colleague must contact every player on a fixed date.')
recipe('trusted-introduction','friendship','Someone knows two people and sees a relevant mutual opportunity',['introducer','two contacts'],['reason','privacy consent','prior trust','recipient interest'],['relationship','knowledge','work','organizations'],'Recipients actually learn permitted contact/context; acceptance is separate.','Friendship transfers automatically along a network edge.')
recipe('shared-success','friendship','Actual cooperative work achieves a supported result',['collaborators'],['credit','effort','risk','division of work','recognition'],['work/project','memory','respect','reputation'],'Participants appraise who contributed and whether to cooperate again.','A success popup gives all bystanders trust.')
recipe('conflicting-priorities','friendship','Two genuine commitments compete for finite time/resources',['person','affected people'],['stakes','alternatives','notice','duty','prior promises'],['calendar','commitments','relationship','career'],'A choice, explanation or renegotiation changes the specific commitments.','Create conflict by silently booking mutually impossible routine obligations.')
recipe('privacy-and-confidence','friendship','A person chooses whether to disclose or protect a specific known matter',['speaker','recipient','affected person'],['public/private status','intent','permission','stakes','later evidence'],['knowledge','deception','relationship','memory','news'],'Actual disclosure/access and observer-specific appraisal.','Everyone automatically learns a secret or every disclosure is malicious.')
recipe('disagreement-and-repair','friendship','A recorded disagreement or breach leaves unresolved tension',['participants'],['severity','accountability','remedy','belief difference','boundaries'],['relationship','dialogue','commitments','memory'],'Possible repair/revised terms/separation with trust and warmth allowed to differ.','Apology resets every relationship dimension or conflict namespace always means harm.')
recipe('friend-moves-or-changes-role','friendship','An actual move/job/office change alters proximity or availability',['mover','existing contacts'],['distance','worktime','reason','contact preference'],['population','housing','work','travel','relationships'],'The person and history persist; feasible meetings and routes change.','Moving deletes friendships or forces emotional decay.')
recipe('referral-to-real-vacancy','career','An employer has real available work and a contact knows it',['employer','referrer','candidate'],['requirements','pay','schedule','location','referrer knowledge'],['work','employer budget','relationships','information'],'A reachable recruitment opportunity with appropriate terms; referral is not automatic hiring.','Invent vacancy merely to reward friendship.')
recipe('competing-job-offers','career','Candidate has multiple genuine offers or staying is viable',['candidate','employers','household if relevant'],['compensation','hours','commute','security','goals','trust'],['offers','schedules','money','housing','goals'],'Explicit chosen terms, declines/lapses and feasible transition.','All offers stay forever or choosing one automatically fills every other vacancy.')
recipe('internal-promotion','career','Organization has responsibility/capacity need and a candidate is considered',['employee','manager','other candidates'],['experience','performance evidence','trust','role need','pay authority'],['career','skills','relationships','organization authority','pay'],'Role/terms change with evidence; other applicants respond if they learn.','N shifts automatically promotes or internal promotion counts as a new resident.')
recipe('training-for-opportunity','career','A chosen career opportunity needs a supported skill/credential',['learner','provider','employer'],['prior skill','cost','available time','aid','job demand'],['compact education','work','finance','contacts'],'Background meaningful training progress and later eligibility under actual terms.','Restore rejected certificates, literal homework grind or instant knowledge.')
recipe('hours-or-pay-negotiation','career','Either worker or employer has a real reason to revisit terms',['worker','authorized manager'],['capacity','financing','outside options','performance','household needs'],['terms','schedule','output/service','payroll','relationship'],'Agreed/rejected/countered terms have downstream budget and availability consequences.','Charisma creates money or fewer days necessarily means fewer paid hours.')
recipe('position-ended-or-layoff','career','An employer decision or contract condition actually ends work',['employer','worker','affected household'],['cause','notice','support','vacancies elsewhere','financial cushion'],['employer finance','employment','household income','goals','relationships'],'Correct cessation, remaining obligations and possible job search/support opportunities.','Every missed shift fires someone or hardship forces a political conversion.')
recipe('employee-exit-and-replacement','career','Worker leaves through a real decision/retirement/move',['worker','employer','colleagues','potential replacement'],['continuity need','knowledge transfer','recruitment urgency','budget'],['career','vacancy','scheduling','services','social network'],'Organization adjusts its staffing/delivery; replacement is an independently assessed person.','Vacancy always fills immediately with a newly born adult.')
recipe('small-enterprise-change','career','Represented employer opens/expands/contracts or transfers ownership',['owner/manager','workers','customers'],['demand','resources','credit','permits','competition'],['business','population work cohorts','tax base','local services'],'Capacity and payroll change through real resources and actors.','Every new business grants a fixed universal growth bonus.')
recipe('change-tax-base-rate','legislation','A proposal changes a specified taxable activity or rate',['proposer','tax authority','affected groups'],['base','rate','exemption','phase-in','collection cost'],['propositions','legislation','accounts','household/business','macro'],'Effective rule changes actual collections; behavioral response is separately labelled.','Tax increase automatically triggers positive national revenue-windfall growth.','fiscal.income-tax')
recipe('fund-service-capacity','legislation','Government considers funding for an actual service',['proposer','appropriator','delivery agency','workers','users'],['amount','source','staffing','capital vs operating','target','start'],['budget','procurement','work','service','population','beliefs'],'Authority then actual obligation/payment/staffing yields capacity and delivery.','Passage alone delivers the service or spends every authorized dollar.','fiscal.appropriations')
recipe('eligibility-and-benefit-change','legislation','A proposal changes who may receive a defined supported benefit',['proposer','administrator','eligible/ineligible groups'],['eligibility','amount','duration','funding','application friction'],['law','eligibility','service','accounts','household','knowledge'],'Affected people can qualify/apply/receive under implemented terms.','A vocabulary label is a completed entitlement model.','health-human-services.food-and-income-assistance')
recipe('health-capacity-access','legislation','A health service or coverage rule has a represented need or reform proposal',['agency','providers','workers','users','legislators'],['coverage','affordability','capacity','geography','funding'],['health','public/private spending','jobs','service access','beliefs'],'Compact coverage/cost/capacity/access states change before any uncertain health-outcome response.','Build a detailed medical simulator first or equate insurance enrollment to treatment.','health-human-services.hospitals-and-providers')
recipe('housing-permission-construction','legislation','A land-use or building proposal concerns actual sites/households',['authority','applicants','builders','residents'],['permitted use','density','cost','finance','construction time'],['zoning','permits','housing','work','infrastructure','population'],'Permissions change feasible projects; resources and construction determine eventual supply.','A zoning vote immediately creates homes.','housing-land-use.zoning')
recipe('maintenance-and-resilience','legislation','A service asset needs planned maintenance or a proposed resilience upgrade',['asset operator','budget authority','workers','users'],['asset condition','priority','outage tradeoff','funding','hazard context'],['budget','procurement','maintenance','crisis exposure','work'],'Actual completed work changes condition/vulnerability and service continuity.','A preventive appropriation automatically prevents every future hazard.','transportation-infrastructure.roads-and-bridges')
recipe('report-inspect-and-enforce','legislation','An operative rule creates a specific reporting, inspection or enforcement duty',['regulated actor','agency','reviewer'],['scope','evidence','deadline','staffing','remedy','appeal'],['law','work queues','evidence','oversight','accounts','news'],'Assigned duties can be fulfilled/overdue/examined and produce supported remedies.','Duty exists only as bill text or allegation equals guilt.','government-operations.public-contracting')
recipe('amend-repeal-and-transition','legislation','A real operative provision is amended, expires or is repealed',['proposer','body','implementer','affected parties'],['revision','effective date','grandfathering','outstanding commitments'],['versioned law','programs','accounts','rights','memory'],'Future application changes coherently, preserving completed acts and surviving obligations.','Repeal erases money already paid or roads already built.','government-operations.legislative-procedure')
recipe('flood-and-displacement','crisis','A geographically supported hazard episode affects exposed assets',['residents','operators','responders','officials'],['footprint','duration','water intensity','vulnerability','warning','capacity'],['hazards','housing','work','transport','response','finance'],'Actual damage/service loss/displacement then response and recovery.','One independent flood per household or damage proportional to number of visible characters.')
recipe('wind-and-grid-loss','crisis','Supported wind episode or equipment damage affects connected infrastructure',['operator','residents','employers','responders'],['footprint','network redundancy','repair resources','timing'],['hazards','energy','water','work','health access','recovery'],'Service dependency changes with mitigation and restoration; cascading harm is conditional.','Every severe storm causes the same chain or duplicate damage per article.')
recipe('heat-and-service-pressure','crisis','A supported heat episode meets exposed people and capacity constraints',['residents','employers','service operators','officials'],['duration','exposure','cooling access','work conditions','resources'],['hazards','health capacity','energy','work','public service'],'Exposure/availability and supported relief measures change; label uncalibrated outcome responses.','Borrow flood-destruction formula for heat or turn temperature into a fixed death quota.')
recipe('winter-transport-disruption','crisis','Supported cold/snow/ice episode obstructs actual transport/services',['travellers','operators','employers','responders'],['routes','conditions','maintenance','duration','prior preparation'],['hazards','travel','calendar','work','service delivery'],'Cancellations/delays/repair are attributed to shared conditions with valid rescheduling.','Advance a traveller past a meeting and leave the meeting pending forever.')
recipe('wildfire-smoke-and-access','crisis','Supported fire/smoke footprint reaches relevant terrain and assets',['residents','land managers','responders','employers'],['fuel/terrain','wind','exposure','evacuation capacity','duration'],['hazards','housing','health exposure','travel','response','finance'],'Distinct direct damage, smoke exposure and access effects through their appropriate models.','Treat all state residents as equally exposed or reuse a storm label with no fire mechanism.')
recipe('drought-and-supply-stress','crisis','Persistent supported water deficit pressures actual users',['utilities','farms/businesses','residents','authorities'],['storage','season','demand','alternatives','allocation rule'],['water','agriculture','jobs','prices','regulation','migration'],'Resource balance changes service/production with rule-bound responses.','One dry month universally destroys crops or directly adds the same GDP shock everywhere.')
recipe('service-failure-and-repair','crisis','A represented water/power/communications/transport component actually fails',['operator','users','repair staff','public officials'],['cause','redundancy','repair dependencies','funding','disclosure'],['infrastructure','work','health/services','procurement','oversight'],'Loss/stabilization/restoration followed by identified causes and possible reform.','A generic crisis card bypasses the condition of the actual service.')
recipe('public-health-capacity-pressure','crisis','A supported health episode or demand rise exceeds represented service capacity',['providers','workers','users','health authority'],['need','staffing','access','cost','communication','response'],['health','jobs','public budget','household','beliefs'],'Care availability and costs respond before separately modelled outcomes.','Invent named disease clinical rates or automatically force civil restrictions.')
recipe('fiscal-pressure-and-service-tradeoff','crisis','Real revenue/expenditure commitments create projected or actual fiscal pressure',['finance staff','executive','legislature','service users'],['reserves','borrowing power','timing','obligations','revenue base'],['accounts','budgets','services','work','legislation','news'],'Feasible adjustment, borrowing or delivery consequences under the government’s powers.','A deficit headline causes arbitrary default while cash/obligations are ignored.')
recipe('institutional-dispute','crisis','Actual actors disagree over authority, obligations or a consequential decision',['officeholders','bodies','review institution','affected groups'],['power','evidence','procedure','deadline','coalitions'],['government','courts/oversight','law','service continuity','news'],'Supported negotiation/review/decision changes authority or action; work elsewhere continues.','Disagreement automatically means violent unrest or whole-game deadlock.')
recipe('international-pressure-and-response','crisis','A supported cross-border dispute or incident has actors, interests and information',['governments','affected organizations','authorized officials'],['interests','commitments','resources','signals','exposure','response'],['international records','diplomacy','trade','macro','authority','news'],'Plausible proposals, de-escalation, escalation or unresolved continuation with actual effects.','Guaranteed war by year N or same fishing-rights sentence in every save.')
recipe('ordinary-improvement-and-new-opportunity','world-change','A real service/project/employer/relationship improvement opens possibilities',['participants','beneficiaries','new entrants'],['capacity','access','local needs','knowledge','resources'],['services','work','housing','private goals','relationships'],'People can pursue new feasible choices in good conditions too.','Only crisis or deprivation can generate content.')

# Versioned, provisional sampling proposal. Weights sum to 100 but are selection weights, not population percentages.
FAMILIES=[('Self-image',8),('Social approach',11),('Social manner',8),('Thinking and learning',11),('Work and follow-through',11),('Goals and advantage',9),('Concern and reciprocity',9),('Trust and integrity',6),('Rules and flexibility',5),('Conflict and repair',5),('Pacing and risk',5),('Emotional style',4),('Emotional outlook',4),('Attachment and closeness',4)]
assert sum(w for _,w in FAMILIES)==100
profile={'version':'depth1-salient-family-private-a','status':'authored-provisional-private-playtest-not-empirical','scope':'One or two salient adult descriptors; not the five latent dimensions; not official measured prevalence.','countWeights':{'1':1,'2':1},'sampling':'Weighted family draw for each slot, allowing repeat family; then distinct compatible supported descriptor. No duplicate descriptor and no family-size synonym weighting.','families':[{'family':f,'selectionWeight':w} for f,w in FAMILIES],'withinFamily':'Use explicit descriptor meaning and compatibility; extreme disruptive descriptors get separately labelled lower candidate weights, not demographic inference. Full per-descriptor weights remain owner-implementer calibration, not supplied as measured rates here.'}
# Isolated illustrative experiment; never imports game source.
world_rates=[]; allcounts=Counter(); count_distribution=Counter()
for seed in range(100):
 rng=random.Random(seed); c=Counter()
 for _ in range(1000):
  n=1+rng.randrange(2);count_distribution[n]+=1
  seen=set()
  for __ in range(n):
   pick=rng.choices(FAMILIES,weights=[x[1] for x in FAMILIES],k=1)[0]
   seen.add(pick[0])
  for family in seen:
   c[family]+=1;allcounts[family]+=1
 world_rates.append(c)
obs=[]
for f,w in FAMILIES:
 vals=sorted(c[f]/10 for c in world_rates)
 obs.append({'family':f,'selectionWeight':w,'artificialAdultsWithFamilyPercent':round(allcounts[f]/1000,3),'across100ArtificialWorlds5to95Percent':[round(vals[4],2),round(vals[94],2)]})
EXPERIMENT={'kind':'isolated-authored-sampling-experiment-not-game-or-human-data','worlds':100,'adultsPerWorld':1000,'seedRange':[0,99],'pythonRandom':'MT19937 via random.Random; not the game RNG; not reference outputs for its algorithm','countDistribution':dict(count_distribution),'familyObservations':obs}

RUBRIC=[
 ('contact','A greeting or routine acknowledgement',{},'Record contact and any temporary appraisal, not default standing warmth/trust points merely from repetition.'),
 ('commitment','Agreeing to a specific feasible request',{},'Create the commitment; anticipation can be a temporary appraisal, not fulfillment.'),
 ('support','Delivered useful voluntary help',{'warmth':[.4,1.2],'trust':[.3,1.0]},'Ground recipient interpretation in need, cost and consent; no automatic reciprocal duty.'),
 ('work','Demonstrated competent cooperation',{'respect':[.4,1.2],'trust':[.2,.7]},'Domain-specific reliance; competence does not guarantee affection.'),
 ('commitment','Kept a significant explicit promise',{'trust':[.5,1.5],'warmth':[0,.7]},'Evaluate the actual terms and capacity; same promise counted once.'),
 ('conflict','Ordinary honest disagreement',{},'May change appraisal or issue respect; not universally a strained relationship.'),
 ('contact','Respectful refusal without prior duty',{},'Record the response; disappointment may exist without standing penalty.'),
 ('conflict','Known contempt or humiliation',{'warmth':[-1.5,-.4],'tension':[.5,1.5]},'Witness/interpretation-specific, not every blunt response.'),
 ('commitment','Unexplained avoidable breach of meaningful commitment',{'trust':[-2,-.5],'tension':[.3,1.5]},'Causal alternatives/capacity matter; accident or unknowable obligation is not deliberate betrayal.'),
 ('exchange','Known deliberate deception or privacy breach',{'trust':[-3,-1],'tension':[.5,2]},'Undiscovered act does not reveal itself; lie differs from sincere mistake.'),
 ('conflict','Acknowledgement plus accepted concrete repair',{'tension':[-1.5,-.3],'trust':[0,.5]},'Reduced tension is not erased breach or instantly restored trust.'),
 ('care','Ongoing meaningful support under an accepted arrangement',{'warmth':[.5,1.5],'trust':[.3,1]},'Aggregate related daily work as one evolving episode rather than 365 independent bonuses.')
]
rubric={'status':'authored-provisional-private-comparison-rubric','unit':'relative evidence contribution to an actor-specific interpretation; not a psychometric score, gameplay delta API or closeness threshold','rules':['Ranges illustrate scale, not random draws to apply blindly.','0 means no assumed standing change, not absent interaction/memory.','Commitment is primarily an explicit relationship/obligation record, not a cumulative points bonus.','Deduplicate by canonical episode and relevant evidence; maintained is not automatically strengthened.','Allow dispositions/context to change appraisal without making consent or trust compulsory.','Do not sum all dimensions into one friendship bucket.'], 'rows':[dict(namespace=k,conduct=c,proposedContributionRanges=d,boundary=b) for k,c,d,b in RUBRIC]}

PENDING=[
 {'requestId':'political-violence-what-to-ask-the-owner','status':'owner-question-prepared','reason':'Player-as-initiator scope still needs the requested owner choice; no new violence-design survey.'},
 {'requestId':'federal-policy-vocabulary-pack','status':'extensive-input-not-completed-this-batch','reason':'Federal pack scope remains approved; this batch expands cross-system content specifications, not a sourced complete federal vocabulary.'},
 {'requestId':'puerto-rico-government-and-municipios','status':'factual-compilation-pending','reason':'Profile topology answer does not replace actual office/qualification/source rows.'},
 {'requestId':'regional-scene-place-ids','status':'prior-delivery-recovery-pending','reason':'Earlier asserted remaining-18 JSON was absent from verified package. No new ID-list completion claimed.'},
 {'requestId':'school-name-plausibility-by-state-and-era','status':'extensive-distribution-survey-parked','reason':'No new nationwide proportions/era compilation; not a blocker for substantive life/governing connections.'},
 {'requestId':'ethics-procedure-unread-detail-wy-id-ut','status':'narrow-procedural-research-parked','reason':'51-jurisdiction institution survey remains complete at its stated scope; these three details are not certified.'},
]

# Authored preference questions use the inspected loader schema; no fixed bill numbers/names or invented numeric defaults.
PROPOSITIONS=[
 ('income-base-breadth','fiscal.income-tax','Breadth of the income-tax base','Should more forms of income fall within the income-tax base?','tax-base-definition'),
 ('income-rate-progressivity','fiscal.income-tax','Income-tax progressivity','Should higher taxable-income bands face a steeper rate schedule?','tax-rate-schedule'),
 ('sales-tax-essential-exemptions','fiscal.sales-tax','Essential-goods exemptions','Should essential goods receive broader sales-tax exemptions?','tax-exemption'),
 ('property-tax-relief-targeting','fiscal.property-tax','Targeted property-tax relief','Should property-tax relief concentrate on households meeting need-based conditions?','tax-relief-eligibility'),
 ('service-fee-waivers','fiscal.fees-and-charges','Service-fee waivers','Should users meeting need-based conditions pay reduced fees for specified public services?','fee-eligibility'),
 ('reserve-use-for-service-continuity','fiscal.reserves','Reserves and service continuity','Should available reserves protect essential service delivery during a temporary revenue shortfall?','reserve-withdrawal-authority'),
 ('capital-borrowing','fiscal.debt-and-bonds','Borrowing for durable projects','Should eligible durable public projects be financed partly through borrowing rather than entirely through current revenue?','debt-authorization'),
 ('local-revenue-sharing','fiscal.revenue-sharing','Local revenue-sharing distribution','Should a larger share of state revenue-sharing support localities with higher measured service needs?','grant-allocation-rule'),
 ('public-contract-disclosure','government-operations.public-contracting','Public-contract disclosure','Should public contracts carry stronger disclosure of relevant ownership and conflicts?','reporting-duty'),
 ('public-hiring-access','government-operations.civil-service','Access to public employment','Should qualification rules accept relevant demonstrated experience as an alternative to specified credentials where the role permits it?','employment-eligibility'),
 ('agency-responsibility-transfer','government-operations.agency-organization','Agency responsibility','Should a specified public responsibility move to a different accountable agency?','authority-transfer'),
 ('school-funding-need-weight','education.school-funding','Need-weighted school funding','Should school funding give more weight to documented student and community needs?','allocation-formula'),
 ('teacher-compensation','education.teacher-workforce','Teacher compensation','Should additional available education funds prioritize teacher compensation and retention?','funded-work-terms'),
 ('college-need-based-aid','education.higher-education-tuition-and-aid','Need-based college aid','Should aid eligibility and award levels place greater weight on financial need?','benefit-eligibility-amount'),
 ('career-training-access','education.career-and-technical-education','Career-training access','Should public support make recognized job-related training more accessible to eligible workers?','training-capacity-support'),
 ('coverage-eligibility','health-human-services.medicaid','Public health-coverage eligibility','Should eligibility for the represented public health-coverage program be broadened within this government’s actual authority?','coverage-rule'),
 ('health-provider-capacity','health-human-services.hospitals-and-providers','Health-service capacity','Should available support prioritize adding provider capacity in underserved areas?','funded-service-capacity'),
 ('income-assistance-access','health-human-services.food-and-income-assistance','Income-assistance access','Should assistance rules reduce avoidable barriers for otherwise eligible applicants?','application-and-eligibility-rule'),
 ('housing-density-permission','housing-land-use.zoning','Residential density','Should more residential density be permitted in suitable existing developed areas?','land-use-permission'),
 ('housing-permit-process','housing-land-use.permitting','Housing permit process','Should qualifying housing projects receive a simpler permit process while retaining applicable safety requirements?','procedure-and-deadline-rule'),
 ('housing-subsidy-targeting','housing-land-use.housing-affordability','Housing support targeting','Should housing support give greater weight to the difference between local housing costs and household resources?','benefit-allocation'),
 ('transit-service-reach','transportation-infrastructure.transit','Transit service reach','Should available transit funding extend useful service to currently underserved users?','funded-route-and-capacity'),
 ('water-reliability-investment','transportation-infrastructure.water-and-sewer','Water-system reliability','Should available capital funding prioritize renewal of water-system components with higher service-loss risk?','asset-maintenance-and-resilience'),
 ('emergency-response-capacity','justice-public-safety.emergency-response','Emergency-response capacity','Should additional response resources prioritize areas with a larger gap between demand and available service?','funded-staff-and-equipment')
]
packname='ocd-authored-policy-questions'
pack={'pack':packname,'provenance':{'kind':'authored-fiction','note':'Director-authored general policy preference questions for the fictional game. Referenced issue vocabulary is separately sourced. These rows are not real enacted statutes, executable effects, or blanket approval of every concrete bill variant. Bind actual proposition alternatives, target, authority and terms before evaluating a specific measure.'},'propositions':[{'key':k,'issue':'us-state-and-local:'+issue,'name':name,'question':q,'tags':['general-policy-direction','requires-bound-terms-for-specific-measure']} for k,issue,name,q,op in PROPOSITIONS],'subjects':[{'key':k+'-knowledge','name':'Understanding '+name.lower(),'description':'Knowledge relevant to this proposed policy direction; a subject definition does not give any person that knowledge.','scope':'proposition','about':packname+':'+k} for k,issue,name,q,op in PROPOSITIONS]}
(ROOT/'authored-policy-questions.candidate.json').write_text(json.dumps(pack,indent=2),encoding='utf-8')
(ROOT/'policy-question-binding-notes.json').write_text(json.dumps({'status':'candidate-content-not-loaded-or-executed','sourceHead':HEAD,'requiredBindings':['actual jurisdiction and authorized actor','selected proposition alternative/provision revision','affected target/population','quantity/rate and units where applicable','funding/resource source','conditions/exemptions','implementation owner','effective and expiry/transition dates'],'rows':[{'questionKey':packname+':'+k,'inspectedIssueKey':'us-state-and-local:'+issue,'effectOperationToBind':op} for k,issue,name,q,op in PROPOSITIONS],'rules':['The preference question alone is never a complete bill or executable effect.','Stable definitions can be reused; concrete selected terms must be represented in the existing alternative/provision context.','Do not apply support for one amount or group automatically to another proposal.','Preserve current useful issue IDs; no third taxonomy or duplicate source pack.','File follows the inspected PolicyPack row shape but was not passed through the actual repository loader in this environment.']},indent=2),encoding='utf-8')

(ROOT/'source-register.json').write_text(json.dumps(SOURCES,indent=2),encoding='utf-8')
(ROOT/'answers.json').write_text(json.dumps({'version':'depth1-receiving-v1','sourceHead':HEAD,'evidenceStatus':'read-source-and-research-not-production-test','answers':ANS,'ownerQuestion':QUESTION,'remaining':PENDING},indent=2),encoding='utf-8')
(ROOT/'depth-content-catalogue.json').write_text(json.dumps({'version':'depth1-content-specification-v1','status':'design-specification-for-existing-engine-adapters-not-a-loadable-game-pack','notALimit':'This finite receiving batch is not a permanent content ceiling or scripted event deck. Expand through the same meaningful operations.','recipes':RECIPES},indent=2),encoding='utf-8')
(ROOT/'trait-family-private-profile.json').write_text(json.dumps(profile,indent=2),encoding='utf-8')
(ROOT/'trait-family-experiment.json').write_text(json.dumps(EXPERIMENT,indent=2),encoding='utf-8')
(ROOT/'relationship-conduct-rubric.json').write_text(json.dumps(rubric,indent=2),encoding='utf-8')

# A readable current receiving document; no external source quotations copied.
lines=['# DEPTH1 — People, work, legislation and crises that affect each other','',
'Owner-approved consolidation • September 22, 2026','',
'## Status and authority','',
'The six scope choices are recorded in the existing Decision Register and PROJECT START. The former per-number approval paragraph in LIVE QUESTIONS was replaced in place: labelled, adjustable private-playtest calibration is now allowed inside approved behavior. Friendships and career changes are the immediate personal-life priorities; the same world must support an office term. Compact missing models are authorized, but major new creative choices still return to the owner. Monitoring remains off.','',
'This batch supplies research-backed distinctions, current-source findings and authored game specifications. It does not claim source edits, merged work, a compiled national dataset, a running Claude worker, artwork acceptance or installed-game tests. Existing full cloud owners keep their current registered workspace and branch; this document creates no new worker or competing engine.','',
'## Source findings that change the receiving work','',
'- The current relationship summary adds 1/2/3 per interaction and calls a pair close at three. Maintained interactions are ordinarily positive; conflict-prefixed interactions are negative. The close-person event query consumes that summary. [code-relationships]','- The five-trait pack explicitly scopes its traits to life:ordinary. Widening relevant consumers needs an intentional scope/adapter connection, not another set of personal identities. The old permanent perMove penalty has already been replaced in this inspected pack; do not repeat that repair. [code-trait-pack]','- Belief formation already has a meaningful no-opinion default and requires source-supported factors. Scheduling an empty call is not enough; connect the person\'s reasons. [code-beliefs]','- HazardFamily remains flood | severe-storm, and the automatic source map handles flood, flash-flood and thunderstorm-wind. The existing historical sampler and response machinery are useful; expansion needs distinct supported hazard effects and contexts, not another renamed storm card. [code-hazards, code-crisis-types]','',
'## Candidate policy-question content','', 'authored-policy-questions.candidate.json supplies 24 actual proposition rows and 24 related knowledge-subject rows in the inspected PolicyPack shape, referencing existing sourced issue IDs. They state general policy directions, not named Acts, quantities or a predetermined outcome. Their authored-fiction provenance is explicit. policy-question-binding-notes.json names the missing specific-measure bindings and effects. These candidates are not loader-tested or installed; the receiver must verify them through the actual loader and preserve the existing live catalogue. Definitions do not confer knowledge on any person.','', '## Queue answers','']
for a in ANS:
 lines += [f"### {a['requestId']} — {a['title']}",'',f"**Status:** {a['status']}. **Receiver:** {a['receivingOwner']}.",'',a['answer'],'',f"**Acceptance requested, not executed:** {a['acceptance']}",'',f"**Basis:** {', '.join('['+s+']' for s in a['sourceIds'])}",'']
lines += ['## Content expansion: actual mechanisms, not a pile of fixed stories','',
'`depth-content-catalogue.json` contains '+str(len(RECIPES))+' composable receiving specifications. These are not new executable engine schemas and are not ready-to-import production packs. Each names a real trigger, participant roles, variation axes, systems that must exchange facts, a required consequence and a forbidden shortcut. The existing owners map them onto current typed producers/actions/records/consumers, extending a compact missing model only where necessary. Existing issue keys are provided only where directly checked in the current pack.','',
'Keep original causal episode and action identities across all consumers. A municipal budget decision, a water interruption, a lost work shift and a later conversation may be linked consequences of one event—not four independent random draws or four charges for the same damage. A scenario is a viewpoint and choice opportunity over these facts; the scenario log links to canonical history rather than owning a parallel truth.','',
'For a proposed law, use the same structured operations for starting rules, new proposals, amendments and repeal. Bind institution/power, target/affected group, quantity/rate, funding source, conditions/exemptions, implementation actor and effective period. Text, negotiation, private view, public statement and actual effects must all refer to the correct version/selected terms. General support for a proposition does not authorize every possible amount or beneficiary.','',
'### Mechanism catalogue','', '| Group | Mechanism | Required consequence |','|---|---|---|']
for r in RECIPES: lines.append(f"| {r['group']} | {r['key']} | {r['requiredResult']} |")
lines += ['', '### Compact service model to connect first','',
'Use represented demand/eligible users, available staffed capacity, operating/capital resources, access/queue, delivered service and the responsible institution. Keep delivered service distinct from an output metric or an appropriation. A health-access model can initially represent coverage, affordability and staffed availability without claiming clinical prognosis; a housing model distinguishes permission, funded construction, completed homes and household access. A utility model distinguishes equipment condition, service capacity, network dependencies and restoration. These are linked supporting states, not rival engines.','',
'BLS differentiates an available vacancy, a payroll hire, internal promotion and different separations. That supports keeping those career events separate. Its job-openings definition uses a possible start within thirty days for a statistical measure; this is not a universal rule that a game offer lasts thirty days. [bls-jolts]','',
'EPA describes how energy, water and healthcare systems depend on one another and how lifelines distinguish operational root causes. The game transfer is to represent conditional propagation and useful interventions: backup power or a repaired supply can interrupt a chain. A flood does not have to trigger every downstream crisis. [epa-lifelines, epa-dependencies]','',
'NOAA/NWS document multiple weather families and uneven historical coverage/reporting. Add distinct hazard content against verified source families, local exposure, intensity/duration, vulnerability and response; retain the current catalogue-window limitations. Counts of reports or counties touched are not direct measurements of physical intensity. Heat, winter disruption, fire/smoke and drought need their own effect semantics rather than the flood damage formula. No new nationwide frequency table or condition-specific medical calibration is claimed. [noaa-catalog, nws-reports]','',
'### A connected example for testing, not a scripted production story','',
'A worker and colleague become familiar through an actual project. A damaged service interrupts their employer. The worker\'s schedule and household income change; their friend may offer useful information or an introduction depending on knowledge, willingness and availability. Officials consider repair funding, competing needs and service alternatives. The measure\'s terms and implementation change what is restored, when and for whom. The two people can interpret the same response differently, preserve or revise a view, and make different career decisions. Nothing guarantees friendship, job loss, a particular bill, a vote or political conversion. Controls with no interruption must still offer normal work/friendship development.','',
'## Explicit private calibration','',
'The family profile is authored for a first comparison, NOT measured human prevalence. It uses a 50/50 one-or-two salient adult descriptor count and weighted family selection that allows two compatible traits in one family. It does not specify the full latent psyche or a permanent trait cap. Per-descriptor eligibility/compatibility and any extreme-trait downweight remain explicit implementer work, not inferred demographic truths.','',
'| Research family | Selection weight | Artificial adults with this family (%) | 5th–95th world range (%) |','|---|---:|---:|---:|']
for o in obs: lines.append(f"| {o['family']} | {o['selectionWeight']} | {o['artificialAdultsWithFamilyPercent']} | {o['across100ArtificialWorlds5to95Percent'][0]}–{o['across100ArtificialWorlds5to95Percent'][1]} |")
lines += ['',
'These outputs come from the included isolated Python experiment (100 artificial worlds × 1,000 adults). They are neither real-population estimates nor runs of Our Civic Duty. The actual game RNG may produce different samples with the same target distribution. Families with more catalogue entries do not gain selection weight simply from list length.','',
'`relationship-conduct-rubric.json` supplies relative direction/magnitude proposals on separate interpretations, not a one-sum closeness rule. The trait-change answer defines an A/B private comparison against actual current pack values, rather than recertifying those values as research. For each enabled configuration, show a compact assumption label in development information and the report, retain configuration identity with saved-world behavior and do not silently mutate an existing life\'s model on reload.','',
'## Playtest receiving order','',
'1. A friendship and a career change over a meaningful ordinary interval through the actual creator/player route, with named NPCs continuing offscreen. No injected success story or proofreading milestone.','2. A normal office term inherits live work and can enact a supported measure whose effects reach those same people/services; an election transition cannot leave the winning character with only an employment label.','3. Matched initial states with/without a supported disruption and with alternative responses: trace one origin, each effect, appropriate discovery and continuation. Include a quiet/good-condition control.','4. Same source/configuration/seed across daily versus larger time steps and Save/Continue; rerenders, extra wording and extra portrait detail must not add incidents, ballots, payments or evidence.','5. A few representative cross-system pairs are the first proof, not a permanent content cap. Expand coverage by independently supported mechanisms, contextual alternatives and branch outcomes—not just row counts.','',
'## Remaining scope and data','']
for p in PENDING: lines += [f"- **{p['requestId']} — {p['status']}:** {p['reason']}"]
lines += ['',f"**Owner question:** {QUESTION['question']}",QUESTION['boundary'],'',
'Names have method answers but no new annual-count compilation. Family life has a partial continuity answer; detailed courtship/parenting is not declared complete. Source-specific new health/disease or major legal-power assumptions need their appropriate factual or creative review.','',
'## Source register','']
for s in SOURCES: lines += [f"- **[{s['id']}]** {s['kind']}: {s.get('url',s.get('path'))}. {s['use']}"]
lines += ['','## Verification boundary','',
'Code was read through the GitHub connector at the recorded head. Direct raw-GitHub download in this container failed DNS, so no checkout/production build or game test was executed. The local scripts test only supplied research structure, artificial sampling and illustrative conservation arithmetic. Tool write/delivery receipts are recorded separately in the live Drive exchange. No active worker acknowledgment is inferred from publication.','']
(ROOT/'DEPTH1-RESEARCH-AND-ANSWERS.md').write_text('\n'.join(lines),encoding='utf-8')
print(json.dumps({'answers':len(ANS),'recipes':len(RECIPES),'families':len(FAMILIES),'sources':len(SOURCES),'markdown_bytes':(ROOT/'DEPTH1-RESEARCH-AND-ANSWERS.md').stat().st_size},indent=2))
