import { describe, expect, it } from "vitest";

import staging from "../../art/backdrops/staging.json" with { type: "json" };
import { makeIsoDate } from "../simulation/dates";
import { createStableId } from "../simulation/ids";
import { isSeatedPose } from "./appearance-engine/pack";
import { sceneActivity } from "./appearance-engine/pose-chooser";
import { engineRecipeFor } from "./appearance-engine/recipe";
import { PEOPLE_PACK } from "./appearance-engine/runtime";
import {
  drawnAtSpot,
  spotPose,
  spotViews,
  type StagingSpot,
} from "./backdrop-people";
import { placeDressCode } from "./dress-code";

/**
 * PEOPLE STANDING AND POSING IN EVERY PAINTED PLACE.
 *
 * Every spot staging.json marks in every place picture is checked: a person
 * generated by the people engine, posed by the pose chooser for what a
 * person there does (pose-by-activity.json), can be drawn there in a view
 * the spot allows (spotViews). The one spot nobody can be drawn at is a seat
 * facing away: the pack has no seated person painted from behind.
 */

const PLACES = Object.entries(
  (staging as { places: Record<string, { spots: StagingSpot[] }> }).places,
);
/** People of each face age band (recipe.ts faceBand), both presentations. */
const SEEDS = 12;
const AGES = [33, 55, 72] as const;

function someoneDrawnAt(place: string, spot: StagingSpot): boolean {
  for (let index = 0; index < SEEDS; index++) {
    const seed = `spot-fill:${place}:${spot.id}:${index}`;
    const activity = sceneActivity({
      personId: seed,
      speakerId: null,
      anchorType: spot.group ?? spot.pose ?? "stand",
      seated: spot.pose === "sit",
      facing: spot.facing,
    });
    for (const view of spotViews(spot)) {
      const recipe = engineRecipeFor(
        {
          id: createStableId("person", seed),
          birthDate: makeIsoDate(`${2000 - AGES[index % AGES.length]!}-01-01`),
        },
        "2000-06-01",
        PEOPLE_PACK,
        {
          wear: placeDressCode(place).dress,
          pose: spotPose(spot, activity, seed, { view }),
          view,
        },
      );
      if (recipe && drawnAtSpot(spot, recipe, view)) return true;
    }
  }
  return false;
}

describe(
  "the people standing in every painted place",
  { timeout: 120_000 },
  () => {
    it("can put someone at every spot but a seat facing away", () => {
      const empty: string[] = [];
      let spots = 0;
      for (const [place, stage] of PLACES)
        for (const spot of stage.spots) {
          // A lectern is the scene's speaker's, posed at the podium; a seat
          // facing away waits for a seated person painted from behind.
          if (spot.pose === "podium") continue;
          if (spot.pose === "sit" && spot.facing === "away") continue;
          spots++;
          if (!someoneDrawnAt(place, spot))
            empty.push(`${spot.id} ${spot.pose ?? "stand"} ${spot.facing}`);
        }
      expect(spots).toBeGreaterThan(1000);
      expect(empty).toEqual([]);
    });

    it("stands a person at a place to lean, posed the way a lean is drawn", () => {
      const leans = PLACES.flatMap(([place, stage]) =>
        stage.spots
          .filter((spot) => spot.pose === "lean")
          .map((spot) => [place, spot] as const),
      );
      expect(leans.length).toBeGreaterThan(0);
      for (const [place, spot] of leans)
        expect(someoneDrawnAt(place, spot), `${spot.id}`).toBe(true);
    });

    it("faces the room at a turned spot until its turned painting has a face", () => {
      const turned: StagingSpot = { x: 50, y: 80, facing: "left" };
      expect(spotViews(turned)).toEqual(["three-quarter", "front"]);
      expect(spotViews({ ...turned, facing: "right" })).toEqual([
        "three-quarter",
        "front",
      ]);
      expect(spotViews({ ...turned, facing: "away" })).toEqual(["back"]);
      expect(spotViews({ ...turned, facing: "away" }, true)).toEqual(["front"]);
      expect(spotViews({ ...turned, facing: "viewer" })).toEqual(["front"]);
    });

    it("never seats a standing figure or stands a seated one", () => {
      for (const [place, stage] of PLACES)
        for (const spot of stage.spots.filter((at) => at.pose === "sit")) {
          const seed = `seat:${place}:${spot.id}`;
          for (const view of spotViews(spot)) {
            const recipe = engineRecipeFor(
              { id: createStableId("person", seed), birthDate: "1967-01-01" },
              "2000-06-01",
              PEOPLE_PACK,
              { wear: placeDressCode(place).dress, pose: "arms-folded", view },
            );
            if (recipe) expect(drawnAtSpot(spot, recipe, view)).toBeNull();
            const seated = recipe && { ...recipe, pose: "seated" as const };
            const drawn = seated ? drawnAtSpot(spot, seated, view) : null;
            if (drawn) expect(isSeatedPose(drawn.pose)).toBe(true);
          }
        }
    });
  },
);
