/** Shared wording for UX39/WORLD39. Consumers retain their existing actions,
 * authority checks and saving behavior. These strings confer no capability. */
export const TEXT39_UI_COPY = {
  newLife: "New life",
  continueLife: "Continue",
  save: "Save",
  saving: "Saving…",
  saved: "Saved",
  unsaved: "Unsaved changes",
  randomizeName: "Randomize name",
  randomizeAll: "Randomize all",
  origin: "Where are you from?",
  appearance: "Appearance",
  begin: "Begin",
  questionnaireSkip: "Discover through play",
  questionnaireShort: "Answer a few questions",
  questionnaireDeep: "Answer more questions",
  questionnaireStartNow: "Start playing",
  questionnaireNote:
    "These are imagined situations. You can stop answering and start playing at any time.",
  calendar: "Calendar",
  week: "Week",
  month: "Month",
  history: "History",
  dateOrder: "Date format",
  monthFirst: "Month / day / year",
  dayFirst: "Day / month / year",
  plan: "Edit plan",
  perform: "Do this now",
  travel: "Travel",
  noDestination: "No destination is available from here yet.",
  noIntroduction: "You don't know anyone who can introduce you yet.",
  noPublicNews: "There are no public updates to read yet.",
  noBiography: "Your life story will begin with what you do next.",
  unavailableOfficeAction:
    "You don't currently hold an office that can take this action.",
  noSupportedOffice: "This office doesn't have playable actions yet.",
  motion: "Background motion",
  motionHelp:
    "Animate supported backgrounds. Your reduced-motion preference takes priority.",
  build: "About this version",
} as const;
