/** GENERATED by scripts/source/export-constitutional-process.ts. */
export const CONSTITUTIONAL_EVIDENCE = {
  "us-process": {
    url: "https://www.archives.gov/federal-register/constitution",
    sha256: "348aaf850906794914f97a7c2c5c7cd3faa510ccfda7051d67bb462e17a6322f",
    observedOn: "2026-09-13",
  },
  "us-proposal-denominator": {
    url: "https://www.law.cornell.edu/supremecourt/text/253/350",
    sha256: "34860ffcfecc071387bae537b8d43f0c2b5b46bb118fc668ab364c878793c798",
    observedOn: "2026-09-13",
  },
  "ca-constitution-iv": {
    url: "https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CONS&article=IV",
    sha256: "0f731aa7ee4d9903a62c8c53c309df55519af67d6ce28142d50326eac36da8fa",
    observedOn: "2026-09-13",
  },
  "us-constitution": {
    url: "https://www.archives.gov/federal-register/constitution/article-v.html",
    sha256: "4dfeba35d19c5235c5788c9d0ea38d453e17ff2924b1578561941a9ef6d8fa4c",
    observedOn: "2026-09-13",
  },
  "ca-constitution-xviii": {
    url: "https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?lawCode=CONS&article=XVIII",
    sha256: "fe199d9ecb9fff8fc50f45dd0c90831d17d93cb8e1228a27c98c66bcc0a71d42",
    observedOn: "2026-09-13",
  },
  "carson-charter": {
    url: "https://www.leg.state.nv.us/CityCharters/CtyCCCC.html",
    sha256: "8a26e351cc91505eca8a4eb5d4659a14b27d4edb06e214fd66cd1dd2cf8e84ad",
    observedOn: "2026-09-13",
  },
  "nv-effective": {
    url: "https://www.leg.state.nv.us/NRS/NRS-218D.html",
    sha256: "a256f44ef8ac98ee20ac28d1cac752a002493c1ce86219cfef957512c354891b",
    observedOn: "2026-09-13",
  },
  "us-quorum": {
    url: "https://www.archives.gov/founding-docs/constitution-transcript",
    sha256: "b4a9993a71ff99a0e91a6064007b04d6cafbc2a4c9935046ce1c6f5fd6657cb2",
    observedOn: "2026-09-13",
  },
} as const;
