// Generated by scripts/law-consequence-modules/generate-manifest.mjs. Do not edit by hand.
import type { AnyLawConsequenceKindRegistration } from "./law-consequence-types";
import type { PublicProgramCapacityOutturnReceiverRegistration } from "./public-program-capacity-outturn";
import * as lawConsequenceLw08DevelopmentIncentiveCapRegistrations from "./law-consequences/modules/lw08-development-incentive-cap";

interface GeneratedLawConsequenceModule {
  readonly registrations: readonly AnyLawConsequenceKindRegistration[];
  readonly publicProgramCapacityOutturnReceivers?: readonly PublicProgramCapacityOutturnReceiverRegistration[];
}

const GENERATED_LAW_CONSEQUENCE_MODULES: readonly GeneratedLawConsequenceModule[] =
  [
  lawConsequenceLw08DevelopmentIncentiveCapRegistrations,
];

export const LAW_CONSEQUENCE_MODULE_KEYS = [
  "lw08-development-incentive-cap",
] as const;

export const LAW_CONSEQUENCE_MODULE_REGISTRATIONS: readonly AnyLawConsequenceKindRegistration[] =
  Object.freeze(
    GENERATED_LAW_CONSEQUENCE_MODULES.flatMap((module) => module.registrations),
  );

export const PUBLIC_PROGRAM_CAPACITY_OUTTURN_RECEIVERS: readonly PublicProgramCapacityOutturnReceiverRegistration[] =
  Object.freeze(
    GENERATED_LAW_CONSEQUENCE_MODULES.flatMap(
      (module) => module.publicProgramCapacityOutturnReceivers ?? [],
    ),
  );
