// Generated by scripts/law-consequence-modules/generate-manifest.mjs. Do not edit by hand.
import type { AnyLawConsequenceKindRegistration } from "./law-consequence-types";
import type { PublicProgramCapacityOutturnReceiverRegistration } from "./public-program-capacity-outturn";
import * as lawConsequenceElectionLocalLandingsRegistrations from "./law-consequences/modules/election-local-landings";
import * as lawConsequenceElectionStateLandingsRegistrations from "./law-consequences/modules/election-state-landings";
import * as lawConsequenceElectionWardLandingsRegistrations from "./law-consequences/modules/election-ward-landings";
import * as lawConsequenceGovernmentOperationsRegistrations from "./law-consequences/modules/government-operations";
import * as lawConsequenceJusticePretrialLandingsRegistrations from "./law-consequences/modules/justice-pretrial-landings";
import * as lawConsequenceJusticeSentencingLandingsRegistrations from "./law-consequences/modules/justice-sentencing-landings";
import * as lawConsequenceLw08LibraryMaterialsRegistrations from "./law-consequences/modules/lw08-library-materials";

interface GeneratedLawConsequenceModule {
  readonly registrations: readonly AnyLawConsequenceKindRegistration[];
  readonly publicProgramCapacityOutturnReceivers?: readonly PublicProgramCapacityOutturnReceiverRegistration[];
}

const GENERATED_LAW_CONSEQUENCE_MODULES: readonly GeneratedLawConsequenceModule[] =
  [
    lawConsequenceElectionLocalLandingsRegistrations,
    lawConsequenceElectionStateLandingsRegistrations,
    lawConsequenceElectionWardLandingsRegistrations,
    lawConsequenceGovernmentOperationsRegistrations,
    lawConsequenceJusticePretrialLandingsRegistrations,
    lawConsequenceJusticeSentencingLandingsRegistrations,
    lawConsequenceLw08LibraryMaterialsRegistrations,
  ];

export const LAW_CONSEQUENCE_MODULE_KEYS = [
  "election-local-landings",
  "election-state-landings",
  "election-ward-landings",
  "government-operations",
  "justice-pretrial-landings",
  "justice-sentencing-landings",
  "lw08-library-materials",
] as const;

export const LAW_CONSEQUENCE_MODULE_REGISTRATIONS: readonly AnyLawConsequenceKindRegistration[] =
  Object.freeze(
    GENERATED_LAW_CONSEQUENCE_MODULES.flatMap((module) => module.registrations),
  );

export const PUBLIC_PROGRAM_CAPACITY_OUTTURN_RECEIVERS: readonly PublicProgramCapacityOutturnReceiverRegistration[] =
  Object.freeze(
    GENERATED_LAW_CONSEQUENCE_MODULES.flatMap(
      (module) => module.publicProgramCapacityOutturnReceivers ?? [],
    ),
  );
