/** Retained BLS Consumer Expenditure category means and published sampling errors.
 * Native XLSX cells from the locked regional corpus, not observed household bills.
 */
export const LIVING_COSTS_CATEGORY_SOURCES = {
  "region-of-residence": {
    length: 23675,
    localPath:
      "data/source/consumer-expenditure/raw/cu-region-1-year-average-2024.xlsx",
    mediaType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    sha256: "9d7cbb5437dd975b918d11c454e74c626e9809e1418887ae05da00a7b35c0843",
    sheet: "Table 1800",
    url: "https://www.bls.gov/cex/tables/calendar-year/mean-item-share-average-standard-error/cu-region-1-year-average-2024.xlsx",
    vintage: "calendar year 2024",
  },
  "consumer-unit-size": {
    length: 28642,
    localPath: "data/source/consumer-expenditure/raw/cu-size-2024.xlsx",
    mediaType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    sha256: "6378f4aa2e2f54bfe758c7604aeb366e8cc38d0d626a583bd77ba6aee87d28f9",
    sheet: "Table 1400",
    url: "https://www.bls.gov/cex/tables/calendar-year/mean-item-share-average-standard-error/cu-size-2024.xlsx",
    vintage: "calendar year 2024",
  },
} as const;

export const LIVING_COSTS_CATEGORY_DATA = {
  food: {
    label: "Food",
    regions: {
      national: {
        annualMeanUsd: 10169,
        standardErrorUsd: 158.96,
        relativeStandardErrorPercent: 1.56,
        column: "B",
        meanSourceRow: 56,
        standardErrorSourceRow: 58,
        relativeStandardErrorSourceRow: 59,
      },
      northeast: {
        annualMeanUsd: 11372,
        standardErrorUsd: 219.46,
        relativeStandardErrorPercent: 1.93,
        column: "C",
        meanSourceRow: 56,
        standardErrorSourceRow: 58,
        relativeStandardErrorSourceRow: 59,
      },
      midwest: {
        annualMeanUsd: 9677,
        standardErrorUsd: 258.04,
        relativeStandardErrorPercent: 2.67,
        column: "D",
        meanSourceRow: 56,
        standardErrorSourceRow: 58,
        relativeStandardErrorSourceRow: 59,
      },
      south: {
        annualMeanUsd: 9003,
        standardErrorUsd: 338.99,
        relativeStandardErrorPercent: 3.77,
        column: "E",
        meanSourceRow: 56,
        standardErrorSourceRow: 58,
        relativeStandardErrorSourceRow: 59,
      },
      west: {
        annualMeanUsd: 11746,
        standardErrorUsd: 412.59,
        relativeStandardErrorPercent: 3.51,
        column: "F",
        meanSourceRow: 56,
        standardErrorSourceRow: 58,
        relativeStandardErrorSourceRow: 59,
      },
    },
    sizes: {
      "1": {
        annualMeanUsd: 5644,
        standardErrorUsd: 137.99,
        relativeStandardErrorPercent: 2.44,
        column: "C",
        meanSourceRow: 57,
        standardErrorSourceRow: 59,
        relativeStandardErrorSourceRow: 60,
      },
      "2": {
        annualMeanUsd: 10158,
        standardErrorUsd: 250.18,
        relativeStandardErrorPercent: 2.46,
        column: "E",
        meanSourceRow: 57,
        standardErrorSourceRow: 59,
        relativeStandardErrorSourceRow: 60,
      },
      "3": {
        annualMeanUsd: 12205,
        standardErrorUsd: 338.21,
        relativeStandardErrorPercent: 2.77,
        column: "F",
        meanSourceRow: 57,
        standardErrorSourceRow: 59,
        relativeStandardErrorSourceRow: 60,
      },
      "4": {
        annualMeanUsd: 14543,
        standardErrorUsd: 496.92,
        relativeStandardErrorPercent: 3.42,
        column: "G",
        meanSourceRow: 57,
        standardErrorSourceRow: 59,
        relativeStandardErrorSourceRow: 60,
      },
      "5plus": {
        annualMeanUsd: 15605,
        standardErrorUsd: 638.9,
        relativeStandardErrorPercent: 4.09,
        column: "H",
        meanSourceRow: 57,
        standardErrorSourceRow: 59,
        relativeStandardErrorSourceRow: 60,
      },
    },
  },
  apparelAndServices: {
    label: "Apparel and services",
    regions: {
      national: {
        annualMeanUsd: 2001,
        standardErrorUsd: 65.72,
        relativeStandardErrorPercent: 3.28,
        column: "B",
        meanSourceRow: 344,
        standardErrorSourceRow: 346,
        relativeStandardErrorSourceRow: 347,
      },
      northeast: {
        annualMeanUsd: 2420,
        standardErrorUsd: 223.58,
        relativeStandardErrorPercent: 9.24,
        column: "C",
        meanSourceRow: 344,
        standardErrorSourceRow: 346,
        relativeStandardErrorSourceRow: 347,
      },
      midwest: {
        annualMeanUsd: 1962,
        standardErrorUsd: 113.6,
        relativeStandardErrorPercent: 5.79,
        column: "D",
        meanSourceRow: 344,
        standardErrorSourceRow: 346,
        relativeStandardErrorSourceRow: 347,
      },
      south: {
        annualMeanUsd: 1759,
        standardErrorUsd: 109.92,
        relativeStandardErrorPercent: 6.25,
        column: "E",
        meanSourceRow: 344,
        standardErrorSourceRow: 346,
        relativeStandardErrorSourceRow: 347,
      },
      west: {
        annualMeanUsd: 2137,
        standardErrorUsd: 106.78,
        relativeStandardErrorPercent: 5,
        column: "F",
        meanSourceRow: 344,
        standardErrorSourceRow: 346,
        relativeStandardErrorSourceRow: 347,
      },
    },
    sizes: {
      "1": {
        annualMeanUsd: 1113,
        standardErrorUsd: 83.06,
        relativeStandardErrorPercent: 7.46,
        column: "C",
        meanSourceRow: 345,
        standardErrorSourceRow: 347,
        relativeStandardErrorSourceRow: 348,
      },
      "2": {
        annualMeanUsd: 1994,
        standardErrorUsd: 112.07,
        relativeStandardErrorPercent: 5.62,
        column: "E",
        meanSourceRow: 345,
        standardErrorSourceRow: 347,
        relativeStandardErrorSourceRow: 348,
      },
      "3": {
        annualMeanUsd: 2404,
        standardErrorUsd: 192.81,
        relativeStandardErrorPercent: 8.02,
        column: "F",
        meanSourceRow: 345,
        standardErrorSourceRow: 347,
        relativeStandardErrorSourceRow: 348,
      },
      "4": {
        annualMeanUsd: 2653,
        standardErrorUsd: 182.63,
        relativeStandardErrorPercent: 6.88,
        column: "G",
        meanSourceRow: 345,
        standardErrorSourceRow: 347,
        relativeStandardErrorSourceRow: 348,
      },
      "5plus": {
        annualMeanUsd: 3358,
        standardErrorUsd: 307.99,
        relativeStandardErrorPercent: 9.17,
        column: "H",
        meanSourceRow: 345,
        standardErrorSourceRow: 347,
        relativeStandardErrorSourceRow: 348,
      },
    },
  },
  miscellaneous: {
    label: "Miscellaneous",
    regions: {
      national: {
        annualMeanUsd: 1218,
        standardErrorUsd: 77.63,
        relativeStandardErrorPercent: 6.37,
        column: "B",
        meanSourceRow: 542,
        standardErrorSourceRow: 544,
        relativeStandardErrorSourceRow: 545,
      },
      northeast: {
        annualMeanUsd: 1069,
        standardErrorUsd: 85.94,
        relativeStandardErrorPercent: 8.04,
        column: "C",
        meanSourceRow: 542,
        standardErrorSourceRow: 544,
        relativeStandardErrorSourceRow: 545,
      },
      midwest: {
        annualMeanUsd: 1142,
        standardErrorUsd: 123.94,
        relativeStandardErrorPercent: 10.85,
        column: "D",
        meanSourceRow: 542,
        standardErrorSourceRow: 544,
        relativeStandardErrorSourceRow: 545,
      },
      south: {
        annualMeanUsd: 1029,
        standardErrorUsd: 99.76,
        relativeStandardErrorPercent: 9.69,
        column: "E",
        meanSourceRow: 542,
        standardErrorSourceRow: 544,
        relativeStandardErrorSourceRow: 545,
      },
      west: {
        annualMeanUsd: 1744,
        standardErrorUsd: 267.66,
        relativeStandardErrorPercent: 15.35,
        column: "F",
        meanSourceRow: 542,
        standardErrorSourceRow: 544,
        relativeStandardErrorSourceRow: 545,
      },
    },
    sizes: {
      "1": {
        annualMeanUsd: 1096,
        standardErrorUsd: 182.84,
        relativeStandardErrorPercent: 16.69,
        column: "C",
        meanSourceRow: 543,
        standardErrorSourceRow: 545,
        relativeStandardErrorSourceRow: 546,
      },
      "2": {
        annualMeanUsd: 1115,
        standardErrorUsd: 84.23,
        relativeStandardErrorPercent: 7.55,
        column: "E",
        meanSourceRow: 543,
        standardErrorSourceRow: 545,
        relativeStandardErrorSourceRow: 546,
      },
      "3": {
        annualMeanUsd: 1360,
        standardErrorUsd: 110.72,
        relativeStandardErrorPercent: 8.14,
        column: "F",
        meanSourceRow: 543,
        standardErrorSourceRow: 545,
        relativeStandardErrorSourceRow: 546,
      },
      "4": {
        annualMeanUsd: 1546,
        standardErrorUsd: 234.26,
        relativeStandardErrorPercent: 15.15,
        column: "G",
        meanSourceRow: 543,
        standardErrorSourceRow: 545,
        relativeStandardErrorSourceRow: 546,
      },
      "5plus": {
        annualMeanUsd: 1319,
        standardErrorUsd: 157.64,
        relativeStandardErrorPercent: 11.95,
        column: "H",
        meanSourceRow: 543,
        standardErrorSourceRow: 545,
        relativeStandardErrorSourceRow: 546,
      },
    },
  },
  gasoline: {
    label: "Gasoline",
    regions: {
      national: {
        annualMeanUsd: 2411,
        standardErrorUsd: 34.35,
        relativeStandardErrorPercent: 1.43,
        column: "B",
        meanSourceRow: 420,
        standardErrorSourceRow: 422,
        relativeStandardErrorSourceRow: 423,
      },
      northeast: {
        annualMeanUsd: 2103,
        standardErrorUsd: 37.24,
        relativeStandardErrorPercent: 1.77,
        column: "C",
        meanSourceRow: 420,
        standardErrorSourceRow: 422,
        relativeStandardErrorSourceRow: 423,
      },
      midwest: {
        annualMeanUsd: 2349,
        standardErrorUsd: 84.26,
        relativeStandardErrorPercent: 3.59,
        column: "D",
        meanSourceRow: 420,
        standardErrorSourceRow: 422,
        relativeStandardErrorSourceRow: 423,
      },
      south: {
        annualMeanUsd: 2395,
        standardErrorUsd: 52.59,
        relativeStandardErrorPercent: 2.2,
        column: "E",
        meanSourceRow: 420,
        standardErrorSourceRow: 422,
        relativeStandardErrorSourceRow: 423,
      },
      west: {
        annualMeanUsd: 2740,
        standardErrorUsd: 88.09,
        relativeStandardErrorPercent: 3.22,
        column: "F",
        meanSourceRow: 420,
        standardErrorSourceRow: 422,
        relativeStandardErrorSourceRow: 423,
      },
    },
    sizes: {
      "1": {
        annualMeanUsd: 1226,
        standardErrorUsd: 28.23,
        relativeStandardErrorPercent: 2.3,
        column: "C",
        meanSourceRow: 421,
        standardErrorSourceRow: 423,
        relativeStandardErrorSourceRow: 424,
      },
      "2": {
        annualMeanUsd: 2329,
        standardErrorUsd: 45.17,
        relativeStandardErrorPercent: 1.94,
        column: "E",
        meanSourceRow: 421,
        standardErrorSourceRow: 423,
        relativeStandardErrorSourceRow: 424,
      },
      "3": {
        annualMeanUsd: 2825,
        standardErrorUsd: 76.79,
        relativeStandardErrorPercent: 2.72,
        column: "F",
        meanSourceRow: 421,
        standardErrorSourceRow: 423,
        relativeStandardErrorSourceRow: 424,
      },
      "4": {
        annualMeanUsd: 3512,
        standardErrorUsd: 92.34,
        relativeStandardErrorPercent: 2.63,
        column: "G",
        meanSourceRow: 421,
        standardErrorSourceRow: 423,
        relativeStandardErrorSourceRow: 424,
      },
      "5plus": {
        annualMeanUsd: 4335,
        standardErrorUsd: 117.36,
        relativeStandardErrorPercent: 2.71,
        column: "H",
        meanSourceRow: 421,
        standardErrorSourceRow: 423,
        relativeStandardErrorSourceRow: 424,
      },
    },
  },
  maintenanceAndRepairs: {
    label: "Maintenance and repairs",
    regions: {
      national: {
        annualMeanUsd: 984,
        standardErrorUsd: 28.12,
        relativeStandardErrorPercent: 2.86,
        column: "B",
        meanSourceRow: 435,
        standardErrorSourceRow: 437,
        relativeStandardErrorSourceRow: 438,
      },
      northeast: {
        annualMeanUsd: 986,
        standardErrorUsd: 48.99,
        relativeStandardErrorPercent: 4.97,
        column: "C",
        meanSourceRow: 435,
        standardErrorSourceRow: 437,
        relativeStandardErrorSourceRow: 438,
      },
      midwest: {
        annualMeanUsd: 1037,
        standardErrorUsd: 63.57,
        relativeStandardErrorPercent: 6.13,
        column: "D",
        meanSourceRow: 435,
        standardErrorSourceRow: 437,
        relativeStandardErrorSourceRow: 438,
      },
      south: {
        annualMeanUsd: 822,
        standardErrorUsd: 41.96,
        relativeStandardErrorPercent: 5.1,
        column: "E",
        meanSourceRow: 435,
        standardErrorSourceRow: 437,
        relativeStandardErrorSourceRow: 438,
      },
      west: {
        annualMeanUsd: 1222,
        standardErrorUsd: 79.5,
        relativeStandardErrorPercent: 6.5,
        column: "F",
        meanSourceRow: 435,
        standardErrorSourceRow: 437,
        relativeStandardErrorSourceRow: 438,
      },
    },
    sizes: {
      "1": {
        annualMeanUsd: 619,
        standardErrorUsd: 28.81,
        relativeStandardErrorPercent: 4.65,
        column: "C",
        meanSourceRow: 436,
        standardErrorSourceRow: 438,
        relativeStandardErrorSourceRow: 439,
      },
      "2": {
        annualMeanUsd: 1036,
        standardErrorUsd: 47.14,
        relativeStandardErrorPercent: 4.55,
        column: "E",
        meanSourceRow: 436,
        standardErrorSourceRow: 438,
        relativeStandardErrorSourceRow: 439,
      },
      "3": {
        annualMeanUsd: 1018,
        standardErrorUsd: 68.38,
        relativeStandardErrorPercent: 6.72,
        column: "F",
        meanSourceRow: 436,
        standardErrorSourceRow: 438,
        relativeStandardErrorSourceRow: 439,
      },
      "4": {
        annualMeanUsd: 1358,
        standardErrorUsd: 88.58,
        relativeStandardErrorPercent: 6.52,
        column: "G",
        meanSourceRow: 436,
        standardErrorSourceRow: 438,
        relativeStandardErrorSourceRow: 439,
      },
      "5plus": {
        annualMeanUsd: 1412,
        standardErrorUsd: 112.17,
        relativeStandardErrorPercent: 7.94,
        column: "H",
        meanSourceRow: 436,
        standardErrorSourceRow: 438,
        relativeStandardErrorSourceRow: 439,
      },
    },
  },
  drugs: {
    label: "Drugs",
    regions: {
      national: {
        annualMeanUsd: 658,
        standardErrorUsd: 24.51,
        relativeStandardErrorPercent: 3.73,
        column: "B",
        meanSourceRow: 471,
        standardErrorSourceRow: 473,
        relativeStandardErrorSourceRow: 474,
      },
      northeast: {
        annualMeanUsd: 661,
        standardErrorUsd: 30.32,
        relativeStandardErrorPercent: 4.59,
        column: "C",
        meanSourceRow: 471,
        standardErrorSourceRow: 473,
        relativeStandardErrorSourceRow: 474,
      },
      midwest: {
        annualMeanUsd: 662,
        standardErrorUsd: 26.6,
        relativeStandardErrorPercent: 4.02,
        column: "D",
        meanSourceRow: 471,
        standardErrorSourceRow: 473,
        relativeStandardErrorSourceRow: 474,
      },
      south: {
        annualMeanUsd: 629,
        standardErrorUsd: 53.66,
        relativeStandardErrorPercent: 8.53,
        column: "E",
        meanSourceRow: 471,
        standardErrorSourceRow: 473,
        relativeStandardErrorSourceRow: 474,
      },
      west: {
        annualMeanUsd: 703,
        standardErrorUsd: 54.69,
        relativeStandardErrorPercent: 7.78,
        column: "F",
        meanSourceRow: 471,
        standardErrorSourceRow: 473,
        relativeStandardErrorSourceRow: 474,
      },
    },
    sizes: {
      "1": {
        annualMeanUsd: 457,
        standardErrorUsd: 27.43,
        relativeStandardErrorPercent: 6,
        column: "C",
        meanSourceRow: 472,
        standardErrorSourceRow: 474,
        relativeStandardErrorSourceRow: 475,
      },
      "2": {
        annualMeanUsd: 810,
        standardErrorUsd: 31.23,
        relativeStandardErrorPercent: 3.86,
        column: "E",
        meanSourceRow: 472,
        standardErrorSourceRow: 474,
        relativeStandardErrorSourceRow: 475,
      },
      "3": {
        annualMeanUsd: 681,
        standardErrorUsd: 40.57,
        relativeStandardErrorPercent: 5.96,
        column: "F",
        meanSourceRow: 472,
        standardErrorSourceRow: 474,
        relativeStandardErrorSourceRow: 475,
      },
      "4": {
        annualMeanUsd: 634,
        standardErrorUsd: 64.57,
        relativeStandardErrorPercent: 10.19,
        column: "G",
        meanSourceRow: 472,
        standardErrorSourceRow: 474,
        relativeStandardErrorSourceRow: 475,
      },
      "5plus": {
        annualMeanUsd: 759,
        standardErrorUsd: 91.78,
        relativeStandardErrorPercent: 12.09,
        column: "H",
        meanSourceRow: 472,
        standardErrorSourceRow: 474,
        relativeStandardErrorSourceRow: 475,
      },
    },
  },
  medicalSupplies: {
    label: "Medical supplies",
    regions: {
      national: {
        annualMeanUsd: 233,
        standardErrorUsd: 19.89,
        relativeStandardErrorPercent: 8.54,
        column: "B",
        meanSourceRow: 476,
        standardErrorSourceRow: 478,
        relativeStandardErrorSourceRow: 479,
      },
      northeast: {
        annualMeanUsd: 220,
        standardErrorUsd: 22.4,
        relativeStandardErrorPercent: 10.19,
        column: "C",
        meanSourceRow: 476,
        standardErrorSourceRow: 478,
        relativeStandardErrorSourceRow: 479,
      },
      midwest: {
        annualMeanUsd: 262,
        standardErrorUsd: 25.4,
        relativeStandardErrorPercent: 9.71,
        column: "D",
        meanSourceRow: 476,
        standardErrorSourceRow: 478,
        relativeStandardErrorSourceRow: 479,
      },
      south: {
        annualMeanUsd: 217,
        standardErrorUsd: 46.09,
        relativeStandardErrorPercent: 21.23,
        column: "E",
        meanSourceRow: 476,
        standardErrorSourceRow: 478,
        relativeStandardErrorSourceRow: 479,
      },
      west: {
        annualMeanUsd: 244,
        standardErrorUsd: 16.67,
        relativeStandardErrorPercent: 6.82,
        column: "F",
        meanSourceRow: 476,
        standardErrorSourceRow: 478,
        relativeStandardErrorSourceRow: 479,
      },
    },
    sizes: {
      "1": {
        annualMeanUsd: 144,
        standardErrorUsd: 11.23,
        relativeStandardErrorPercent: 7.81,
        column: "C",
        meanSourceRow: 477,
        standardErrorSourceRow: 479,
        relativeStandardErrorSourceRow: 480,
      },
      "2": {
        annualMeanUsd: 330,
        standardErrorUsd: 54.1,
        relativeStandardErrorPercent: 16.39,
        column: "E",
        meanSourceRow: 477,
        standardErrorSourceRow: 479,
        relativeStandardErrorSourceRow: 480,
      },
      "3": {
        annualMeanUsd: 207,
        standardErrorUsd: 18.3,
        relativeStandardErrorPercent: 8.84,
        column: "F",
        meanSourceRow: 477,
        standardErrorSourceRow: 479,
        relativeStandardErrorSourceRow: 480,
      },
      "4": {
        annualMeanUsd: 235,
        standardErrorUsd: 19.81,
        relativeStandardErrorPercent: 8.44,
        column: "G",
        meanSourceRow: 477,
        standardErrorSourceRow: 479,
        relativeStandardErrorSourceRow: 480,
      },
      "5plus": {
        annualMeanUsd: 213,
        standardErrorUsd: 28.81,
        relativeStandardErrorPercent: 13.5,
        column: "H",
        meanSourceRow: 477,
        standardErrorSourceRow: 479,
        relativeStandardErrorSourceRow: 480,
      },
    },
  },
} as const;
