/** Compiled source anchors for the local game profile. Rebuild from the
 * current municipal-governance corpus when that source projection changes.
 * This small index lets a saved pack resolve without loading the full
 * municipal inventory during cold legislative lookup.
 */
export const LOCAL_ORDINANCE_SOURCE_ANCHORS = {
  "gus2025:100091": {
    governmentKey: "us-al-montgomery",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:106079": {
    governmentKey: "us-ma-worcester",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Worcester City Council",
    bodySize: 11,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Worcester City Council",
      sourceUrl: "https://www.worcesterma.gov/city-council",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:106897": {
    governmentKey: "us-mn-duluth",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Duluth City Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Duluth City Council",
      sourceUrl: "https://duluthmn.gov/city-council/",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:109096": {
    governmentKey: "us-nj-trenton",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Trenton City Council",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Trenton City Council meetings",
      sourceUrl: "https://www.trentonnj.org/476/Meetings",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:109329": {
    governmentKey: "us-nm-santa-fe",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Governing Body",
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:110222": {
    governmentKey: "us-nd-grand-forks",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:115492": {
    governmentKey: "us-wy-cheyenne",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:124038": {
    governmentKey: "us-ct-bridgeport",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:124214": {
    governmentKey: "us-dc-washington",
    sourceEvidence: "enacted-text",
    safeGameProcedure: false,
    bodyName: "Council of the District of Columbia",
    bodySize: 13,
    bodySizeSource: {
      authority: "statute",
      citation: "D.C. Code § 1-204.01(b)(1)",
      sourceTitle: "D.C. Code § 1-204.01 Creation and membership",
      sourceUrl:
        "https://code.dccouncil.gov/us/dc/council/code/sections/1-204.01",
      retrievedAt: "2026-09-20",
      verification: "verified",
      note: null,
    },
  },
  "gus2025:124438": {
    governmentKey: "us-ga-savannah",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Savannah Mayor and Aldermen",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Council meeting schedule",
      sourceUrl: "https://www.savannahga.gov/458/Council-Meeting-Schedule",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:127810": {
    governmentKey: "us-la-shreveport",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:128028": {
    governmentKey: "us-md-annapolis",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "City Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:133602": {
    governmentKey: "us-pa-philadelphia",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:136562": {
    governmentKey: "us-wi-milwaukee",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:136964": {
    governmentKey: "us-wy-casper",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:160683": {
    governmentKey: "us-al-mobile",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:160840": {
    governmentKey: "us-az-tucson",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Mayor and Council",
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:161064": {
    governmentKey: "us-ar-fort-smith",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Fort Smith Board of Directors",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Board of Directors",
      sourceUrl:
        "https://www.fortsmithar.gov/government/leadership/board-of-directors",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:161529": {
    governmentKey: "us-de-wilmington",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Wilmington City Council",
    bodySize: 13,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "City of Wilmington",
      sourceUrl: "https://www.wilmingtonde.gov/",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:161650": {
    governmentKey: "us-fl-tallahassee",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "City Commission",
    bodySize: 5,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:162035": {
    governmentKey: "us-id-boise",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Boise City Council",
    bodySize: 6,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "FY2026 Adopted Budget",
      sourceUrl:
        "https://www.cityofboise.org/media/20517/fy-26-adopted-budget-ada-compliant.pdf",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:162037": {
    governmentKey: "us-id-meridian",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 6,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:163465": {
    governmentKey: "us-in-fort-wayne",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:164452": {
    governmentKey: "us-ia-iowa-city",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Iowa City City Council",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Iowa City City Council",
      sourceUrl: "https://www.icgov.org/government/city-council",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:165831": {
    governmentKey: "us-ky-lexington-fayette-ucg",
    sourceEvidence: "research-transcription",
    safeGameProcedure: false,
    bodyName: "Urban County Council",
    bodySize: 15,
    bodySizeSource: {
      authority: "research-reference",
      citation: "lfucg-council",
      sourceTitle:
        "Office of the Urban County Council — City of Lexington, Kentucky",
      sourceUrl:
        "https://www.lexingtonky.gov/government/office-urban-county-council",
      retrievedAt: "2026-09-05",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:165866": {
    governmentKey: "us-ky-louisville-jefferson-metro",
    sourceEvidence: "research-transcription",
    safeGameProcedure: false,
    bodyName: "Louisville Metro Council",
    bodySize: 26,
    bodySizeSource: {
      authority: "research-reference",
      citation: "louisville-metro",
      sourceTitle: "Metro Council — Louisville Metro Government",
      sourceUrl: "https://louisvilleky.gov/government/metro-council",
      retrievedAt: "2026-09-05",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:166094": {
    governmentKey: "us-la-new-orleans",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "New Orleans City Council",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "New Orleans City Council",
      sourceUrl: "https://council.nola.gov/",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:166159": {
    governmentKey: "us-me-lewiston",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:166160": {
    governmentKey: "us-me-portland",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:166166": {
    governmentKey: "us-me-bangor",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Bangor City Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Bangor City Council",
      sourceUrl: "https://bangormaine.gov/446/City-Council",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:167605": {
    governmentKey: "us-mn-saint-paul",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:168896": {
    governmentKey: "us-mo-springfield",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:169464": {
    governmentKey: "us-mt-missoula",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "City Council",
    bodySize: 12,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:169988": {
    governmentKey: "us-nv-las-vegas",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "City Council",
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:169993": {
    governmentKey: "us-nv-reno",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Reno City Council",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Reno City Council",
      sourceUrl: "https://www.reno.gov/government/city-council/",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:170001": {
    governmentKey: "us-nh-manchester",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Board of Mayor and Aldermen",
    bodySize: 15,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Board of Mayor and Aldermen",
      sourceUrl: "https://www.manchesternh.gov/Government/Mayor-and-Aldermen",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:170378": {
    governmentKey: "us-nm-albuquerque",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:171305": {
    governmentKey: "us-nc-raleigh",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:175728": {
    governmentKey: "us-tn-nashville-davidson-county",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:176546": {
    governmentKey: "us-vt-burlington",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:176966": {
    governmentKey: "us-wv-huntington",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:177842": {
    governmentKey: "us-wy-laramie",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Laramie City Council",
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:183701": {
    governmentKey: "us-hi-honolulu",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Honolulu City Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Honolulu City Council",
      sourceUrl: "https://www.honolulucitycouncil.org/",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:184191": {
    governmentKey: "us-ne-grand-island",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "City Council",
    bodySize: 10,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:184856": {
    governmentKey: "us-hi-hawaii-county",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:193734": {
    governmentKey: "us-nj-jersey-city",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "City Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:194177": {
    governmentKey: "us-va-charlottesville",
    sourceEvidence: "enacted-text",
    safeGameProcedure: false,
    bodyName: "Council of the City of Charlottesville",
    bodySize: 5,
    bodySizeSource: {
      authority: "statute",
      citation: "Charter § 5(b)",
      sourceTitle: "Charter of the City of Charlottesville, Virginia",
      sourceUrl: "https://law.lis.virginia.gov/charters/charlottesville/",
      retrievedAt: "2026-09-08",
      verification: "verified",
      note: null,
    },
  },
  "gus2025:194178": {
    governmentKey: "us-va-richmond",
    sourceEvidence: "enacted-text",
    safeGameProcedure: false,
    bodyName: "Council of the City of Richmond",
    bodySize: 9,
    bodySizeSource: {
      authority: "statute",
      citation: "Charter § 4.01",
      sourceTitle: "Charter of the City of Richmond, Virginia",
      sourceUrl: "https://law.lis.virginia.gov/charters/richmond/",
      retrievedAt: "2026-09-08",
      verification: "verified",
      note: null,
    },
  },
  "gus2025:194463": {
    governmentKey: "us-ak-anchorage",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Anchorage Assembly",
    bodySize: 12,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipality of Anchorage",
      sourceUrl: "https://www.muni.org/",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:194647": {
    governmentKey: "us-co-denver",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Denver City Council",
    bodySize: 13,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Denver City Council",
      sourceUrl:
        "https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Denver-City-Council",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:194679": {
    governmentKey: "us-ga-augusta-richmond-county",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Commission",
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:194805": {
    governmentKey: "us-ny-new-york-city",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:194943": {
    governmentKey: "us-nv-carson-city",
    sourceEvidence: "enacted-text",
    safeGameProcedure: false,
    bodyName: "Carson City Board of Supervisors",
    bodySize: 5,
    bodySizeSource: {
      authority: "statute",
      citation: "Charter § 2.010(1)",
      sourceTitle: "Charter of Carson City, Nevada",
      sourceUrl:
        "https://www.leg.state.nv.us/Division/Legal/LawLibrary/CityCharters/CtyCCCC.html",
      retrievedAt: "2026-09-08",
      verification: "verified",
      note: null,
    },
  },
  "gus2025:201810": {
    governmentKey: "us-ks-wichita",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Governing Body",
    bodySize: 7,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:204917": {
    governmentKey: "us-nh-concord",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "City Council",
    bodySize: 15,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:207536": {
    governmentKey: "us-az-phoenix",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Phoenix City Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Phoenix City Clerk — About City Council meetings",
      sourceUrl:
        "https://www.phoenix.gov/administration/departments/cityclerk/programs-services/city-council-meetings/about.html",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:208246": {
    governmentKey: "us-md-baltimore",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Baltimore City Council",
    bodySize: 15,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Baltimore City Council",
      sourceUrl: "https://baltimorecitycouncil.com/",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:208744": {
    governmentKey: "us-nh-enfield",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Enfield Town Meeting",
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:209050": {
    governmentKey: "us-oh-columbus",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:209170": {
    governmentKey: "us-ok-oklahoma-city",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:209465": {
    governmentKey: "us-sd-aberdeen",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:209777": {
    governmentKey: "us-wi-madison",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: null,
    bodySize: null,
    bodySizeSource: null,
  },
  "gus2025:211254": {
    governmentKey: "us-or-portland",
    sourceEvidence: "enacted-text",
    safeGameProcedure: true,
    bodyName: "City Council",
    bodySize: 12,
    bodySizeSource: {
      authority: "statute",
      citation: "Portland City Charter § 2-102",
      sourceTitle: "Portland City Charter, Section 2-102 City Council",
      sourceUrl: "https://www.portland.gov/charter/2/1/102",
      retrievedAt: "2026-09-09",
      verification: "verified",
      note: null,
    },
  },
  "gus2025:211708": {
    governmentKey: "us-in-bloomington",
    sourceEvidence: "research-transcription",
    safeGameProcedure: true,
    bodyName: "Common Council",
    bodySize: 9,
    bodySizeSource: {
      authority: "research-reference",
      citation: "body size",
      sourceTitle: "Municipal research packet 44",
      sourceUrl:
        "https://docs.google.com/document/d/1NLddpuRckHQvpjDVUjhVx_HItEubfmDUTAvzrPiBprk/edit",
      retrievedAt: "2026-08-25",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
  "gus2025:212021": {
    governmentKey: "us-ky-bowling-green",
    sourceEvidence: "research-transcription",
    safeGameProcedure: false,
    bodyName: "Board of Commissioners",
    bodySize: 5,
    bodySizeSource: {
      authority: "research-reference",
      citation: "bgky-gov",
      sourceTitle: "How Government Works — City of Bowling Green, Kentucky",
      sourceUrl: "https://www.bgky.org/government/how-government-works",
      retrievedAt: "2026-09-05",
      verification: "partial",
      note: "Research transcription; not independently verified operative law.",
    },
  },
} as const;
