/** GENERATED by export-municipal-governments.ts; do not edit. */
/** Complete admitted registry, not an unloaded inventory. See the full inventory for refusals. */
export const MUNICIPAL_RULE_REGISTRY_META = {
  "productionCorpusSha256": "dab27077f2faed5926590576b2bcf81f5b88d3f2a7de34043ef31693932ef062",
  "kentuckyCorpusSha256": "59be6547d3ca4bd03691ba0f14d0080e1845f4050a18f084574523e29f45909f",
  "nationalCorpusSha256": "e3d380a6c7560f52d354369749feaf0502577fef9603eec9b149d796d12412b4",
  "referenceObservationSha256": "26e374d21ed2eafe827ebc4d05ce3dc7d71d18d7367d13961c2a7fbf6a8e9507",
  "inventoryGovernments": 144,
  "admittedPacks": 0
} as const;

export const MUNICIPAL_RULE_PACKS_JSON: string = "[]";
