// Generated by scripts/traits/personality-catalogue.ts from
// docs/research/chatgpt-answers/2026-09-22-depth2/personality-scale-dispositions.json. Do not edit by hand.
// Source catalog sha256 868726452fc66ead40a7c5eec601f2a2fe6962ca0a31582009187c01177fbf14.

import type { CatalogueScale } from "./personality-catalogue";

export const CATALOGUE_SCALES: readonly CatalogueScale[] = [
  {
    "key": "self-confidence",
    "sides": "two",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Confidence in one's own adequacy, not superiority or predicted success.",
    "low": {
      "label": "Insecure",
      "meaning": "Doubts own adequacy and looks for reassurance."
    },
    "high": {
      "label": "Self-assured",
      "meaning": "Trusts own judgment without requiring superiority over others."
    }
  },
  {
    "key": "social-contact-preference",
    "sides": "two",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "Preference for being alone versus frequent company when both are feasible; disclosure and inhibition remain separate.",
    "low": {
      "label": "Solitude-seeking",
      "meaning": "Often chooses time alone when both options are available."
    },
    "high": {
      "label": "Gregarious",
      "meaning": "Seeks frequent social contact and initiates exchanges."
    }
  },
  {
    "key": "playful-manner",
    "sides": "two",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Purposeful versus playful default delivery; neither prevents humor or serious decisions.",
    "low": {
      "label": "Serious",
      "meaning": "Usually favors purposeful discussion over joking."
    },
    "high": {
      "label": "Playful",
      "meaning": "Uses humor and low-stakes play to engage."
    }
  },
  {
    "key": "voluntary-effort",
    "sides": "two",
    "family": "Work and follow-through",
    "profile": "follow-through",
    "meaning": "Preference for sustained effort on a chosen feasible task, after constraints are accounted for.",
    "low": {
      "label": "Effort-averse",
      "meaning": "Prefers lower-effort options when stakes permit."
    },
    "high": {
      "label": "Industrious",
      "meaning": "Voluntarily applies sustained effort to a chosen task."
    }
  },
  {
    "key": "ownership-of-duties",
    "sides": "two",
    "family": "Work and follow-through",
    "profile": "follow-through",
    "meaning": "Taking ownership of foreseeable responsibilities and consequences.",
    "low": {
      "label": "Irresponsible",
      "meaning": "Tends to avoid ownership of foreseeable duties."
    },
    "high": {
      "label": "Responsible",
      "meaning": "Takes ownership of duties and consequences beyond a narrow promise."
    }
  },
  {
    "key": "concern-for-distress",
    "sides": "two",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Weight given to suffering the person actually understands; not automatic policy support.",
    "low": {
      "label": "Callous",
      "meaning": "Gives relatively little weight to another person's distress."
    },
    "high": {
      "label": "Compassionate",
      "meaning": "Gives weight to understood suffering and personal circumstances."
    }
  },
  {
    "key": "initial-trust",
    "sides": "two",
    "family": "Trust and integrity",
    "profile": "relational",
    "meaning": "Initial credit given to reasonable claims when evidence is incomplete; not knowledge of who is truthful.",
    "low": {
      "label": "Suspicious",
      "meaning": "Looks for concealed motives and seeks corroboration."
    },
    "high": {
      "label": "Trusting",
      "meaning": "Initially gives reasonable claims the benefit of doubt."
    }
  },
  {
    "key": "bond-loyalty",
    "sides": "two",
    "family": "Trust and integrity",
    "profile": "relational",
    "meaning": "Weight of an established allegiance when other motives compete, without overriding consent or every moral limit.",
    "low": {
      "label": "Disloyal",
      "meaning": "Readily abandons a represented allegiance when other motives prevail."
    },
    "high": {
      "label": "Loyal",
      "meaning": "Gives sustained weight to particular established bonds."
    }
  },
  {
    "key": "truthfulness",
    "sides": "two",
    "family": "Trust and integrity",
    "profile": "relational",
    "meaning": "Preference for statements matching believed truth rather than intentional misrepresentation; error is not deceit.",
    "low": {
      "label": "Deceitful",
      "meaning": "Is more willing to intentionally misrepresent known information."
    },
    "high": {
      "label": "Honest",
      "meaning": "Usually favors statements matching what they believe true."
    }
  },
  {
    "key": "method-revision",
    "sides": "two",
    "family": "Rules and flexibility",
    "profile": "cognition",
    "meaning": "Resistance or openness to changing an established method. This does not collapse conviction, fairness or curiosity.",
    "low": {
      "label": "Stubborn",
      "meaning": "Resists revising an established judgment or approach."
    },
    "high": {
      "label": "Flexible",
      "meaning": "Readily revises methods when a workable alternative appears."
    }
  },
  {
    "key": "patience",
    "sides": "two",
    "family": "Pacing and risk",
    "profile": "pressure",
    "meaning": "Tolerance of necessary delay while an objective remains viable; not persistence on an impossible goal.",
    "low": {
      "label": "Impatient",
      "meaning": "Places greater weight on obtaining a result soon."
    },
    "high": {
      "label": "Patient",
      "meaning": "Tolerates a necessary delay when the objective remains viable."
    }
  },
  {
    "key": "action-despite-fear",
    "sides": "two",
    "family": "Pacing and risk",
    "profile": "pressure",
    "meaning": "Readiness to act despite perceived personal threat when the purpose matters; not thrill-seeking.",
    "low": {
      "label": "Timid",
      "meaning": "Is easily deterred by perceived personal threat."
    },
    "high": {
      "label": "Brave",
      "meaning": "Can act despite recognized fear when the purpose matters."
    }
  },
  {
    "key": "outward-emotional-display",
    "sides": "two",
    "family": "Emotional style",
    "profile": "pressure",
    "meaning": "Restraining versus communicating felt emotion; neither end means feeling more or less.",
    "low": {
      "label": "Stoic",
      "meaning": "Usually restrains outward display while bearing difficulty."
    },
    "high": {
      "label": "Emotionally expressive",
      "meaning": "Readily communicates felt emotion through words and manner."
    }
  },
  {
    "key": "uncertain-outlook",
    "sides": "two",
    "family": "Emotional outlook",
    "profile": "appraisal",
    "meaning": "Expected prospects under uncertainty, subject to known evidence rather than denial of facts.",
    "low": {
      "label": "Pessimistic",
      "meaning": "Anticipates adverse possibilities and limited prospects."
    },
    "high": {
      "label": "Optimistic",
      "meaning": "Expects attainable improvement when evidence is uncertain."
    }
  },
  {
    "key": "facet-cocky",
    "sides": "one",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Overestimates personal prospects and advertises confidence.",
    "low": {
      "label": "No marked cocky tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Cocky",
      "meaning": "Overestimates personal prospects and advertises confidence."
    }
  },
  {
    "key": "facet-proud",
    "sides": "one",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Attaches importance to dignity and recognition.",
    "low": {
      "label": "No marked status sensitivity",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Proud",
      "meaning": "Attaches importance to dignity and recognition."
    }
  },
  {
    "key": "facet-humble",
    "sides": "one",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Downplays own status and shares credit.",
    "low": {
      "label": "No marked modesty",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Humble",
      "meaning": "Downplays own status and shares credit."
    }
  },
  {
    "key": "facet-self-conscious",
    "sides": "one",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Pays close attention to being observed and evaluated.",
    "low": {
      "label": "No marked self conscious tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Self-conscious",
      "meaning": "Pays close attention to being observed and evaluated."
    }
  },
  {
    "key": "facet-approval-seeking",
    "sides": "one",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Places particular weight on favorable reactions.",
    "low": {
      "label": "No marked approval seeking tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Approval-seeking",
      "meaning": "Places particular weight on favorable reactions."
    }
  },
  {
    "key": "facet-smug",
    "sides": "one",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Dwells on satisfaction with own achievements.",
    "low": {
      "label": "No marked smug tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Smug",
      "meaning": "Dwells on satisfaction with own achievements."
    }
  },
  {
    "key": "facet-entitled",
    "sides": "one",
    "family": "Self-image",
    "profile": "appraisal",
    "meaning": "Expects preferential treatment beyond established obligations.",
    "low": {
      "label": "No marked entitled tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Entitled",
      "meaning": "Expects preferential treatment beyond established obligations."
    }
  },
  {
    "key": "facet-brazen",
    "sides": "one",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "Is less inhibited by social audacity or embarrassment.",
    "low": {
      "label": "No marked social audacity",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Brazen",
      "meaning": "Is less inhibited by social audacity or embarrassment."
    }
  },
  {
    "key": "facet-assertive",
    "sides": "one",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "States needs and boundaries without needing to attack.",
    "low": {
      "label": "No marked assertive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Assertive",
      "meaning": "States needs and boundaries without needing to attack."
    }
  },
  {
    "key": "facet-deferential",
    "sides": "one",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "Initially yields conversational space to recognized expertise or rank.",
    "low": {
      "label": "No marked deferential tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Deferential",
      "meaning": "Initially yields conversational space to recognized expertise or rank."
    }
  },
  {
    "key": "facet-reserved",
    "sides": "one",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "Discloses thoughts and feelings selectively.",
    "low": {
      "label": "No marked reserved tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Reserved",
      "meaning": "Discloses thoughts and feelings selectively."
    }
  },
  {
    "key": "facet-shy",
    "sides": "one",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "Feels inhibited around unfamiliar people despite possible interest.",
    "low": {
      "label": "No marked social inhibition",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Shy",
      "meaning": "Feels inhibited around unfamiliar people despite possible interest."
    }
  },
  {
    "key": "facet-slow-to-warm-up",
    "sides": "one",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "Opens up through repeated safe contact.",
    "low": {
      "label": "No marked slow to warm up tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Slow to warm up",
      "meaning": "Opens up through repeated safe contact."
    }
  },
  {
    "key": "facet-independent",
    "sides": "one",
    "family": "Social approach",
    "profile": "manner",
    "meaning": "Prefers autonomy in how tasks and time are managed.",
    "low": {
      "label": "No marked independent tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Independent",
      "meaning": "Prefers autonomy in how tasks and time are managed."
    }
  },
  {
    "key": "facet-friendly",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Usually begins with a welcoming cooperative manner.",
    "low": {
      "label": "No marked friendly tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Friendly",
      "meaning": "Usually begins with a welcoming cooperative manner."
    }
  },
  {
    "key": "facet-charming",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Uses engaging attention and responsive delivery.",
    "low": {
      "label": "No marked charming tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Charming",
      "meaning": "Uses engaging attention and responsive delivery."
    }
  },
  {
    "key": "facet-blunt",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Delivers conclusions with little cushioning.",
    "low": {
      "label": "No marked blunt tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Blunt",
      "meaning": "Delivers conclusions with little cushioning."
    }
  },
  {
    "key": "facet-tactful",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Adjusts timing and wording to avoid needless harm.",
    "low": {
      "label": "No marked tactful tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Tactful",
      "meaning": "Adjusts timing and wording to avoid needless harm."
    }
  },
  {
    "key": "facet-polite",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Uses conventional courtesies and respects turn-taking.",
    "low": {
      "label": "No marked polite tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Polite",
      "meaning": "Uses conventional courtesies and respects turn-taking."
    }
  },
  {
    "key": "facet-informal",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Avoids ceremony and favors conversational familiarity.",
    "low": {
      "label": "No marked informal tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Informal",
      "meaning": "Avoids ceremony and favors conversational familiarity."
    }
  },
  {
    "key": "facet-cheeky",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Playfully tests small social boundaries.",
    "low": {
      "label": "No marked cheeky tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Cheeky",
      "meaning": "Playfully tests small social boundaries."
    }
  },
  {
    "key": "facet-sassy",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Uses sharp, self-possessed verbal pushback.",
    "low": {
      "label": "No marked sassy tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Sassy",
      "meaning": "Uses sharp, self-possessed verbal pushback."
    }
  },
  {
    "key": "facet-mischievous",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Looks for playful disruption or a low-stakes trick.",
    "low": {
      "label": "No marked mischievous tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Mischievous",
      "meaning": "Looks for playful disruption or a low-stakes trick."
    }
  },
  {
    "key": "facet-dramatic",
    "sides": "one",
    "family": "Social manner",
    "profile": "manner",
    "meaning": "Expresses reactions in conspicuous, theatrical ways.",
    "low": {
      "label": "No marked dramatic tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Dramatic",
      "meaning": "Expresses reactions in conspicuous, theatrical ways."
    }
  },
  {
    "key": "facet-studious",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Chooses sustained effort to understand a subject.",
    "low": {
      "label": "No marked study inclination",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Studious",
      "meaning": "Chooses sustained effort to understand a subject."
    }
  },
  {
    "key": "facet-curious",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Actively explores unanswered questions.",
    "low": {
      "label": "No marked curious tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Curious",
      "meaning": "Actively explores unanswered questions."
    }
  },
  {
    "key": "facet-analytical",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Breaks a problem into parts and compares reasons.",
    "low": {
      "label": "No marked analytical tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Analytical",
      "meaning": "Breaks a problem into parts and compares reasons."
    }
  },
  {
    "key": "facet-practical",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Focuses on feasible next steps under actual constraints.",
    "low": {
      "label": "No marked practical tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Practical",
      "meaning": "Focuses on feasible next steps under actual constraints."
    }
  },
  {
    "key": "facet-inventive",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Searches for a different supported way to achieve a goal.",
    "low": {
      "label": "No marked inventive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Inventive",
      "meaning": "Searches for a different supported way to achieve a goal."
    }
  },
  {
    "key": "facet-imaginative",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Readily considers hypothetical situations and possibilities.",
    "low": {
      "label": "No marked imaginative tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Imaginative",
      "meaning": "Readily considers hypothetical situations and possibilities."
    }
  },
  {
    "key": "facet-open-minded",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Gives unfamiliar explanations a hearing.",
    "low": {
      "label": "No marked open minded tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Open-minded",
      "meaning": "Gives unfamiliar explanations a hearing."
    }
  },
  {
    "key": "facet-skeptical",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Asks what supports a claim before relying on it.",
    "low": {
      "label": "No marked skeptical tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Skeptical",
      "meaning": "Asks what supports a claim before relying on it."
    }
  },
  {
    "key": "facet-cynical",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Often interprets stated ideals through self-interest.",
    "low": {
      "label": "No marked cynical tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Cynical",
      "meaning": "Often interprets stated ideals through self-interest."
    }
  },
  {
    "key": "facet-distractible",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Attention can shift away from the current task.",
    "low": {
      "label": "No marked distractible tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Distractible",
      "meaning": "Attention can shift away from the current task."
    }
  },
  {
    "key": "facet-daydreaming",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Attention sometimes turns inward to possibilities.",
    "low": {
      "label": "No marked daydreaming tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Daydreaming",
      "meaning": "Attention sometimes turns inward to possibilities."
    }
  },
  {
    "key": "facet-observant",
    "sides": "one",
    "family": "Thinking and learning",
    "profile": "cognition",
    "meaning": "Pays attention to available behavioral and contextual cues.",
    "low": {
      "label": "No marked observant tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Observant",
      "meaning": "Pays attention to available behavioral and contextual cues."
    }
  },
  {
    "key": "facet-meticulous",
    "sides": "one",
    "family": "Work and follow-through",
    "profile": "follow-through",
    "meaning": "Checks details and consistency before completion.",
    "low": {
      "label": "No marked meticulous tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Meticulous",
      "meaning": "Checks details and consistency before completion."
    }
  },
  {
    "key": "facet-persistent",
    "sides": "one",
    "family": "Work and follow-through",
    "profile": "follow-through",
    "meaning": "Keeps pursuing an objective through setbacks.",
    "low": {
      "label": "No marked persistent tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Persistent",
      "meaning": "Keeps pursuing an objective through setbacks."
    }
  },
  {
    "key": "facet-duty-bound",
    "sides": "one",
    "family": "Work and follow-through",
    "profile": "follow-through",
    "meaning": "Prioritizes a recognized role obligation even when inconvenient.",
    "low": {
      "label": "No marked duty bound tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Duty-bound",
      "meaning": "Prioritizes a recognized role obligation even when inconvenient."
    }
  },
  {
    "key": "facet-work-centered",
    "sides": "one",
    "family": "Work and follow-through",
    "profile": "follow-through",
    "meaning": "Lets work occupy attention and time beyond necessity.",
    "low": {
      "label": "No marked work centered tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Work-centered",
      "meaning": "Lets work occupy attention and time beyond necessity."
    }
  },
  {
    "key": "facet-ambitious",
    "sides": "one",
    "family": "Goals and advantage",
    "profile": "motivation",
    "meaning": "Seeks advancement, responsibility or meaningful achievement.",
    "low": {
      "label": "No marked ambitious tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Ambitious",
      "meaning": "Seeks advancement, responsibility or meaningful achievement."
    }
  },
  {
    "key": "facet-contented",
    "sides": "one",
    "family": "Goals and advantage",
    "profile": "motivation",
    "meaning": "Places less weight on further status once current aims are met.",
    "low": {
      "label": "No marked contented tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Contented",
      "meaning": "Places less weight on further status once current aims are met."
    }
  },
  {
    "key": "facet-competitive",
    "sides": "one",
    "family": "Goals and advantage",
    "profile": "motivation",
    "meaning": "Pays attention to relative performance and winning.",
    "low": {
      "label": "No marked competitive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Competitive",
      "meaning": "Pays attention to relative performance and winning."
    }
  },
  {
    "key": "facet-opportunistic",
    "sides": "one",
    "family": "Goals and advantage",
    "profile": "motivation",
    "meaning": "Reconsiders plans when a beneficial opening appears.",
    "low": {
      "label": "No marked opportunistic tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Opportunistic",
      "meaning": "Reconsiders plans when a beneficial opening appears."
    }
  },
  {
    "key": "facet-enterprising",
    "sides": "one",
    "family": "Goals and advantage",
    "profile": "motivation",
    "meaning": "Initiates a feasible project when an unmet opportunity is noticed.",
    "low": {
      "label": "No marked enterprising tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Enterprising",
      "meaning": "Initiates a feasible project when an unmet opportunity is noticed."
    }
  },
  {
    "key": "facet-self-serving",
    "sides": "one",
    "family": "Goals and advantage",
    "profile": "motivation",
    "meaning": "Gives unusual weight to personal benefit.",
    "low": {
      "label": "No marked self serving tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Self-serving",
      "meaning": "Gives unusual weight to personal benefit."
    }
  },
  {
    "key": "facet-acquisitive",
    "sides": "one",
    "family": "Goals and advantage",
    "profile": "motivation",
    "meaning": "Strongly values gaining or retaining resources.",
    "low": {
      "label": "No marked acquisitive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Acquisitive",
      "meaning": "Strongly values gaining or retaining resources."
    }
  },
  {
    "key": "facet-generous",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Readily shares available resources or time.",
    "low": {
      "label": "No marked generous tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Generous",
      "meaning": "Readily shares available resources or time."
    }
  },
  {
    "key": "facet-gentle",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Avoids rough or intimidating delivery even under disagreement.",
    "low": {
      "label": "No marked gentle tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Gentle",
      "meaning": "Avoids rough or intimidating delivery even under disagreement."
    }
  },
  {
    "key": "facet-supportive",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Actively helps another person persist or recover confidence.",
    "low": {
      "label": "No marked supportive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Supportive",
      "meaning": "Actively helps another person persist or recover confidence."
    }
  },
  {
    "key": "facet-comforting",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Responds to distress with reassurance or attentive presence.",
    "low": {
      "label": "No marked comforting tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Comforting",
      "meaning": "Responds to distress with reassurance or attentive presence."
    }
  },
  {
    "key": "facet-nurturing",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Invests attention in another person's growth and care.",
    "low": {
      "label": "No marked nurturing tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Nurturing",
      "meaning": "Invests attention in another person's growth and care."
    }
  },
  {
    "key": "facet-philanthropic",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Frequently turns concern into voluntary material or service support.",
    "low": {
      "label": "No marked philanthropic tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Philanthropic",
      "meaning": "Frequently turns concern into voluntary material or service support."
    }
  },
  {
    "key": "facet-envious",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Reacts strongly to a comparison that favors someone else.",
    "low": {
      "label": "No marked envious tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Envious",
      "meaning": "Reacts strongly to a comparison that favors someone else."
    }
  },
  {
    "key": "facet-cruel",
    "sides": "one",
    "family": "Concern and reciprocity",
    "profile": "relational",
    "meaning": "Sometimes uses humiliation or suffering as a means or end.",
    "low": {
      "label": "No marked inclination to cruelty",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Cruel",
      "meaning": "Sometimes uses humiliation or suffering as a means or end."
    }
  },
  {
    "key": "facet-sincere",
    "sides": "one",
    "family": "Trust and integrity",
    "profile": "relational",
    "meaning": "Tries to make expressed appreciation or apology genuine.",
    "low": {
      "label": "No marked sincere tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Sincere",
      "meaning": "Tries to make expressed appreciation or apology genuine."
    }
  },
  {
    "key": "facet-manipulative",
    "sides": "one",
    "family": "Trust and integrity",
    "profile": "relational",
    "meaning": "Tries to shape another's choices through selective framing and pressure.",
    "low": {
      "label": "No marked manipulative tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Manipulative",
      "meaning": "Tries to shape another's choices through selective framing and pressure."
    }
  },
  {
    "key": "facet-guarded",
    "sides": "one",
    "family": "Trust and integrity",
    "profile": "relational",
    "meaning": "Protects personal intentions or vulnerabilities until confidence is earned.",
    "low": {
      "label": "No marked guarded tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Guarded",
      "meaning": "Protects personal intentions or vulnerabilities until confidence is earned."
    }
  },
  {
    "key": "facet-fair-minded",
    "sides": "one",
    "family": "Rules and flexibility",
    "profile": "cognition",
    "meaning": "Wants like cases treated consistently under a defensible rule.",
    "low": {
      "label": "No marked fair minded tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Fair-minded",
      "meaning": "Wants like cases treated consistently under a defensible rule."
    }
  },
  {
    "key": "facet-arbitrary",
    "sides": "one",
    "family": "Rules and flexibility",
    "profile": "cognition",
    "meaning": "Often favors case-specific discretion over consistency.",
    "low": {
      "label": "No marked arbitrary tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Arbitrary",
      "meaning": "Often favors case-specific discretion over consistency."
    }
  },
  {
    "key": "facet-fickle",
    "sides": "one",
    "family": "Rules and flexibility",
    "profile": "cognition",
    "meaning": "Changes preferences or allegiances without strong new reasons.",
    "low": {
      "label": "No marked fickle tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Fickle",
      "meaning": "Changes preferences or allegiances without strong new reasons."
    }
  },
  {
    "key": "facet-zealous",
    "sides": "one",
    "family": "Rules and flexibility",
    "profile": "cognition",
    "meaning": "Pursues an explicitly held conviction with unusual intensity.",
    "low": {
      "label": "No marked zealous tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Zealous",
      "meaning": "Pursues an explicitly held conviction with unusual intensity."
    }
  },
  {
    "key": "facet-argumentative",
    "sides": "one",
    "family": "Conflict and repair",
    "profile": "pressure",
    "meaning": "Often treats discussion as a contest over who is correct.",
    "low": {
      "label": "No marked argumentative tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Argumentative",
      "meaning": "Often treats discussion as a contest over who is correct."
    }
  },
  {
    "key": "facet-mediating",
    "sides": "one",
    "family": "Conflict and repair",
    "profile": "pressure",
    "meaning": "Intervenes to help other parties resolve their dispute.",
    "low": {
      "label": "No marked mediating tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Mediating",
      "meaning": "Intervenes to help other parties resolve their dispute."
    }
  },
  {
    "key": "facet-forgiving",
    "sides": "one",
    "family": "Conflict and repair",
    "profile": "pressure",
    "meaning": "Lets a recognized repair reduce the weight of a grievance.",
    "low": {
      "label": "No marked forgiving tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Forgiving",
      "meaning": "Lets a recognized repair reduce the weight of a grievance."
    }
  },
  {
    "key": "facet-vindictive",
    "sides": "one",
    "family": "Conflict and repair",
    "profile": "pressure",
    "meaning": "Keeps a grievance salient and seeks a way to answer it.",
    "low": {
      "label": "No marked vindictive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Vindictive",
      "meaning": "Keeps a grievance salient and seeks a way to answer it."
    }
  },
  {
    "key": "facet-defensive",
    "sides": "one",
    "family": "Conflict and repair",
    "profile": "pressure",
    "meaning": "Responds to perceived criticism by protecting self-image.",
    "low": {
      "label": "No marked defensive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Defensive",
      "meaning": "Responds to perceived criticism by protecting self-image."
    }
  },
  {
    "key": "facet-hostile",
    "sides": "one",
    "family": "Conflict and repair",
    "profile": "pressure",
    "meaning": "Often begins an exchange with antagonistic intent.",
    "low": {
      "label": "No marked hostile tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Hostile",
      "meaning": "Often begins an exchange with antagonistic intent."
    }
  },
  {
    "key": "facet-thrill-seeking",
    "sides": "one",
    "family": "Pacing and risk",
    "profile": "pressure",
    "meaning": "Values stimulation and excitement in available choices.",
    "low": {
      "label": "No marked thrill seeking tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Thrill-seeking",
      "meaning": "Values stimulation and excitement in available choices."
    }
  },
  {
    "key": "facet-calm",
    "sides": "one",
    "family": "Emotional style",
    "profile": "pressure",
    "meaning": "Shows relatively measured immediate reactions.",
    "low": {
      "label": "No marked calm tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Calm",
      "meaning": "Shows relatively measured immediate reactions."
    }
  },
  {
    "key": "facet-hot-headed",
    "sides": "one",
    "family": "Emotional style",
    "profile": "pressure",
    "meaning": "Escalates quickly when a relevant frustration is perceived.",
    "low": {
      "label": "No marked hot headed tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Hot-headed",
      "meaning": "Escalates quickly when a relevant frustration is perceived."
    }
  },
  {
    "key": "facet-sensitive",
    "sides": "one",
    "family": "Emotional style",
    "profile": "pressure",
    "meaning": "Reacts strongly to personally meaningful social cues.",
    "low": {
      "label": "No marked sensitive tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Sensitive",
      "meaning": "Reacts strongly to personally meaningful social cues."
    }
  },
  {
    "key": "facet-tender-hearted",
    "sides": "one",
    "family": "Emotional style",
    "profile": "pressure",
    "meaning": "Responds to interpersonal hurt more with sorrow than anger.",
    "low": {
      "label": "No marked tender hearted tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Tender-hearted",
      "meaning": "Responds to interpersonal hurt more with sorrow than anger."
    }
  },
  {
    "key": "facet-excitable",
    "sides": "one",
    "family": "Emotional outlook",
    "profile": "appraisal",
    "meaning": "Readily shows enthusiasm for newly encountered opportunities.",
    "low": {
      "label": "No marked excitable tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Excitable",
      "meaning": "Readily shows enthusiasm for newly encountered opportunities."
    }
  },
  {
    "key": "facet-light-hearted",
    "sides": "one",
    "family": "Emotional outlook",
    "profile": "appraisal",
    "meaning": "Keeps relatively minor setbacks in proportion.",
    "low": {
      "label": "No marked light hearted tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Light-hearted",
      "meaning": "Keeps relatively minor setbacks in proportion."
    }
  },
  {
    "key": "facet-restless",
    "sides": "one",
    "family": "Emotional outlook",
    "profile": "appraisal",
    "meaning": "Becomes dissatisfied with prolonged unvaried activity.",
    "low": {
      "label": "No marked restless tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Restless",
      "meaning": "Becomes dissatisfied with prolonged unvaried activity."
    }
  },
  {
    "key": "facet-even-tempered",
    "sides": "one",
    "family": "Emotional outlook",
    "profile": "appraisal",
    "meaning": "Returns from ordinary irritation without prolonged escalation.",
    "low": {
      "label": "No marked even tempered tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Even-tempered",
      "meaning": "Returns from ordinary irritation without prolonged escalation."
    }
  },
  {
    "key": "facet-brooding",
    "sides": "one",
    "family": "Emotional outlook",
    "profile": "appraisal",
    "meaning": "Revisits personally significant unpleasant events after the moment passes.",
    "low": {
      "label": "No marked brooding tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Brooding",
      "meaning": "Revisits personally significant unpleasant events after the moment passes."
    }
  },
  {
    "key": "facet-affectionate",
    "sides": "one",
    "family": "Attachment and closeness",
    "profile": "relational",
    "meaning": "Frequently expresses warmth toward established loved ones.",
    "low": {
      "label": "No marked affectionate tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Affectionate",
      "meaning": "Frequently expresses warmth toward established loved ones."
    }
  },
  {
    "key": "facet-closeness-seeking",
    "sides": "one",
    "family": "Attachment and closeness",
    "profile": "relational",
    "meaning": "Places high value on reassurance and shared time in close bonds.",
    "low": {
      "label": "No marked closeness seeking tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Closeness-seeking",
      "meaning": "Places high value on reassurance and shared time in close bonds."
    }
  },
  {
    "key": "facet-intimacy-guarded",
    "sides": "one",
    "family": "Attachment and closeness",
    "profile": "relational",
    "meaning": "Keeps distance when a relationship becomes emotionally close.",
    "low": {
      "label": "No marked intimacy guarded tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Intimacy-guarded",
      "meaning": "Keeps distance when a relationship becomes emotionally close."
    }
  },
  {
    "key": "facet-devoted",
    "sides": "one",
    "family": "Attachment and closeness",
    "profile": "relational",
    "meaning": "Frequently prioritizes an established close commitment.",
    "low": {
      "label": "No marked devotion",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Devoted",
      "meaning": "Frequently prioritizes an established close commitment."
    }
  },
  {
    "key": "facet-nostalgic",
    "sides": "one",
    "family": "Attachment and closeness",
    "profile": "relational",
    "meaning": "Frequently revisits meaningful earlier relationships and experiences.",
    "low": {
      "label": "No marked nostalgia",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Nostalgic",
      "meaning": "Frequently revisits meaningful earlier relationships and experiences."
    }
  },
  {
    "key": "facet-teasing",
    "sides": "one",
    "family": "Attachment and closeness",
    "profile": "relational",
    "meaning": "Uses playful challenge as an established style of closeness.",
    "low": {
      "label": "No marked teasing tendency",
      "meaning": "This particular marked pattern is not established. This does NOT establish the opposite virtue, vice, capacity or emotion."
    },
    "high": {
      "label": "Teasing",
      "meaning": "Uses playful challenge as an established style of closeness."
    }
  }
];
