/** Generated from the existing municipal readings by scripts/source/export-town-council-profile-inputs.ts. */
export const TOWN_COUNCIL_PROFILE_INPUTS = {
  "gus2025:100091": {
    bodyName: "Council",
    bodySize: 9,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:106079": {
    bodyName: "Worcester City Council",
    bodySize: 11,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:106897": {
    bodyName: "Duluth City Council",
    bodySize: 9,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:109096": {
    bodyName: "Trenton City Council",
    bodySize: 7,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:109329": {
    bodyName: "Governing Body",
    bodySize: 8,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:110222": {
    bodyName: null,
    bodySize: 7,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:115492": {
    bodyName: null,
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:122711": {
    bodyName: null,
    bodySize: 6,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:124038": {
    bodyName: null,
    bodySize: 20,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:124214": {
    bodyName: "Council of the District of Columbia",
    bodySize: 13,
    form: null,
    evidence: "enacted-text",
  },
  "gus2025:124438": {
    bodyName: "Savannah Mayor and Aldermen",
    bodySize: 9,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:127810": {
    bodyName: "Council",
    bodySize: 7,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:128028": {
    bodyName: "City Council",
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:133602": {
    bodyName: null,
    bodySize: 17,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:136562": {
    bodyName: null,
    bodySize: 15,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:136964": {
    bodyName: null,
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:160683": {
    bodyName: "Council",
    bodySize: 7,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:160840": {
    bodyName: "Mayor and Council",
    bodySize: 6,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:161064": {
    bodyName: "Fort Smith Board of Directors",
    bodySize: 7,
    form: "OTHER",
    evidence: "research-transcription",
  },
  "gus2025:161529": {
    bodyName: "Wilmington City Council",
    bodySize: 13,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:161650": {
    bodyName: "City Commission",
    bodySize: 5,
    form: "COMMISSION_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:162013": {
    bodyName: null,
    bodySize: 7,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:162035": {
    bodyName: "Boise City Council",
    bodySize: 6,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:162037": {
    bodyName: "Council",
    bodySize: 6,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:162629": {
    bodyName: null,
    bodySize: 10,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:163465": {
    bodyName: "Council",
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:164452": {
    bodyName: "Iowa City City Council",
    bodySize: 7,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:165831": {
    bodyName: "Urban County Council",
    bodySize: 15,
    form: "URBAN_COUNTY_CONSOLIDATED",
    evidence: "research-transcription",
  },
  "gus2025:165866": {
    bodyName: "Louisville Metro Council",
    bodySize: 26,
    form: "METRO_CONSOLIDATED",
    evidence: "research-transcription",
  },
  "gus2025:166094": {
    bodyName: "New Orleans City Council",
    bodySize: 7,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:166159": {
    bodyName: "Council",
    bodySize: 7,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:166160": {
    bodyName: "Council",
    bodySize: 9,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:166166": {
    bodyName: "Bangor City Council",
    bodySize: 9,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:166690": {
    bodyName: null,
    bodySize: 8,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:167605": {
    bodyName: null,
    bodySize: 7,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:168896": {
    bodyName: "Council",
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:169464": {
    bodyName: "City Council",
    bodySize: 12,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:169988": {
    bodyName: "City Council",
    bodySize: 6,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:169993": {
    bodyName: "Reno City Council",
    bodySize: 7,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:170001": {
    bodyName: "Board of Mayor and Aldermen",
    bodySize: 15,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:170378": {
    bodyName: null,
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:171305": {
    bodyName: null,
    bodySize: 7,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:175728": {
    bodyName: null,
    bodySize: 40,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:176546": {
    bodyName: null,
    bodySize: 12,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:176966": {
    bodyName: null,
    bodySize: 11,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:177842": {
    bodyName: "Laramie City Council",
    bodySize: 9,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:183701": {
    bodyName: "Honolulu City Council",
    bodySize: 9,
    form: "CITY_COUNTY_CONSOLIDATED",
    evidence: "research-transcription",
  },
  "gus2025:184191": {
    bodyName: "City Council",
    bodySize: 10,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:184216": {
    bodyName: null,
    bodySize: 6,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:184856": {
    bodyName: null,
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:189877": {
    bodyName: null,
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:193734": {
    bodyName: "City Council",
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:194177": {
    bodyName: "Council of the City of Charlottesville",
    bodySize: 5,
    form: "COUNCIL_MANAGER",
    evidence: "enacted-text",
  },
  "gus2025:194178": {
    bodyName: "Council of the City of Richmond",
    bodySize: 9,
    form: "MAYOR_COUNCIL",
    evidence: "enacted-text",
  },
  "gus2025:194463": {
    bodyName: "Anchorage Assembly",
    bodySize: 12,
    form: "CITY_COUNTY_CONSOLIDATED",
    evidence: "research-transcription",
  },
  "gus2025:194647": {
    bodyName: "Denver City Council",
    bodySize: 13,
    form: "CITY_COUNTY_CONSOLIDATED",
    evidence: "research-transcription",
  },
  "gus2025:194679": {
    bodyName: "Commission",
    bodySize: 10,
    form: "CITY_COUNTY_CONSOLIDATED",
    evidence: "research-transcription",
  },
  "gus2025:194805": {
    bodyName: null,
    bodySize: 51,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:194943": {
    bodyName: "Carson City Board of Supervisors",
    bodySize: 5,
    form: "CITY_COUNTY_CONSOLIDATED",
    evidence: "enacted-text",
  },
  "gus2025:201810": {
    bodyName: "Governing Body",
    bodySize: 7,
    form: "OTHER",
    evidence: "research-transcription",
  },
  "gus2025:204917": {
    bodyName: "City Council",
    bodySize: 15,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:207536": {
    bodyName: "Phoenix City Council",
    bodySize: 9,
    form: "COUNCIL_MANAGER",
    evidence: "research-transcription",
  },
  "gus2025:208246": {
    bodyName: "Baltimore City Council",
    bodySize: 15,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:208744": {
    bodyName: "Enfield Town Meeting",
    bodySize: null,
    form: "TOWN_MEETING",
    evidence: "research-transcription",
  },
  "gus2025:209050": {
    bodyName: "Columbus City Council",
    bodySize: 9,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:209170": {
    bodyName: null,
    bodySize: 8,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:209465": {
    bodyName: null,
    bodySize: 8,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:209777": {
    bodyName: null,
    bodySize: 20,
    form: null,
    evidence: "research-transcription",
  },
  "gus2025:211254": {
    bodyName: "City Council",
    bodySize: 12,
    form: null,
    evidence: "enacted-text",
  },
  "gus2025:211708": {
    bodyName: "Common Council",
    bodySize: 9,
    form: "MAYOR_COUNCIL",
    evidence: "research-transcription",
  },
  "gus2025:212021": {
    bodyName: "Board of Commissioners",
    bodySize: 5,
    form: "COMMISSION_MANAGER",
    evidence: "research-transcription",
  },
} as const;
