/** Compile locked Census bulk selections into the browser-safe population layer.
 * Run: node --import tsx scripts/world/compile-place-demographics.ts <selection-dir>
 * The selections retain original Census headers and are verified against receipts.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { join, basename } from "node:path";

interface CompiledDemographics {
  columns: string[];
  sources: unknown[];
  rows: (string | number | null)[][];
  annualSource: unknown;
  annualRows: (string | number)[][];
  territoryRows: unknown[];
  decennialRows: (string | number | null)[][];
  decennialSources: unknown[];
  stateKeys: Record<string, string>;
}
function render(output: CompiledDemographics): string {
  const packed = (rows: (string | number | null)[][]) =>
    JSON.stringify(
      rows.map((row) => row.map((value) => value ?? "").join(",")).join(";"),
    );
  return `/** GENERATED by scripts/world/compile-place-demographics.ts. Normalized source rows and receipts: data/research/census/place-demographics-2024.json. */\nexport const PLACE_DEMOGRAPHIC_COLUMNS = ${JSON.stringify(output.columns)} as const;\nexport const PLACE_DEMOGRAPHIC_SOURCES = ${JSON.stringify(output.sources)} as const;\n/** GEOID,vintage,then columns; empty cells are suppressed or unavailable, never zero. */\nexport const PLACE_DEMOGRAPHIC_ROWS: string = ${packed(output.rows)};\nexport const ANNUAL_POPULATION_SOURCE = ${JSON.stringify(output.annualSource)} as const;\nexport const ANNUAL_POPULATION_ROWS: string = ${packed(output.annualRows)};\nexport const TERRITORY_POPULATION_ROWS = ${JSON.stringify(output.territoryRows)} as const;\nexport const DECENNIAL_POPULATION_ROWS: string = ${packed(output.decennialRows)};\nexport const DECENNIAL_POPULATION_SOURCES = ${JSON.stringify(output.decennialSources)} as const;\nexport const STATE_POPULATION_KEYS: Readonly<Record<string,string>> = ${JSON.stringify(output.stateKeys)};\n`;
}
const input = process.argv[2];
if (!input || input === "--replay" || input === "--check") {
  const output = JSON.parse(
    readFileSync("data/research/census/place-demographics-2024.json", "utf8"),
  ) as CompiledDemographics;
  const path =
    "src/simulation/nationwide-world/place-demographics.generated.ts";
  const generated = render(output);
  if (input === "--check") {
    if (readFileSync(path, "utf8") !== generated)
      throw new Error(
        "Generated Census bytes do not match their normalized source packet.",
      );
    console.log(
      `Verified replay bytes for ${output.rows.length} normalized Census rows.`,
    );
  } else {
    writeFileSync(path, generated);
    console.log(`Replayed ${output.rows.length} normalized Census rows.`);
  }
  process.exit(0);
}
const selectionDirectory: string = input;
const hash = (bytes: Buffer | string) =>
  createHash("sha256").update(bytes).digest("hex");
interface Receipt {
  url: string;
  year: number;
  table: string;
  sourceSha256: string;
  selectedSha256: string;
  path: string;
}
const receipts: Receipt[] = [
  ...JSON.parse(readFileSync(join(input, "manifest.json"), "utf8")),
  ...JSON.parse(readFileSync(join(input, "language-manifest.json"), "utf8")),
];
const tables = new Map<string, Map<string, (number | null)[]>>();
for (const receipt of receipts) {
  const bytes = readFileSync(receipt.path);
  if (hash(bytes) !== receipt.selectedSha256)
    throw new Error(`Selection digest mismatch: ${receipt.path}`);
  const [header, ...lines] = bytes.toString("utf8").trim().split(/\r?\n/);
  const fields = header!.split("|");
  const estimates = fields.flatMap((field, index) =>
    /_E\d+$/.test(field) ? [index] : [],
  );
  const rows = new Map<string, (number | null)[]>();
  for (const line of lines) {
    const cells = line.split("|");
    const id = cells[0]!.split("US")[1]!;
    rows.set(
      id,
      estimates.map((index) => {
        const value = Number(cells[index]);
        return cells[index] === "" || !Number.isFinite(value) || value < 0
          ? null
          : value;
      }),
    );
  }
  tables.set(`${receipt.year}:${receipt.table}`, rows);
}
const read = (year: number, table: string, id: string, cell: number) =>
  tables.get(`${year}:${table}`)?.get(id)?.[cell - 1] ?? null;
const ids = [...tables.get("2024:b01001")!.keys()].sort();
const sum = (table: string, id: string, cells: number[]) => {
  const values = cells.map((cell) => read(2024, table, id, cell));
  return values.some((value) => value === null)
    ? null
    : values.reduce<number>((total, value) => total + value!, 0);
};
const age = (id: string, start: number, end: number) =>
  sum(
    "b01001",
    id,
    Array.from({ length: end - start + 1 }, (_, i) => start + i).flatMap(
      (cell) => [cell, cell + 24],
    ),
  );
const columns = [
  "population",
  "households",
  "under18",
  "age18to24",
  "age25to44",
  "age45to61",
  "age62plus",
  "age16plus",
  "laborForce",
  "employed",
  "unemployed",
  "white",
  "black",
  "americanIndian",
  "asian",
  "pacificIslander",
  "otherRace",
  "multipleRaces",
  "hispanic",
  "englishOnly",
  "languageTotal",
  "owners",
  "renters",
  "population2023",
  "marriedCoupleHouseholds",
  "maleFamilyHeadHouseholds",
  "femaleFamilyHeadHouseholds",
  "aloneHouseholds",
  "housemateHouseholds",
];
const rows = ids.map((id) => [
  id,
  2024,
  read(2024, "b01001", id, 1),
  read(2024, "b11001", id, 1),
  age(id, 3, 6),
  age(id, 7, 10),
  age(id, 11, 14),
  age(id, 15, 18),
  age(id, 19, 25),
  read(2024, "b23025", id, 1),
  read(2024, "b23025", id, 3),
  read(2024, "b23025", id, 4),
  read(2024, "b23025", id, 5),
  ...[2, 3, 4, 5, 6, 7, 8].map((cell) => read(2024, "b02001", id, cell)),
  read(2024, "b03003", id, 3),
  read(2024, "c16001", id, 2),
  read(2024, "c16001", id, 1),
  read(2024, "b25003", id, 2),
  read(2024, "b25003", id, 3),
  read(2023, "b01001", id, 1),
  ...[3, 5, 6, 8, 9].map((cell) => read(2024, "b11001", id, cell)),
]);
const sources = receipts.map(
  ({ url, year, table, sourceSha256, selectedSha256 }) => ({
    url,
    year,
    table,
    sourceSha256,
    selectedSha256,
  }),
);
const annualReceipt = JSON.parse(
  readFileSync(join(input, "sub-est2025.receipt.json"), "utf8"),
);
const annualBytes = readFileSync(annualReceipt.path);
if (hash(annualBytes) !== annualReceipt.sha256)
  throw new Error("Annual population digest mismatch.");
const parseCsv = (line: string): string[] => {
  const cells: string[] = [];
  let cell = "";
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i]!;
    if (c === '"' && quoted && line[i + 1] === '"') {
      cell += c;
      i++;
    } else if (c === '"') quoted = !quoted;
    else if (c === "," && !quoted) {
      cells.push(cell);
      cell = "";
    } else cell += c;
  }
  cells.push(cell);
  return cells;
};
const annualLines = annualBytes.toString("latin1").trim().split(/\r?\n/);
const annualHeader = parseCsv(annualLines[0]!);
const annualRows = annualLines.slice(1).flatMap((line) => {
  const cells = parseCsv(line);
  if (!["040", "162"].includes(cells[0]!)) return [];
  const id = cells[0] === "040" ? cells[1]! : cells[1]! + cells[3]!;
  return [
    [
      id,
      ...Array.from({ length: 6 }, (_, i) =>
        Number(cells[annualHeader.indexOf(`POPESTIMATE${2020 + i}`)]),
      ),
    ],
  ];
});
const islandSources = JSON.parse(
  readFileSync(join(input, "islands-manifest.json"), "utf8"),
).flat();
interface IslandMatch {
  key: string;
  scope: string;
  status: string;
  allowedEstimateCandidate?: {
    value: number;
    method: string;
    denominator: number;
  };
  candidates: {
    name: string;
    population2020: number;
    population2010?: number;
    sourceFile: string;
    sourceSha256: string;
  }[];
}
interface IslandDemographicRow {
  key: string;
  status: string;
  logrecno?: string;
  fields: Record<string, number | null | Record<string, number | null>>;
  fieldSources: Record<string, unknown>;
}
const islandDemographics = JSON.parse(
  readFileSync(join(input, "island-demographic-normalized.json"), "utf8"),
) as {
  receipts: { path: string; sha256: string; url?: string }[];
  rows: IslandDemographicRow[];
  limits: string[];
};
const islandRecords = new Map<string, Map<string, string[]>>();
for (const receipt of islandDemographics.receipts) {
  const bytes = readFileSync(receipt.path);
  if (hash(bytes) !== receipt.sha256)
    throw new Error(`Island demographic digest mismatch: ${receipt.path}`);
  if (receipt.path.endsWith(".dp"))
    islandRecords.set(
      receipt.path,
      new Map(
        bytes
          .toString("utf8")
          .trim()
          .split(/\r?\n/)
          .map((line) => {
            const cells = line.split("|");
            return [cells[4]!, cells];
          }),
      ),
    );
}
function verifyIslandCells(value: unknown, row: IslandDemographicRow): void {
  if (!value || typeof value !== "object") return;
  const cell = value as {
    pipeColumn1based?: number;
    segment?: number;
    sourcePath?: string;
    raw?: string;
  };
  if (cell.pipeColumn1based) {
    const country = row.key.split(":")[1]!.toLowerCase();
    const file =
      cell.sourcePath ??
      join(selectionDirectory, `${country}0000${cell.segment}2020.dp`);
    const raw = islandRecords.get(file)?.get(row.logrecno!)?.[
      cell.pipeColumn1based - 1
    ];
    if (raw !== cell.raw)
      throw new Error(
        `Island demographic cell mismatch: ${row.key} ${file} column ${cell.pipeColumn1based}`,
      );
  } else for (const item of Object.values(value)) verifyIslandCells(item, row);
}
for (const row of islandDemographics.rows)
  if (row.status === "decoded") verifyIslandCells(row.fieldSources, row);
const portableIslandProof = JSON.parse(
  JSON.stringify(islandDemographics, (key, value) =>
    (key === "path" || key === "sourcePath" || key === "fieldLayout") &&
    typeof value === "string"
      ? basename(value)
      : value,
  ),
);
const ownPlaceAnchors = JSON.parse(
  readFileSync(join(input, "own-place-resolution-2020.json"), "utf8"),
) as {
  rows: {
    key: string;
    relatedOwnNameSourceRecords: {
      name: string;
      summaryLevel: string;
      geoId: string;
      logrecno: string;
      fields: Record<
        string,
        {
          value: number;
          raw: string;
          path: string;
          sha256: string;
          pipeColumn1based: number;
        }
      >;
    }[];
  }[];
};
for (const row of ownPlaceAnchors.rows) {
  for (const record of row.relatedOwnNameSourceRecords) {
    for (const cell of Object.values(record.fields)) {
      const bytes = readFileSync(cell.path);
      if (
        hash(bytes) !== cell.sha256 ||
        islandRecords.get(cell.path)?.get(record.logrecno)?.[
          cell.pipeColumn1based - 1
        ] !== cell.raw ||
        Number(cell.raw) !== cell.value
      )
        throw new Error(`Calibration anchor cell mismatch: ${row.key}`);
    }
  }
}
const territoryRows = (
  JSON.parse(
    readFileSync(join(input, "territory-key-crosswalk.json"), "utf8"),
  ) as IslandMatch[]
).map((row) => {
  const candidate = row.candidates[0];
  const receipt =
    candidate &&
    islandSources.find(
      (item: { path: string }) => item.path === candidate.sourceFile,
    );
  if (
    candidate &&
    (!receipt ||
      hash(readFileSync(candidate.sourceFile)) !== candidate.sourceSha256)
  )
    throw new Error(`Island source digest mismatch: ${row.key}`);
  const demographic = islandDemographics.rows.find(
    (item) => item.key === row.key && item.status === "decoded",
  );
  const fields = demographic?.fields;
  const race = fields?.raceAlone as Record<string, number | null> | undefined;
  const demographicCounts = fields
    ? {
        ...fields,
        under18:
          typeof fields.population === "number" &&
          typeof fields.adults === "number"
            ? fields.population - fields.adults
            : null,
        americanIndian: race?.native ?? null,
        pacificIslander: race?.pacific ?? null,
        otherRace: race?.other ?? null,
        multipleRaces: race?.multiple ?? null,
        white: race?.white ?? null,
        black: race?.black ?? null,
        asian: race?.asian ?? null,
      }
    : null;
  return {
    key: row.key,
    demographicCounts,
    scope: row.scope,
    status: row.status,
    population: candidate?.population2020 ?? null,
    previousPopulation: candidate?.population2010 ?? null,
    name: candidate?.name ?? null,
    source: receipt?.url ?? null,
    sourceSha256: candidate?.sourceSha256 ?? null,
    calibrationAnchor: (() => {
      const records = ownPlaceAnchors.rows.find(
        (item) => item.key === row.key,
      )?.relatedOwnNameSourceRecords;
      if (!records?.length) return null;
      const sum = (field: string) =>
        records.reduce(
          (total, record) => total + record.fields[field]!.value,
          0,
        );
      return {
        kind: records.length === 1 ? "county-mcd-proxy" : "component-sum",
        observationOfGameGeography: false,
        population: sum("population"),
        households: sum("households"),
        laborForce: sum("civilianLaborForce"),
        employed: sum("employed"),
        adults: sum("adults18plus"),
        records: JSON.parse(
          JSON.stringify(records, (key, value) =>
            key === "path" && typeof value === "string"
              ? basename(value)
              : value,
          ),
        ),
      };
    })(),
    estimate: null,
    vintage: 2020,
  };
});
const decennialReceipts = [
  ...JSON.parse(readFileSync(join(input, "tiger2020-manifest.json"), "utf8")),
  ...JSON.parse(
    readFileSync(join(input, "tiger2020-state-county-manifest.json"), "utf8"),
  ),
];
const decennialRows: (string | number | null)[][] = [];
const stateKeys: Record<string, string> = {};
for (const receipt of decennialReceipts) {
  const bytes = readFileSync(receipt.path);
  if (
    hash(bytes) !== receipt.sha256 ||
    receipt.exceededTransferLimit ||
    receipt.error
  )
    throw new Error("Decennial source digest/truncation failure.");
  const sourceRows = JSON.parse(bytes.toString("utf8")).features;
  for (const item of sourceRows) {
    const row = item.attributes;
    decennialRows.push([
      row.GEOID,
      row.POP100 === null ? null : Number(row.POP100),
      row.HU100 === null ? null : Number(row.HU100),
    ]);
    if (row.STUSAB && row.GEOID.length === 2) stateKeys[row.STUSAB] = row.GEOID;
  }
}
const islandProfiles = JSON.parse(
  readFileSync(join(input, "island-geoid-population.json"), "utf8"),
) as { summaryLevel: string; geoId: string; population2020: number }[];
for (const row of decennialRows) {
  if (row[1] !== null) continue;
  const profile = islandProfiles.find(
    (item) =>
      item.summaryLevel === (String(row[0]).length === 2 ? "040" : "050") &&
      item.geoId.endsWith(`US${row[0]}`),
  );
  if (profile) row[1] = profile.population2020;
}
const decennialSources = decennialReceipts.map(
  ({ url, sha256 }: { url: string; sha256: string }) => ({
    url,
    sha256,
    vintage: 2020,
  }),
);
const annualSource = {
  url: annualReceipt.url,
  sha256: annualReceipt.sha256,
  vintage: 2025,
  encoding: "latin1",
};
const output = {
  schema: "census-place-demographics-v1",
  columns,
  sources,
  rows,
  annualSource,
  annualRows,
  territoryRows,
  decennialRows,
  decennialSources,
  stateKeys,
  islandDemographicProof: portableIslandProof,
};
mkdirSync("data/research/census", { recursive: true });
writeFileSync(
  "data/research/census/place-demographics-2024.json",
  JSON.stringify(output) + "\n",
);
writeFileSync(
  "src/simulation/nationwide-world/place-demographics.generated.ts",
  render(output),
);
console.log(
  `Compiled ${rows.length} state, county and place rows from hash-verified Census selections.`,
);
