import fs from "fs";
import path from "path";

import {
  ARM_MEASUREMENT_TOOL,
  ARM_SIDES,
  measureArms,
  renderArmOverlaySvg,
  type ArmMeasurementEntry,
} from "./arm-measure";
import {
  ARM_MEASUREMENT_OVERLAY_DIRECTORY,
  ARM_MEASUREMENT_REPORT_PATH,
  collectArmSubjects,
} from "./arm-measure-subjects";
import { writeFormatted } from "./write-formatted";

/**
 * Measures every body raster the repository can name, per side and per pose,
 * and writes the report and one review overlay per body.
 *
 * `npm run measure:arms`. The report is checked in and regenerated by test,
 * so the numbers a fit derivation reads are the numbers a reviewer can open,
 * and a raster that changes changes the report in the same commit.
 */

const repositoryRoot = path.resolve(process.cwd());

export interface ArmMeasurementReport {
  readonly tool: string;
  readonly note: string;
  readonly sideConvention: string;
  readonly statuses: Readonly<Record<string, string>>;
  readonly subjects: readonly (ArmMeasurementEntry & {
    readonly overlay: string;
    readonly sha256MatchesSourceRecord: boolean | null;
  })[];
}

const subjects = collectArmSubjects(repositoryRoot);
const entries = subjects.map((subject) => {
  const entry = measureArms(subject, subject.absoluteFile);
  const overlay = `${ARM_MEASUREMENT_OVERLAY_DIRECTORY}/${subject.assetId}.svg`;
  const overlayPath = path.join(repositoryRoot, overlay);
  fs.mkdirSync(path.dirname(overlayPath), { recursive: true });
  const href = path
    .relative(path.dirname(overlayPath), subject.absoluteFile)
    .split(path.sep)
    .join("/");
  fs.writeFileSync(overlayPath, renderArmOverlaySvg(entry, href), "utf8");
  return {
    ...entry,
    overlay,
    sha256MatchesSourceRecord:
      subject.expectedSha256 === null
        ? null
        : subject.expectedSha256 === entry.sha256,
  };
});

const report: ArmMeasurementReport = {
  tool: ARM_MEASUREMENT_TOOL,
  note: "Arm landmarks, segments and cross-sections read from the alpha of each body raster, per image side, keyed by body family and pose family. A value is present only where the silhouette contains it: rows where the arm lies against the torso are FUSED and every inner measurement over them is occluded, not estimated. Sides are never mirrored and poses are never substituted. Regenerate with `npm run measure:arms`; the numbers are reproducible from the rasters.",
  sideConvention:
    "Sides are IMAGE sides: 'left' is the smaller x, matching the pose registry's shoulder-left / shoulder-right landmarks. A front-facing figure's image-left arm is its anatomical right; facing is not inferred here.",
  statuses: {
    measured:
      "Read from the silhouette (a stated rule where evidence says silhouette-rule).",
    "partially-measured":
      "Locates a region rather than a joint, or one endpoint of a segment is only partially located.",
    ambiguous:
      "The silhouette was read and did not decide the question. No value.",
    occluded:
      "The edge is not in the alpha because the arm lies against the torso or is hidden. No value.",
    unavailable: "A prerequisite was missing. No value.",
  },
  subjects: entries,
};

await writeFormatted(
  path.join(repositoryRoot, ARM_MEASUREMENT_REPORT_PATH),
  JSON.stringify(report, null, 2),
);

for (const entry of entries) {
  const sides = ARM_SIDES.map((side) => {
    const arm = entry.sides[side];
    return `${side} ${arm.status.padEnd(18)} sh ${arm.shoulder.status.padEnd(9)} el ${arm.elbow.status.padEnd(18)} wr ${arm.wrist.status.padEnd(9)} sep ${String(arm.separation.separatedRowCount).padStart(4)}/${String(arm.separation.fusedRowCount).padStart(4)}`;
  });
  console.log(
    `${entry.assetId.padEnd(48)} ${entry.poseFamily.padEnd(24)}\n    ${sides.join("\n    ")}${entry.sha256MatchesSourceRecord === false ? "\n    WARNING: sha256 differs from the source record" : ""}`,
  );
}
console.log(
  `\nWrote ${ARM_MEASUREMENT_REPORT_PATH} and ${entries.length} overlays under ${ARM_MEASUREMENT_OVERLAY_DIRECTORY}`,
);
