import path from "path";

import { reconcileAssetReadiness } from "../../src/authoring/asset-readiness";
import { readAssetReadinessInputs } from "./asset-readiness-inputs";
import { writeFormatted } from "./write-formatted";

/**
 * Regenerates the asset readiness reconciliation.
 *
 * Run this before asking anybody to generate anything. It answers one question
 * in a form that can be checked: for each request still open, does art the
 * project already owns answer it, change what it may claim, or leave it alone.
 */

const root = path.resolve(process.cwd());
const inputs = readAssetReadinessInputs(root);
const report = reconcileAssetReadiness(
  inputs.requests.requests,
  inputs.declaration,
  inputs.preservedUnits,
  inputs.existingPaths,
);

const verdictsById = new Map(
  inputs.declaration.requestVerdicts.map((verdict) => [
    verdict.requestId,
    verdict,
  ]),
);
const statusById = new Map(
  inputs.requests.requests.map((request) => [request.requestId, request]),
);

const lines: string[] = [];
lines.push("# Asset readiness reconciliation");
lines.push("");
lines.push(
  "Generated by `npm run readiness:art`. Do not edit by hand; edit `art/requests/preserved-asset-reconciliation.json`.",
);
lines.push("");
lines.push(
  `Reconciled against **${inputs.declaration.reconciledAgainst.preservedEvidenceGeneration}** (merge \`${inputs.declaration.reconciledAgainst.mergeCommit}\`).`,
);
lines.push("");
lines.push(
  `- closed by a preserved asset: **${report.closedByPreservedAsset.length}**`,
);
lines.push(
  `- premise restated, still required: **${report.premiseRestated.length}**`,
);
lines.push(`- unaffected, still required: **${report.stillRequired.length}**`);
lines.push(
  `- preserved units answering no request: **${report.unlinkedPreservedUnits.length}** of ${inputs.preservedUnits.length}`,
);
lines.push("");
lines.push("## Open requests");
lines.push("");
lines.push("| Request | Priority | Status | Verdict |");
lines.push("| --- | --- | --- | --- |");
for (const [requestId, verdict] of [...verdictsById].sort()) {
  const request = statusById.get(requestId);
  lines.push(
    `| \`${requestId}\` | ${request?.priority ?? "?"} | ${request?.status ?? "?"} | ${verdict.verdict} |`,
  );
}
lines.push("");
for (const [requestId, verdict] of [...verdictsById].sort()) {
  lines.push(`### \`${requestId}\` — ${verdict.verdict}`);
  lines.push("");
  lines.push(verdict.reason);
  lines.push("");
  for (const evidencePath of verdict.evidencePaths) {
    lines.push(`- \`${evidencePath}\``);
  }
  if (verdict.evidencePaths.length > 0) lines.push("");
}
lines.push("## Preserved art no request asks for");
lines.push("");
for (const entry of inputs.declaration.unlinkedPreservedAssets) {
  lines.push(`### \`${entry.preservedUnit}\``);
  lines.push("");
  lines.push(entry.reason);
  lines.push("");
  lines.push(`**Next required action.** ${entry.nextRequiredAction}`);
  lines.push("");
}
if (report.findings.length > 0) {
  lines.push("## Findings");
  lines.push("");
  for (const finding of report.findings) {
    lines.push(
      `- \`${finding.code}\` **${finding.subject}** — ${finding.message}`,
    );
  }
  lines.push("");
}

await writeFormatted(
  path.join(root, "art/qa/asset_readiness.md"),
  lines.join("\n"),
);
await writeFormatted(
  path.join(root, "art/qa/asset_readiness.json"),
  JSON.stringify(
    {
      reconciledAgainst: inputs.declaration.reconciledAgainst,
      preservedUnits: inputs.preservedUnits,
      ...report,
    },
    null,
    2,
  ),
);

for (const finding of report.findings) {
  console.error(`${finding.code}: ${finding.subject} — ${finding.message}`);
}
console.log(
  `asset readiness: ${report.closedByPreservedAsset.length} closed by preserved art, ${report.premiseRestated.length} restated, ${report.stillRequired.length} unaffected, ${report.unlinkedPreservedUnits.length} preserved units unlinked.`,
);
process.exit(report.valid ? 0 : 1);
