import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * Turns the received personality dispositions into the build's catalog data.
 *
 * The source is ChatGPT's DEPTH2 answer A01,
 * `docs/research/chatgpt-answers/2026-09-22-depth2/personality-scale-dispositions.json`: all 121 researched
 * catalog ids resolved into 102 scales, 18 with two ends and 84 one-sided.
 * Four of the two-ended scales are exactly the build's own deliberation,
 * reliability, conflict and risk; the answer says to bind those to the
 * existing definitions rather than declare them twice, so they are left out
 * here and the five keep their meaning.
 *
 * Run `npx tsx scripts/traits/personality-catalogue.ts` to rewrite
 * `src/simulation/personality-catalogue.generated.ts`;
 * `tests/personality-catalogue-generated.test.ts` fails when the two disagree.
 *
 * **The wording is part of every save that holds a quality.** The save check
 * compares a stored definition with the pack's field for field, so a revised
 * label or meaning regenerated in place would make those saves refuse to
 * load. A revision of the received text belongs in a new pack version, not a
 * rewrite of `personality-v1`.
 */

const SOURCE = new URL(
  "../../docs/research/chatgpt-answers/2026-09-22-depth2/personality-scale-dispositions.json",
  import.meta.url,
);
const TARGET = new URL(
  "../../src/simulation/personality-catalogue.generated.ts",
  import.meta.url,
);

/** The received scales that are the build's own five under their own names. */
export const BOUND_TO_THE_FIVE = [
  "deliberation",
  "reliability",
  "conflict",
  "risk",
] as const;

/** Qualities retired by Lamontae's September 26 personality decision. */
export const RETIRED_QUALITIES = [
  "social-contact-preference",
  "ownership-of-duties",
  "facet-reserved",
  "facet-cheeky",
  "facet-distractible",
  "facet-even-tempered",
] as const;

const ABSORBED_MEANINGS: Readonly<Record<string, string>> = {
  "facet-calm":
    "Shows relatively measured immediate reactions and returns from ordinary irritation without prolonged escalation.",
  "facet-mischievous":
    "Looks for playful disruption, a low-stakes trick, or a playful test of small social boundaries.",
  "facet-daydreaming":
    "Attention sometimes turns inward to possibilities or shifts away from the current task.",
};

interface ReceivedEnd {
  readonly catalogue_id: string | null;
  readonly label: string;
  readonly meaning: string;
}

interface ReceivedScale {
  readonly key: string;
  readonly kind: "bipolar" | "one-sided-facet";
  readonly meaning: string;
  readonly low: ReceivedEnd;
  readonly high: ReceivedEnd;
  readonly tuning_profile: string;
}

interface ReceivedAssignment {
  readonly id: string;
  readonly family: string;
  readonly scale: string | null;
}

interface Received {
  readonly source_catalogue_sha256: string;
  readonly scales: readonly ReceivedScale[];
  readonly catalogue_assignments: readonly ReceivedAssignment[];
}

export function renderCatalogueData(text: string): string {
  const received = JSON.parse(text) as Received;
  const familyOf = new Map<string, string>();
  for (const assignment of received.catalogue_assignments) {
    if (assignment.scale && !familyOf.has(assignment.scale)) {
      familyOf.set(assignment.scale, assignment.family);
    }
  }
  const bound = new Set<string>([...BOUND_TO_THE_FIVE, ...RETIRED_QUALITIES]);
  const rows = received.scales
    .filter((scale) => !bound.has(scale.key))
    .map((scale) => ({
      key: scale.key,
      sides: scale.kind === "bipolar" ? "two" : "one",
      family: familyOf.get(scale.key) ?? "Unassigned",
      profile: scale.tuning_profile,
      meaning: ABSORBED_MEANINGS[scale.key] ?? scale.meaning,
      low: { label: scale.low.label, meaning: scale.low.meaning },
      high: { label: scale.high.label, meaning: scale.high.meaning },
    }));
  return [
    "// Generated by scripts/traits/personality-catalogue.ts from",
    "// docs/research/chatgpt-answers/2026-09-22-depth2/personality-scale-dispositions.json. Do not edit by hand.",
    `// Source catalog sha256 ${received.source_catalogue_sha256}.`,
    "",
    // british-spelling-ok: a module path in the generated file, not prose.
    'import type { CatalogueScale } from "./personality-catalogue";',
    "",
    `export const CATALOGUE_SCALES: readonly CatalogueScale[] = ${JSON.stringify(rows, null, 2)};`,
    "",
  ].join("\n");
}

export function catalogueSourceText(): string {
  return readFileSync(SOURCE, "utf8");
}

export function catalogueTargetPath(): string {
  return fileURLToPath(TARGET);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(TARGET, renderCatalogueData(catalogueSourceText()));
}
