import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/**
 * Turns the received personality dispositions into the build's catalogue data.
 *
 * The source is ChatGPT's DEPTH2 answer A01,
 * `docs/research/chatgpt-answers/2026-09-22-depth2/personality-scale-dispositions.json`: all 121 researched
 * catalogue ids resolved into 102 scales, 18 with two ends and 84 one-sided.
 * Four of the two-ended scales are exactly the build's own deliberation,
 * reliability, conflict and risk; the answer says to bind those to the
 * existing definitions rather than declare them twice, so they are left out
 * here and the five keep their meaning.
 *
 * Run `npx tsx scripts/traits/personality-catalogue.ts` to rewrite
 * `src/simulation/personality-catalogue.generated.ts`; a test fails when the two
 * disagree.
 */

const SOURCE = new URL(
  "../../docs/research/chatgpt-answers/2026-09-22-depth2/personality-scale-dispositions.json",
  import.meta.url,
);
const TARGET = new URL(
  "../../src/simulation/personality-catalogue.generated.ts",
  import.meta.url,
);

/** The received scales that are the build's own five under their own names. */
export const BOUND_TO_THE_FIVE = [
  "deliberation",
  "reliability",
  "conflict",
  "risk",
] as const;

interface ReceivedEnd {
  readonly catalogue_id: string | null;
  readonly label: string;
  readonly meaning: string;
}

interface ReceivedScale {
  readonly key: string;
  readonly kind: "bipolar" | "one-sided-facet";
  readonly meaning: string;
  readonly low: ReceivedEnd;
  readonly high: ReceivedEnd;
  readonly tuning_profile: string;
}

interface ReceivedAssignment {
  readonly id: string;
  readonly family: string;
  readonly scale: string | null;
}

interface Received {
  readonly source_catalogue_sha256: string;
  readonly scales: readonly ReceivedScale[];
  readonly catalogue_assignments: readonly ReceivedAssignment[];
}

export function renderCatalogueData(text: string): string {
  const received = JSON.parse(text) as Received;
  const familyOf = new Map<string, string>();
  for (const assignment of received.catalogue_assignments) {
    if (assignment.scale && !familyOf.has(assignment.scale)) {
      familyOf.set(assignment.scale, assignment.family);
    }
  }
  const bound = new Set<string>(BOUND_TO_THE_FIVE);
  const rows = received.scales
    .filter((scale) => !bound.has(scale.key))
    .map((scale) => ({
      key: scale.key,
      sides: scale.kind === "bipolar" ? "two" : "one",
      family: familyOf.get(scale.key) ?? "Unassigned",
      profile: scale.tuning_profile,
      meaning: scale.meaning,
      low: { label: scale.low.label, meaning: scale.low.meaning },
      high: { label: scale.high.label, meaning: scale.high.meaning },
    }));
  return [
    "// Generated by scripts/traits/personality-catalogue.ts from",
    "// docs/research/chatgpt-answers/2026-09-22-depth2/personality-scale-dispositions.json. Do not edit by hand.",
    `// Source catalogue sha256 ${received.source_catalogue_sha256}.`,
    "",
    'import type { CatalogueScale } from "./personality-catalogue";',
    "",
    `export const CATALOGUE_SCALES: readonly CatalogueScale[] = ${JSON.stringify(rows, null, 2)};`,
    "",
  ].join("\n");
}

export function catalogueSourceText(): string {
  return readFileSync(SOURCE, "utf8");
}

export function catalogueTargetPath(): string {
  return fileURLToPath(TARGET);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(TARGET, renderCatalogueData(catalogueSourceText()));
}
