/**
 * Contract tests for the compiled storm hazard catalog.
 *
 * The catalog is generated by `node scripts/world/compile-storm-events.mjs`
 * from publisher bytes pinned in `data/source/storm-events-2000-2024/`. These
 * tests do not re-derive it; they assert the properties a consumer is allowed
 * to rely on, and the one property the project cares about most — that no real
 * casualty, injury or loss figure has been carried into the game.
 *
 * The import attribute is required: the Playwright loader rejects a bare JSON
 * import.
 */
import { describe, expect, it } from "vitest";

import catalog from "./storm-catalog.generated.json" with { type: "json" };

const FAMILIES = ["flood", "flash-flood", "thunderstorm-wind"] as const;
type Family = (typeof FAMILIES)[number];

interface AffectedArea {
  readonly stateFips: string;
  readonly countyFips: string;
  readonly czType: string;
  readonly czName?: string;
}

interface Episode {
  readonly episodeId: string;
  readonly family: string;
  readonly startDate: string;
  readonly endDate: string;
  readonly year: number;
  readonly month: number;
  readonly affectedAreas: readonly AffectedArea[];
  readonly eventIds: readonly number[];
  readonly eventCount: number;
  readonly sourceFile: string;
}

interface MonthlyCell {
  readonly month: number;
  readonly family: string;
  readonly episodeCount: number;
  readonly eventRowCount: number;
  readonly episodesPerExposureYear: number | null;
  readonly missingYearNote: string | null;
}

interface StateMonthlyCell {
  readonly stateFips: string;
  readonly stateUsps: string;
  readonly family: string;
  readonly month: number;
  readonly episodeCount: number;
  readonly episodesPerExposureYear: number | null;
  readonly missingYearNote: string | null;
}

interface StateFootprint {
  readonly stateFips: string;
  readonly stateUsps: string;
  readonly family: string;
  readonly episodeCount: number;
  readonly medianCountiesPerEpisode: number;
  readonly p90CountiesPerEpisode: number;
}

const episodes = catalog.episodes as readonly Episode[];
const monthly = catalog.monthlyCatalog as readonly MonthlyCell[];
const footprints = catalog.stateFootprintProfile as readonly StateFootprint[];
const stateMonthly = catalog.stateMonthlyCatalog as readonly StateMonthlyCell[];

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

describe("storm hazard catalog: schema and window", () => {
  it("declares the schema, product and family set the consumer expects", () => {
    expect(catalog.schema).toBe("storm-hazard-catalog/v1");
    expect(catalog.dataProduct).toBe(
      "NOAA NCEI Storm Events Database, bulk CSV details",
    );
    expect(catalog.eventFamilies).toEqual([...FAMILIES]);
  });

  it("declares a 2000-2024 window whose exposure matches its missing years", () => {
    const { firstYear, lastYear, exposureYears, missingYears, note } =
      catalog.window;
    expect(firstYear).toBe(2000);
    expect(lastYear).toBe(2024);
    expect(exposureYears).toBe(lastYear - firstYear + 1);
    expect(Array.isArray(missingYears)).toBe(true);
    for (const year of missingYears as readonly number[]) {
      expect(year).toBeGreaterThanOrEqual(firstYear);
      expect(year).toBeLessThanOrEqual(lastYear);
    }
    // The window has to say out loud that it is a record of reports.
    expect(note).toMatch(/recorded-event coverage, not actual hazard/i);
  });

  it("pins one hashed publisher source per non-missing year", () => {
    const missing = new Set(catalog.window.missingYears as readonly number[]);
    const expected = 25 - missing.size;
    expect(catalog.sources).toHaveLength(expected);
    for (const source of catalog.sources) {
      expect(source.sha256).toMatch(/^[0-9a-f]{64}$/);
      expect(source.byteLength).toBeGreaterThan(0);
      expect(source.url).toMatch(/^https:\/\/www\.ncei\.noaa\.gov\//);
      expect(source.fileName).toMatch(
        /^StormEvents_details-ftp_v1\.0_d\d{4}_c\d{8}\.csv\.gz$/,
      );
      expect(source.retrievedAt).toMatch(
        /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/,
      );
    }
    const ids = catalog.sources.map((source) => source.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("reports counts that are internally consistent", () => {
    const {
      detailRowsRead,
      countyRowsKept,
      zoneRowsSeparate,
      episodesCompiled,
    } = catalog.counts;
    expect(detailRowsRead).toBeGreaterThan(countyRowsKept);
    expect(countyRowsKept).toBeGreaterThan(episodesCompiled);
    expect(zoneRowsSeparate).toBeGreaterThanOrEqual(0);
    expect(catalog.reconciliation.length).toBeGreaterThan(0);
    for (const line of catalog.reconciliation) {
      expect(typeof line).toBe("string");
      expect(line.length).toBeGreaterThan(0);
    }
  });
});

describe("storm hazard catalog: episodes", () => {
  it("is non-empty and uniquely keyed by (episodeId, family)", () => {
    expect(episodes.length).toBeGreaterThan(0);
    const keys = episodes.map(
      (episode) => `${episode.episodeId}|${episode.family}`,
    );
    expect(new Set(keys).size).toBe(keys.length);
  });

  it("gives every episode at least one county-typed affected area", () => {
    for (const episode of episodes) {
      expect(episode.affectedAreas.length).toBeGreaterThanOrEqual(1);
      for (const area of episode.affectedAreas) {
        expect(area.stateFips).toMatch(/^\d{2}$/);
        expect(area.countyFips).toMatch(/^\d{3}$/);
        expect(area.czType).toBe("C");
      }
    }
  });

  it("keeps zone rows out of episodes entirely", () => {
    const zoneTyped = episodes.filter((episode) =>
      episode.affectedAreas.some((area) => area.czType !== "C"),
    );
    expect(zoneTyped).toHaveLength(0);
    expect(catalog.counts.zoneRowsSeparate).toBeGreaterThan(0);
  });

  it("dates every episode in ISO order, consistent with its year and month", () => {
    for (const episode of episodes) {
      expect(episode.startDate).toMatch(ISO_DATE);
      expect(episode.endDate).toMatch(ISO_DATE);
      expect(
        episode.startDate.localeCompare(episode.endDate),
      ).toBeLessThanOrEqual(0);
      expect(episode.year).toBe(Number(episode.startDate.slice(0, 4)));
      expect(episode.month).toBe(Number(episode.startDate.slice(5, 7)));
      expect(episode.month).toBeGreaterThanOrEqual(1);
      expect(episode.month).toBeLessThanOrEqual(12);
      expect(episode.year).toBeGreaterThanOrEqual(catalog.window.firstYear);
      expect(episode.year).toBeLessThanOrEqual(catalog.window.lastYear);
    }
  });

  it("uses only declared families and preserves source identifiers", () => {
    for (const episode of episodes) {
      expect(FAMILIES).toContain(episode.family as Family);
      expect(episode.episodeId).toMatch(/^\d{4}-\d+$/);
      expect(episode.sourceFile).toMatch(/^ncei-details-\d{4}$/);
      expect(episode.eventIds.length).toBeGreaterThanOrEqual(1);
      expect(episode.eventCount).toBe(episode.eventIds.length);
      expect(new Set(episode.eventIds).size).toBe(episode.eventIds.length);
      for (const eventId of episode.eventIds) {
        expect(Number.isInteger(eventId)).toBe(true);
      }
    }
  });

  it("states the bound on the emitted episode rows rather than implying none", () => {
    const policy = catalog.episodeDetailPolicy;
    expect(policy.aggregatesCoverFullWindow).toBe(true);
    expect(policy.episodeRowsEmitted).toBe(episodes.length);
    expect(policy.episodesCompiledInWindow).toBe(
      catalog.counts.episodesCompiled,
    );
    expect(policy.rule.length).toBeGreaterThan(0);
    if (policy.episodeRowsCoverFullWindow) {
      expect(policy.episodeRowsEmitted).toBe(policy.episodesCompiledInWindow);
      expect(policy.warning).toBeNull();
    } else {
      // A bounded list must say so, and say it is not a sample.
      expect(policy.episodeRowsEmitted).toBeLessThan(
        policy.episodesCompiledInWindow,
      );
      expect(policy.warning).toMatch(/not a sample/i);
      const years = episodes.map((episode) => episode.year);
      expect(Math.min(...years)).toBeGreaterThanOrEqual(
        policy.episodeRowYears.firstYear,
      );
      expect(Math.max(...years)).toBeLessThanOrEqual(
        policy.episodeRowYears.lastYear,
      );
    }
  });
});

describe("storm hazard catalog: monthly catalog and rates", () => {
  it("covers 12 months x 3 families exactly once each", () => {
    expect(monthly).toHaveLength(36);
    const keys = monthly.map((cell) => `${cell.month}|${cell.family}`);
    expect(new Set(keys).size).toBe(36);
    for (let month = 1; month <= 12; month += 1) {
      for (const family of FAMILIES) {
        expect(keys).toContain(`${month}|${family}`);
      }
    }
  });

  it("gives every cell a real number or an explicit null, never NaN", () => {
    for (const cell of monthly) {
      expect(Number.isInteger(cell.episodeCount)).toBe(true);
      expect(Number.isInteger(cell.eventRowCount)).toBe(true);
      expect(cell.episodeCount).toBeGreaterThanOrEqual(0);
      expect(cell.eventRowCount).toBeGreaterThanOrEqual(cell.episodeCount);

      const rate = cell.episodesPerExposureYear;
      if (rate === null) {
        // An omitted rate must say why it is omitted.
        expect(cell.missingYearNote).not.toBeNull();
        expect(typeof cell.missingYearNote).toBe("string");
      } else {
        expect(typeof rate).toBe("number");
        expect(Number.isNaN(rate)).toBe(false);
        expect(Number.isFinite(rate)).toBe(true);
        expect(rate).toBeGreaterThanOrEqual(0);
      }
    }
  });

  it("derives each rate from the declared exposure and nothing else", () => {
    const missing = (catalog.window.missingYears as readonly number[]).length;
    const exposure = catalog.window.exposureYears - missing;
    for (const cell of monthly) {
      if (cell.episodesPerExposureYear === null) continue;
      expect(cell.episodesPerExposureYear).toBeCloseTo(
        cell.episodeCount / exposure,
        6,
      );
    }
  });

  it("totals to the compiled episode and county-row counts", () => {
    const episodeTotal = monthly.reduce(
      (sum, cell) => sum + cell.episodeCount,
      0,
    );
    const rowTotal = monthly.reduce((sum, cell) => sum + cell.eventRowCount, 0);
    expect(episodeTotal).toBe(catalog.counts.episodesCompiled);
    expect(rowTotal).toBe(catalog.counts.countyRowsKept);
  });
});

describe("storm hazard catalog: state-by-month catalog", () => {
  it("gives every state present a full 12 months x 3 families grid", () => {
    expect(stateMonthly.length).toBeGreaterThan(0);
    const states = [...new Set(stateMonthly.map((cell) => cell.stateFips))];
    expect(stateMonthly).toHaveLength(states.length * 36);
    const keys = stateMonthly.map(
      (cell) => `${cell.stateFips}|${cell.family}|${cell.month}`,
    );
    expect(new Set(keys).size).toBe(keys.length);
    for (const stateFips of states) {
      for (const family of FAMILIES) {
        for (let month = 1; month <= 12; month += 1) {
          expect(keys).toContain(`${stateFips}|${family}|${month}`);
        }
      }
    }
  });

  it("labels each cell with a real state, a declared family and a real month", () => {
    for (const cell of stateMonthly) {
      expect(cell.stateFips).toMatch(/^\d{2}$/);
      expect(cell.stateUsps).toMatch(/^[A-Z]{2}$/);
      expect(FAMILIES).toContain(cell.family as Family);
      expect(Number.isInteger(cell.month)).toBe(true);
      expect(cell.month).toBeGreaterThanOrEqual(1);
      expect(cell.month).toBeLessThanOrEqual(12);
    }
  });

  it("gives every cell a real number or an explicit null, never NaN", () => {
    for (const cell of stateMonthly) {
      expect(Number.isInteger(cell.episodeCount)).toBe(true);
      expect(cell.episodeCount).toBeGreaterThanOrEqual(0);

      const rate = cell.episodesPerExposureYear;
      if (rate === null) {
        expect(cell.missingYearNote).not.toBeNull();
        expect(typeof cell.missingYearNote).toBe("string");
      } else {
        expect(typeof rate).toBe("number");
        expect(Number.isNaN(rate)).toBe(false);
        expect(Number.isFinite(rate)).toBe(true);
        expect(rate).toBeGreaterThanOrEqual(0);
      }
    }
  });

  it("derives each state rate from the same declared exposure", () => {
    const missing = (catalog.window.missingYears as readonly number[]).length;
    const exposure = catalog.window.exposureYears - missing;
    for (const cell of stateMonthly) {
      if (cell.episodesPerExposureYear === null) continue;
      expect(cell.episodesPerExposureYear).toBeCloseTo(
        cell.episodeCount / exposure,
        6,
      );
    }
  });

  it("attributes border-spanning episodes to each state rather than summing to the national total", () => {
    const stateTotal = stateMonthly.reduce(
      (sum, cell) => sum + cell.episodeCount,
      0,
    );
    // Counting an episode once per state it touches can only meet or exceed
    // the national episode count, never fall short of it.
    expect(stateTotal).toBeGreaterThanOrEqual(catalog.counts.episodesCompiled);
    // And the rule that makes that true has to be written down.
    expect(catalog.fieldNotes.stateAttribution).toMatch(/once for each state/i);
    expect(catalog.fieldNotes.monthAssignment).toMatch(/startDate/);
    expect(catalog.fieldNotes.episodesPerExposureYear).toMatch(
      /not a hazard probability/i,
    );
  });

  it("covers every state that the footprint profile knows about", () => {
    const monthlyStates = new Set(stateMonthly.map((cell) => cell.stateFips));
    for (const row of footprints) {
      expect(monthlyStates.has(row.stateFips)).toBe(true);
    }
  });
});

describe("storm hazard catalog: state footprint profile", () => {
  it("keys every row by a real state FIPS and a declared family", () => {
    expect(footprints.length).toBeGreaterThan(0);
    const keys = footprints.map((row) => `${row.stateFips}|${row.family}`);
    expect(new Set(keys).size).toBe(keys.length);
    for (const row of footprints) {
      expect(row.stateFips).toMatch(/^\d{2}$/);
      expect(row.stateUsps).toMatch(/^[A-Z]{2}$/);
      expect(FAMILIES).toContain(row.family as Family);
    }
  });

  it("reports order statistics that a real episode could have had", () => {
    for (const row of footprints) {
      expect(row.episodeCount).toBeGreaterThan(0);
      expect(Number.isInteger(row.medianCountiesPerEpisode)).toBe(true);
      expect(Number.isInteger(row.p90CountiesPerEpisode)).toBe(true);
      expect(row.medianCountiesPerEpisode).toBeGreaterThanOrEqual(1);
      expect(row.p90CountiesPerEpisode).toBeGreaterThanOrEqual(
        row.medianCountiesPerEpisode,
      );
    }
  });
});

describe("storm hazard catalog: no real harm figures are reused", () => {
  const FORBIDDEN_KEY = /death|fatal|injur|damage|casualt|loss|narrative/i;

  const walkKeys = (value: unknown, found: string[] = []): string[] => {
    if (Array.isArray(value)) {
      for (const item of value) walkKeys(item, found);
      return found;
    }
    if (value !== null && typeof value === "object") {
      for (const [key, child] of Object.entries(value)) {
        found.push(key);
        walkKeys(child, found);
      }
    }
    return found;
  };

  it("carries no field named for a death, injury, damage or narrative", () => {
    const offending = [...new Set(walkKeys(catalog))].filter((key) =>
      FORBIDDEN_KEY.test(key),
    );
    expect(offending).toEqual([]);
  });

  it("carries none of the publisher's harm columns in any episode row", () => {
    const harmColumns = [
      "INJURIES_DIRECT",
      "INJURIES_INDIRECT",
      "DEATHS_DIRECT",
      "DEATHS_INDIRECT",
      "DAMAGE_PROPERTY",
      "DAMAGE_CROPS",
      "EPISODE_NARRATIVE",
      "EVENT_NARRATIVE",
    ];
    const episodeKeys = new Set(
      episodes.flatMap((episode) => Object.keys(episode)),
    );
    for (const column of harmColumns) {
      expect(episodeKeys.has(column)).toBe(false);
    }
    const serializedEpisodes = JSON.stringify(episodes);
    for (const column of harmColumns) {
      expect(serializedEpisodes).not.toContain(column);
    }
  });

  it("restricts an episode to identifiers, dates, places and counts", () => {
    const allowed = new Set([
      "episodeId",
      "family",
      "startDate",
      "endDate",
      "year",
      "month",
      "affectedAreas",
      "eventIds",
      "eventCount",
      "sourceFile",
    ]);
    for (const episode of episodes) {
      for (const key of Object.keys(episode)) {
        expect(allowed.has(key)).toBe(true);
      }
    }
    const areaAllowed = new Set([
      "stateFips",
      "countyFips",
      "czName",
      "czType",
    ]);
    for (const area of episodes[0].affectedAreas) {
      for (const key of Object.keys(area)) {
        expect(areaAllowed.has(key)).toBe(true);
      }
    }
  });
});
