import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import {
  loadEducationCatalog,
  type CatalogManifest,
  type FetchLike,
} from "../../src/education/catalog-load";

/**
 * The committed education catalogs, checked the way they are actually trusted.
 *
 * These three files are generated by `scripts/source/export-education.ts` and
 * are large — sixty megabytes for the postsecondary chunk alone. Prettier used
 * to walk them on every `npm run format`, which is why the EDU branch's
 * formatting job died building an AST near four gigabytes, and why they are
 * listed in `.prettierignore` here.
 *
 * Dropping them out of the formatter is only honest if what actually protects
 * them is checked, so this is that check. Prettier was never the protection:
 * the files are content-addressed, `public/education/manifest.json` records
 * each chunk's digest and record count, and the loader re-hashes every chunk it
 * fetches and refuses one whose bytes do not match.
 *
 * Be precise about the guarantee. This establishes INTERNAL CONSISTENCY — that
 * the committed bytes are the bytes the manifest and the file names claim, and
 * that the loader really refuses bytes that are not. That catches a
 * hand-edited catalog, which is the risk the formatter's departure creates. It
 * is NOT producer replay, and the last case below says so and pins it.
 */

const DIR = "public/education";

interface Chunk {
  readonly kind: string;
  readonly path: string;
  readonly sha256: string;
  readonly recordCount: number;
}

interface Manifest {
  readonly version: number;
  readonly chunks: readonly Chunk[];
  readonly recordCount: number;
  readonly source: unknown;
}

const manifest = JSON.parse(
  readFileSync(`${DIR}/manifest.json`, "utf8"),
) as Manifest;

function sha256(bytes: Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

describe("committed education catalogs", () => {
  it("declares a manifest the loader would accept", () => {
    expect(manifest.version).toBe(1);
    expect(manifest.chunks.length).toBeGreaterThan(0);
    // The loader refuses any path that is not content-addressed, so a manifest
    // that named a plain file would fail closed in the browser. Catch it here.
    for (const chunk of manifest.chunks) {
      expect(chunk.path).toMatch(/^catalog-[a-f0-9]{64}\.json$/);
      expect(chunk.sha256).toMatch(/^[a-f0-9]{64}$/);
      expect(chunk.recordCount).toBeGreaterThan(0);
    }
    expect(new Set(manifest.chunks.map((c) => c.kind)).size).toBe(
      manifest.chunks.length,
    );
    expect(
      manifest.chunks.reduce((total, chunk) => total + chunk.recordCount, 0),
    ).toBe(manifest.recordCount);
  });

  it("carries bytes that hash to their own name and to the manifest", () => {
    for (const chunk of manifest.chunks) {
      const bytes = readFileSync(`${DIR}/${chunk.path}`);
      const digest = sha256(bytes);
      // Three independent statements of the same digest: the file name, the
      // manifest entry, and the bytes themselves. A regenerated export moves
      // all three together; a hand-edited catalog moves none of them.
      expect(digest).toBe(chunk.sha256);
      expect(chunk.path).toBe(`catalog-${digest}.json`);
    }
  });

  it("carries the payload shape and the record count it promises", () => {
    for (const chunk of manifest.chunks) {
      const text = readFileSync(`${DIR}/${chunk.path}`, "utf8");
      // The producer writes `JSON.stringify(...) + "\n"`. That exact byte
      // convention is part of the digest, so it is worth stating plainly now
      // that no formatter is enforcing anything about these files.
      expect(text.endsWith("\n")).toBe(true);
      expect(text.trimEnd().endsWith("}")).toBe(true);

      const payload = JSON.parse(text) as {
        version: number;
        dictionary: { capabilities: unknown; hashes: unknown };
        records: readonly unknown[];
      };
      expect(payload.version).toBe(1);
      expect(payload.dictionary.capabilities).toBeTruthy();
      // The dictionary carries the locked acquisition hashes forward, so a
      // catalog cannot be separated from the source edition it came from.
      expect(payload.dictionary.hashes).toBeTruthy();
      expect(payload.records.length).toBe(chunk.recordCount);
    }
  });

  it("refuses a corrupted chunk at the loader the panel actually uses", async () => {
    /*
     * The real negative control, and a correction.
     *
     * What stood here called this file's own sha256 helper on a flipped byte
     * and asserted the digest changed — which is a property of SHA-256, not of
     * this repository. It never touched the loader, so deleting the integrity
     * check would not have failed it, and the comment claiming otherwise had it
     * exactly backwards. Reported by the independent reviewer.
     *
     * This drives `loadEducationCatalog` with tampered bytes and watches it
     * refuse. Remove the digest comparison and this fails.
     */
    const chunk = [...manifest.chunks].sort(
      (a, b) => a.recordCount - b.recordCount,
    )[0]!;
    const good = readFileSync(`${DIR}/${chunk.path}`);
    const oneManifest: CatalogManifest = { chunks: [chunk] };

    const respond = (bytes: Buffer): FetchLike =>
      ((input: string) =>
        Promise.resolve({
          ok: true,
          json: () => Promise.resolve(oneManifest),
          arrayBuffer: () =>
            Promise.resolve(
              input.endsWith("manifest.json")
                ? new ArrayBuffer(0)
                : bytes.buffer.slice(
                    bytes.byteOffset,
                    bytes.byteOffset + bytes.byteLength,
                  ),
            ),
        })) as unknown as FetchLike;

    // The committed bytes load.
    const rows = await loadEducationCatalog(chunk.kind, respond(good));
    expect(rows).toHaveLength(chunk.recordCount);

    // One flipped byte is refused, by the check the panel relies on.
    const tampered = Buffer.from(good);
    const at = Math.floor(tampered.length / 2);
    tampered[at] = tampered[at]! ^ 0x01;
    await expect(
      loadEducationCatalog(chunk.kind, respond(tampered)),
    ).rejects.toThrow(/integrity check failed/i);

    // So is a manifest that names a path which is not content-addressed.
    const renamed: CatalogManifest = {
      chunks: [{ ...chunk, path: "catalog-latest.json" }],
    };
    const renamedFetch = (() =>
      Promise.resolve({
        ok: true,
        json: () => Promise.resolve(renamed),
        arrayBuffer: () => Promise.resolve(new ArrayBuffer(0)),
      })) as unknown as FetchLike;
    await expect(
      loadEducationCatalog(chunk.kind, renamedFetch),
    ).rejects.toThrow(/Invalid directory manifest/i);
  });

  it("is backed by a real producer replay, wired into the gate", () => {
    /*
     * This replaces the assertion that used to live here.
     *
     * It pinned the ABSENCE of a producer runner and said, in as many words,
     * that the day one was added it should fail and be rewritten to check the
     * runner instead of describing its lack. That day came: the compilation
     * moved into `scripts/source/education-export.ts` as a builder that writes
     * nothing, `scripts/source/check-education.ts` replays it against the
     * committed catalogs byte for byte, and `education:check` runs in
     * `validate`.
     *
     * So the statement inverts rather than disappears. Everything above still
     * establishes only INTERNAL CONSISTENCY — a catalog matching a digest
     * committed beside it by the same run — and that is still not producer
     * replay. What changed is that the replay now exists somewhere, and this
     * asserts it stays wired rather than silently dropping out of the gate and
     * leaving 78 MB the education panel fetches outside every producer check
     * again.
     */
    const scripts = JSON.parse(readFileSync("package.json", "utf8")) as {
      scripts: Record<string, string>;
    };
    expect(
      scripts.scripts["education:check"],
      "the education producer replay lost its npm script",
    ).toContain("check-education");
    expect(
      scripts.scripts.validate,
      "education:check dropped out of the validate gate",
    ).toContain("education:check");
  });
});
