import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

/**
 * The committed education catalogs, checked the way they are actually trusted.
 *
 * These three files are generated by `scripts/source/export-education.ts` and
 * are large — sixty megabytes for the postsecondary chunk alone. Prettier used
 * to walk them on every `npm run format`, which is why the EDU branch's
 * formatting job died building an AST near four gigabytes, and why they are
 * listed in `.prettierignore` here.
 *
 * Dropping them out of the formatter is only honest if what actually protects
 * them is checked, so this is that check. Prettier was never the protection:
 * the files are content-addressed, `public/education/manifest.json` records
 * each chunk's digest and record count, and `EducationOptionsPanel` re-hashes
 * every chunk it fetches and refuses one whose bytes do not match. What was
 * missing was any test that the committed bytes still satisfy that contract,
 * or that the refusal is real rather than a line of code nobody runs.
 */

const DIR = "public/education";

interface Chunk {
  readonly kind: string;
  readonly path: string;
  readonly sha256: string;
  readonly recordCount: number;
}

interface Manifest {
  readonly version: number;
  readonly chunks: readonly Chunk[];
  readonly recordCount: number;
  readonly source: unknown;
}

const manifest = JSON.parse(
  readFileSync(`${DIR}/manifest.json`, "utf8"),
) as Manifest;

function sha256(bytes: Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

describe("committed education catalogs", () => {
  it("declares a manifest the loader would accept", () => {
    expect(manifest.version).toBe(1);
    expect(manifest.chunks.length).toBeGreaterThan(0);
    // The loader refuses any path that is not content-addressed, so a manifest
    // that named a plain file would fail closed in the browser. Catch it here.
    for (const chunk of manifest.chunks) {
      expect(chunk.path).toMatch(/^catalog-[a-f0-9]{64}\.json$/);
      expect(chunk.sha256).toMatch(/^[a-f0-9]{64}$/);
      expect(chunk.recordCount).toBeGreaterThan(0);
    }
    expect(new Set(manifest.chunks.map((c) => c.kind)).size).toBe(
      manifest.chunks.length,
    );
    expect(
      manifest.chunks.reduce((total, chunk) => total + chunk.recordCount, 0),
    ).toBe(manifest.recordCount);
  });

  it("carries bytes that hash to their own name and to the manifest", () => {
    for (const chunk of manifest.chunks) {
      const bytes = readFileSync(`${DIR}/${chunk.path}`);
      const digest = sha256(bytes);
      // Three independent statements of the same digest: the file name, the
      // manifest entry, and the bytes themselves. A regenerated export moves
      // all three together; a hand-edited catalog moves none of them.
      expect(digest).toBe(chunk.sha256);
      expect(chunk.path).toBe(`catalog-${digest}.json`);
    }
  });

  it("carries the payload shape and the record count it promises", () => {
    for (const chunk of manifest.chunks) {
      const text = readFileSync(`${DIR}/${chunk.path}`, "utf8");
      // The producer writes `JSON.stringify(...) + "\n"`. That exact byte
      // convention is part of the digest, so it is worth stating plainly now
      // that no formatter is enforcing anything about these files.
      expect(text.endsWith("\n")).toBe(true);
      expect(text.trimEnd().endsWith("}")).toBe(true);

      const payload = JSON.parse(text) as {
        version: number;
        dictionary: { capabilities: unknown; hashes: unknown };
        records: readonly unknown[];
      };
      expect(payload.version).toBe(1);
      expect(payload.dictionary.capabilities).toBeTruthy();
      // The dictionary carries the locked acquisition hashes forward, so a
      // catalog cannot be separated from the source edition it came from.
      expect(payload.dictionary.hashes).toBeTruthy();
      expect(payload.records.length).toBe(chunk.recordCount);
    }
  });

  it("would refuse a corrupted chunk rather than load it", () => {
    // The negative control for the browser loader's integrity check. One byte
    // is enough; if this ever stopped being true the check in
    // `EducationOptionsPanel` would be decorative.
    const chunk = [...manifest.chunks].sort(
      (a, b) => a.recordCount - b.recordCount,
    )[0]!;
    const bytes = readFileSync(`${DIR}/${chunk.path}`);
    expect(sha256(bytes)).toBe(chunk.sha256);

    const tampered = Buffer.from(bytes);
    const at = Math.floor(tampered.length / 2);
    tampered[at] = tampered[at]! ^ 0x01;
    expect(tampered.length).toBe(bytes.length);
    expect(sha256(tampered)).not.toBe(chunk.sha256);

    // Truncation is the other way a chunk goes wrong, and it is the case the
    // record count is there to catch when the digest is not consulted.
    const truncated = bytes.subarray(0, bytes.length - 1);
    expect(sha256(truncated)).not.toBe(chunk.sha256);
  });
});
