// Generated by scripts/trait-effects/generate-manifest.mjs. Do not edit by hand.
import type { TraitEffectDeclaration } from "../../trait-packs";
import { actionDespiteFearEffects } from "./action-despite-fear";
import { bondLoyaltyEffects } from "./bond-loyalty";
import { concernForDistressEffects } from "./concern-for-distress";
import { facetAmbitiousEffects } from "./facet-ambitious";
import { facetAnalyticalEffects } from "./facet-analytical";
import { facetArgumentativeEffects } from "./facet-argumentative";
import { facetAssertiveEffects } from "./facet-assertive";
import { facetBluntEffects } from "./facet-blunt";
import { facetBrazenEffects } from "./facet-brazen";
import { facetCalmEffects } from "./facet-calm";
import { facetCockyEffects } from "./facet-cocky";
import { facetComfortingEffects } from "./facet-comforting";
import { facetCompetitiveEffects } from "./facet-competitive";
import { facetContentedEffects } from "./facet-contented";
import { facetCruelEffects } from "./facet-cruel";
import { facetCuriousEffects } from "./facet-curious";
import { facetCynicalEffects } from "./facet-cynical";
import { facetDefensiveEffects } from "./facet-defensive";
import { facetDutyBoundEffects } from "./facet-duty-bound";
import { facetEnterprisingEffects } from "./facet-enterprising";
import { facetEnviousEffects } from "./facet-envious";
import { facetForgivingEffects } from "./facet-forgiving";
import { facetFriendlyEffects } from "./facet-friendly";
import { facetGenerousEffects } from "./facet-generous";
import { facetGentleEffects } from "./facet-gentle";
import { facetGuardedEffects } from "./facet-guarded";
import { facetHostileEffects } from "./facet-hostile";
import { facetHumbleEffects } from "./facet-humble";
import { facetIndependentEffects } from "./facet-independent";
import { facetInventiveEffects } from "./facet-inventive";
import { facetMeticulousEffects } from "./facet-meticulous";
import { facetNurturingEffects } from "./facet-nurturing";
import { facetOpenMindedEffects } from "./facet-open-minded";
import { facetOpportunisticEffects } from "./facet-opportunistic";
import { facetPersistentEffects } from "./facet-persistent";
import { facetPhilanthropicEffects } from "./facet-philanthropic";
import { facetPoliteEffects } from "./facet-polite";
import { facetPracticalEffects } from "./facet-practical";
import { facetProudEffects } from "./facet-proud";
import { facetSelfConsciousEffects } from "./facet-self-conscious";
import { facetSkepticalEffects } from "./facet-skeptical";
import { facetStudiousEffects } from "./facet-studious";
import { facetSupportiveEffects } from "./facet-supportive";
import { facetTenderHeartedEffects } from "./facet-tender-hearted";
import { facetWorkCenteredEffects } from "./facet-work-centered";
import { facetZealousEffects } from "./facet-zealous";
import { initialTrustEffects } from "./initial-trust";
import { methodRevisionEffects } from "./method-revision";
import { outwardEmotionalDisplayEffects } from "./outward-emotional-display";
import { patienceEffects } from "./patience";
import { selfConfidenceEffects } from "./self-confidence";
import { uncertainOutlookEffects } from "./uncertain-outlook";
import { voluntaryEffortEffects } from "./voluntary-effort";

/**
 * The catalog's effect readers, one trait per leaf module. Adding a trait
 * means adding its file; run npm run generate:trait-effects to register it.
 */
export function personalityTraitEffects(): readonly TraitEffectDeclaration[] {
  return [
    ...actionDespiteFearEffects,
    ...bondLoyaltyEffects,
    ...concernForDistressEffects,
    ...facetAmbitiousEffects,
    ...facetAnalyticalEffects,
    ...facetArgumentativeEffects,
    ...facetAssertiveEffects,
    ...facetBluntEffects,
    ...facetBrazenEffects,
    ...facetCalmEffects,
    ...facetCockyEffects,
    ...facetComfortingEffects,
    ...facetCompetitiveEffects,
    ...facetContentedEffects,
    ...facetCruelEffects,
    ...facetCuriousEffects,
    ...facetCynicalEffects,
    ...facetDefensiveEffects,
    ...facetDutyBoundEffects,
    ...facetEnterprisingEffects,
    ...facetEnviousEffects,
    ...facetForgivingEffects,
    ...facetFriendlyEffects,
    ...facetGenerousEffects,
    ...facetGentleEffects,
    ...facetGuardedEffects,
    ...facetHostileEffects,
    ...facetHumbleEffects,
    ...facetIndependentEffects,
    ...facetInventiveEffects,
    ...facetMeticulousEffects,
    ...facetNurturingEffects,
    ...facetOpenMindedEffects,
    ...facetOpportunisticEffects,
    ...facetPersistentEffects,
    ...facetPhilanthropicEffects,
    ...facetPoliteEffects,
    ...facetPracticalEffects,
    ...facetProudEffects,
    ...facetSelfConsciousEffects,
    ...facetSkepticalEffects,
    ...facetStudiousEffects,
    ...facetSupportiveEffects,
    ...facetTenderHeartedEffects,
    ...facetWorkCenteredEffects,
    ...facetZealousEffects,
    ...initialTrustEffects,
    ...methodRevisionEffects,
    ...outwardEmotionalDisplayEffects,
    ...patienceEffects,
    ...selfConfidenceEffects,
    ...uncertainOutlookEffects,
    ...voluntaryEffortEffects,
  ];
}
