// Generated by scripts/trait-effects/generate-manifest.mjs. Do not edit by hand.
import type { TraitEffectDeclaration } from "../../trait-packs";
import { actionDespiteFearEffects } from "./action-despite-fear";
import { bondLoyaltyEffects } from "./bond-loyalty";
import { concernForDistressEffects } from "./concern-for-distress";
import { facetAcquisitiveEffects } from "./facet-acquisitive";
import { facetAmbitiousEffects } from "./facet-ambitious";
import { facetAnalyticalEffects } from "./facet-analytical";
import { facetApprovalSeekingEffects } from "./facet-approval-seeking";
import { facetArbitraryEffects } from "./facet-arbitrary";
import { facetArgumentativeEffects } from "./facet-argumentative";
import { facetAssertiveEffects } from "./facet-assertive";
import { facetBluntEffects } from "./facet-blunt";
import { facetBrazenEffects } from "./facet-brazen";
import { facetBroodingEffects } from "./facet-brooding";
import { facetCalmEffects } from "./facet-calm";
import { facetClosenessSeekingEffects } from "./facet-closeness-seeking";
import { facetCockyEffects } from "./facet-cocky";
import { facetComfortingEffects } from "./facet-comforting";
import { facetCompetitiveEffects } from "./facet-competitive";
import { facetContentedEffects } from "./facet-contented";
import { facetCruelEffects } from "./facet-cruel";
import { facetCuriousEffects } from "./facet-curious";
import { facetDefensiveEffects } from "./facet-defensive";
import { facetDeferentialEffects } from "./facet-deferential";
import { facetDevotedEffects } from "./facet-devoted";
import { facetDramaticEffects } from "./facet-dramatic";
import { facetDutyBoundEffects } from "./facet-duty-bound";
import { facetEnterprisingEffects } from "./facet-enterprising";
import { facetEntitledEffects } from "./facet-entitled";
import { facetEnviousEffects } from "./facet-envious";
import { facetExcitableEffects } from "./facet-excitable";
import { facetForgivingEffects } from "./facet-forgiving";
import { facetFriendlyEffects } from "./facet-friendly";
import { facetGenerousEffects } from "./facet-generous";
import { facetGentleEffects } from "./facet-gentle";
import { facetGuardedEffects } from "./facet-guarded";
import { facetHostileEffects } from "./facet-hostile";
import { facetHumbleEffects } from "./facet-humble";
import { facetImaginativeEffects } from "./facet-imaginative";
import { facetIndependentEffects } from "./facet-independent";
import { facetInformalEffects } from "./facet-informal";
import { facetIntimacyGuardedEffects } from "./facet-intimacy-guarded";
import { facetInventiveEffects } from "./facet-inventive";
import { facetManipulativeEffects } from "./facet-manipulative";
import { facetMeticulousEffects } from "./facet-meticulous";
import { facetMischievousEffects } from "./facet-mischievous";
import { facetNurturingEffects } from "./facet-nurturing";
import { facetObservantEffects } from "./facet-observant";
import { facetOpenMindedEffects } from "./facet-open-minded";
import { facetOpportunisticEffects } from "./facet-opportunistic";
import { facetPersistentEffects } from "./facet-persistent";
import { facetPhilanthropicEffects } from "./facet-philanthropic";
import { facetPoliteEffects } from "./facet-polite";
import { facetPracticalEffects } from "./facet-practical";
import { facetProudEffects } from "./facet-proud";
import { facetRestlessEffects } from "./facet-restless";
import { facetSelfConsciousEffects } from "./facet-self-conscious";
import { facetSkepticalEffects } from "./facet-skeptical";
import { facetSlowToWarmUpEffects } from "./facet-slow-to-warm-up";
import { facetStudiousEffects } from "./facet-studious";
import { facetSupportiveEffects } from "./facet-supportive";
import { facetTactfulEffects } from "./facet-tactful";
import { facetTeasingEffects } from "./facet-teasing";
import { facetTenderHeartedEffects } from "./facet-tender-hearted";
import { facetVindictiveEffects } from "./facet-vindictive";
import { facetWorkCenteredEffects } from "./facet-work-centered";
import { facetZealousEffects } from "./facet-zealous";
import { initialTrustEffects } from "./initial-trust";
import { methodRevisionEffects } from "./method-revision";
import { outwardEmotionalDisplayEffects } from "./outward-emotional-display";
import { patienceEffects } from "./patience";
import { playfulMannerEffects } from "./playful-manner";
import { selfConfidenceEffects } from "./self-confidence";
import { uncertainOutlookEffects } from "./uncertain-outlook";
import { voluntaryEffortEffects } from "./voluntary-effort";

/**
 * The catalog's effect readers, one trait per leaf module. Adding a trait
 * means adding its file; run npm run generate:trait-effects to register it.
 */
export function personalityTraitEffects(): readonly TraitEffectDeclaration[] {
  return [
    ...actionDespiteFearEffects,
    ...bondLoyaltyEffects,
    ...concernForDistressEffects,
    ...facetAcquisitiveEffects,
    ...facetAmbitiousEffects,
    ...facetAnalyticalEffects,
    ...facetApprovalSeekingEffects,
    ...facetArbitraryEffects,
    ...facetArgumentativeEffects,
    ...facetAssertiveEffects,
    ...facetBluntEffects,
    ...facetBrazenEffects,
    ...facetBroodingEffects,
    ...facetCalmEffects,
    ...facetClosenessSeekingEffects,
    ...facetCockyEffects,
    ...facetComfortingEffects,
    ...facetCompetitiveEffects,
    ...facetContentedEffects,
    ...facetCruelEffects,
    ...facetCuriousEffects,
    ...facetDefensiveEffects,
    ...facetDeferentialEffects,
    ...facetDevotedEffects,
    ...facetDramaticEffects,
    ...facetDutyBoundEffects,
    ...facetEnterprisingEffects,
    ...facetEntitledEffects,
    ...facetEnviousEffects,
    ...facetExcitableEffects,
    ...facetForgivingEffects,
    ...facetFriendlyEffects,
    ...facetGenerousEffects,
    ...facetGentleEffects,
    ...facetGuardedEffects,
    ...facetHostileEffects,
    ...facetHumbleEffects,
    ...facetImaginativeEffects,
    ...facetIndependentEffects,
    ...facetInformalEffects,
    ...facetIntimacyGuardedEffects,
    ...facetInventiveEffects,
    ...facetManipulativeEffects,
    ...facetMeticulousEffects,
    ...facetMischievousEffects,
    ...facetNurturingEffects,
    ...facetObservantEffects,
    ...facetOpenMindedEffects,
    ...facetOpportunisticEffects,
    ...facetPersistentEffects,
    ...facetPhilanthropicEffects,
    ...facetPoliteEffects,
    ...facetPracticalEffects,
    ...facetProudEffects,
    ...facetRestlessEffects,
    ...facetSelfConsciousEffects,
    ...facetSkepticalEffects,
    ...facetSlowToWarmUpEffects,
    ...facetStudiousEffects,
    ...facetSupportiveEffects,
    ...facetTactfulEffects,
    ...facetTeasingEffects,
    ...facetTenderHeartedEffects,
    ...facetVindictiveEffects,
    ...facetWorkCenteredEffects,
    ...facetZealousEffects,
    ...initialTrustEffects,
    ...methodRevisionEffects,
    ...outwardEmotionalDisplayEffects,
    ...patienceEffects,
    ...playfulMannerEffects,
    ...selfConfidenceEffects,
    ...uncertainOutlookEffects,
    ...voluntaryEffortEffects,
  ];
}
