#!/usr/bin/env node
import process from "node:process";
import console from "node:console";
/**
 * Projects the 92N state-and-local fiscal authority matrix (a secondary,
 * research-input source) and the first-party production corpus into the small
 * file the simulation reads: what each state lets its counties and
 * municipalities do about property, sales, payroll and income taxes.
 *
 * Every cell it keeps names the matrix path it came from, so a lookup can cite
 * it. The production corpus overrides the matrix wherever it has a record.
 * Run `node scripts/local-tax-authority/generate.mjs` to rewrite the file, or
 * `--check` to fail when the committed copy has drifted.
 */
import { readFileSync, writeFileSync } from "node:fs";

const MATRIX =
  "data/source/state-local-fiscal-authority/research-input/92N_NATIONAL_STATE_LOCAL_FISCAL_AUTHORITY.json";
const CORPUS = "data/source/state-local-fiscal-authority/corpus.json";
const OUT = "data/research/money/local-tax-authority-matrix.json";

const matrix = JSON.parse(readFileSync(MATRIX, "utf8"));
const corpus = JSON.parse(readFileSync(CORPUS, "utf8"));

const salesStatus = {
  PERMITTED: "allowed",
  LIMITED_RESORT_LODGING_ONLY: "specific",
  PROHIBITED: "prohibited",
};
const incomeStatus = {
  PERMITTED_GENERAL: "allowed",
  PERMITTED_PIGGYBACK: "piggyback",
  RESTRICTED_SPECIFIC_CITIES: "specific",
  PROHIBITED: "prohibited",
};

const states = {};
for (const state of matrix.states) {
  const code = state.metadata.code;
  const local = state.local_fiscal_authority;
  const cell = (row, column) =>
    `92N matrix: ${code} / local_fiscal_authority / ${row}${column ? ` / ${column}` : ""}`;
  const framework = local.state_framework_for_municipal_taxing;
  const sales = local.local_sales_tax_authority;
  const income = local.local_income_payroll_tax_authority;
  const property = local.property_tax_authority_and_limits;
  if (!salesStatus[sales.status] || !incomeStatus[income.status])
    throw new Error(`${code}: an unmapped matrix status.`);
  states[code] = {
    generalRule: {
      dillonsRule: framework.dillons_rule_status,
      fiscalHomeRuleScope: framework.fiscal_home_rule_scope,
      cell: cell("state_framework_for_municipal_taxing", "dillons_rule_status"),
    },
    property: {
      status: "allowed",
      millageRateSettingBody: property.millage_rate_setting_body.trim(),
      cell: cell("property_tax_authority_and_limits"),
    },
    sales: {
      status: salesStatus[sales.status],
      cell: cell("local_sales_tax_authority", "status"),
    },
    incomePayroll: {
      status: incomeStatus[income.status],
      taxType: income.tax_type,
      cell: cell("local_income_payroll_tax_authority", "status"),
    },
  };
}

const productionStatus = {
  AUTHORIZED: "allowed",
  AUTHORIZED_WITH_VOTER_APPROVAL: "allowed",
};
const instrumentKey = {
  PROPERTY_TAX: "property",
  GENERAL_SALES_TAX: "sales",
};
const production = [];
for (const record of corpus) {
  if (record.kind !== "TAX_INSTRUMENT") continue;
  const instrument = instrumentKey[record.instrument];
  const status = productionStatus[record.authorization?.value];
  if (!instrument || !status) continue;
  production.push({
    stateUsps: record.stateUsps,
    level: record.level,
    instrument,
    status,
    recordId: record.recordId,
    asOf: record.authorization.asOf,
  });
}
production.sort((a, b) =>
  `${a.stateUsps}${a.level}${a.instrument}`.localeCompare(
    `${b.stateUsps}${b.level}${b.instrument}`,
  ),
);

const modal = (values) => {
  const counts = new Map();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return [...counts.entries()].sort(
    (a, b) => b[1] - a[1] || a[0].localeCompare(b[0]),
  )[0][0];
};
const all = Object.values(states);
const national = {
  basis: `Most common value across the ${all.length} states the matrix covers; used only for a place the matrix has no row for.`,
  generalRule: {
    dillonsRule: modal(all.map((s) => s.generalRule.dillonsRule)),
    fiscalHomeRuleScope: modal(
      all.map((s) => s.generalRule.fiscalHomeRuleScope),
    ),
  },
  property: "allowed",
  sales: modal(all.map((s) => s.sales.status)),
  incomePayroll: modal(all.map((s) => s.incomePayroll.status)),
};

const output = {
  about:
    "Generated by scripts/local-tax-authority/generate.mjs from the 92N matrix (a secondary research input, estimated) and the first-party production corpus (sourced). Do not edit by hand.",
  matrix: {
    path: MATRIX,
    asOf: matrix.as_of_date,
    states: all.length,
  },
  states,
  production,
  national,
};
const text = `${JSON.stringify(output, null, 2)}\n`;
if (process.argv.includes("--check")) {
  if (readFileSync(OUT, "utf8") !== text) {
    console.error(`${OUT} is out of date; run the generator.`);
    process.exit(1);
  }
} else writeFileSync(OUT, text);
