import { readFileSync, writeFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import toneData from "../../art/manifest/character_candidate_visual4_tone.json";
import {
  COMPLEXION_COHERENT_RECIPE_VERSION,
  resolveCharacterRecipe,
  type SkinTone,
} from "../../src/presentation/character-components";
import { PEOPLE_VISUAL4_CHARACTER_LIBRARY } from "../../src/presentation/people-visual4-review";
import { buildProductionWorld } from "../../src/presentation/production-world";
import {
  LEGACY_APPEARANCE_RECIPE_VERSION,
  derivePersonAppearance,
  personName,
  requireLifePlace,
} from "../../src/simulation";
import type { Person } from "../../src/simulation";

const REPORT = "docs/agent/evidence/modular-gen14/APPEARANCE-RECIPE-V2.md";

const TONE = new Map(
  (toneData as { tones: { family: string; rgb: SkinTone }[] }).tones.map(
    (entry) => [entry.family, entry.rgb] as const,
  ),
);

function gap(bodyFamily: string, headFamily: string): number | null {
  const body = TONE.get(bodyFamily);
  const head = TONE.get(headFamily);
  if (!body || !head) return null;
  return Math.round(
    Math.hypot(head.r - body.r, head.g - body.g, head.b - body.b),
  );
}

function resolveAt(person: Person, version: string) {
  return resolveCharacterRecipe(
    {
      appearance: derivePersonAppearance(person.id, version),
      poseFamily: "standing-neutral",
      unresolvableRequiredSlots: "diagnose",
    },
    PEOPLE_VISUAL4_CHARACTER_LIBRARY,
  );
}

const SEEDS = ["play-a", "play-b", "play-c", "play-d", "play-e"] as const;

interface Row {
  readonly seed: string;
  readonly name: string;
  readonly stamped: string;
  readonly v1: string;
  readonly v1Gap: number | null;
  readonly v2: string;
  readonly v2Gap: number | null;
}

function measure(): readonly Row[] {
  const rows: Row[] = [];
  for (const seed of SEEDS) {
    const built = buildProductionWorld({
      seed,
      place: requireLifePlace("lexington-fayette"),
      age: 34,
      givenName: null,
      familyName: null,
      // The exact route the banked playable proof walks: an ordinary life,
      // earlier years summarized, sharing a home — so the household this
      // measures is the household somebody actually meets in the room.
      startingLife: "ordinary-life",
      depth: "summarize-earlier-life",
      household: "shares-a-home",
    });
    for (const person of Object.values(built.world.people)) {
      const v1 = resolveAt(person, LEGACY_APPEARANCE_RECIPE_VERSION).identity;
      const v2 = resolveAt(person, COMPLEXION_COHERENT_RECIPE_VERSION).identity;
      rows.push({
        seed,
        name: personName(person),
        stamped: person.appearance?.recipeVersion ?? "(none)",
        v1: `${v1.bodyFamily} / ${v1.headFamily}`,
        v1Gap: gap(v1.bodyFamily, v1.headFamily),
        v2: `${v2.bodyFamily} / ${v2.headFamily}`,
        v2Gap: gap(v2.bodyFamily, v2.headFamily),
      });
    }
  }
  return rows;
}

function median(values: readonly number[]): number {
  return [...values].sort((a, b) => a - b)[Math.floor(values.length / 2)] ?? 0;
}

function render(rows: readonly Row[]): string {
  const v1Gaps = rows.flatMap((row) => (row.v1Gap === null ? [] : [row.v1Gap]));
  const v2Gaps = rows.flatMap((row) => (row.v2Gap === null ? [] : [row.v2Gap]));
  const stamped = rows.filter(
    (row) => row.stamped === COMPLEXION_COHERENT_RECIPE_VERSION,
  ).length;
  const lines = [
    "# Five lives started through the production path, measured",
    "",
    "Regenerated by `npm run measure:appearance-v2`. Every person below was",
    "created by `buildProductionWorld` — the constructor New Game uses — and",
    "resolved against the candidate review bank. The gap column is the RGB",
    "distance between the measured skin of the chosen body and the chosen face;",
    "the measurement is `art/manifest/character_candidate_visual4_tone.json`,",
    "read off the rasters rather than inferred from any family or person name.",
    "",
    `- people created: **${rows.length}**`,
    `- stamped \`${COMPLEXION_COHERENT_RECIPE_VERSION}\`: **${stamped}/${rows.length}**`,
    `- head/body gap under v1: median **${median(v1Gaps)}**, worst **${Math.max(...v1Gaps)}**`,
    `- head/body gap under v2: median **${median(v2Gaps)}**, worst **${Math.max(...v2Gaps)}**`,
    "",
    "| life | person | stamped | v1 body / face | gap | v2 body / face | gap |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows.map(
      (row) =>
        `| ${row.seed} | ${row.name} | \`${row.stamped}\` | ${row.v1} | ${row.v1Gap ?? "—"} | ${row.v2} | ${row.v2Gap ?? "—"} |`,
    ),
    "",
  ];
  return lines.join("\n");
}

/**
 * The repair, measured on lives the game actually creates.
 *
 * `appearance-recipe-v2.test.ts` proves the recipe in isolation and proves the
 * v1 path is untouched. This proves the wiring: that the constructor New Game
 * calls stamps the coherent recipe onto the player AND onto the household
 * written around them, and what that does to the measured skin gap on real
 * people rather than on bare seeds.
 *
 * Read-only unless a capture run asks otherwise, for the reason
 * `figure-framing.test.ts` gives: `docs/agent/evidence` is tracked, the prose
 * corpus measures the same tree live, and regenerating it as a side effect of
 * an ordinary `npm run test` turns unrelated suites red.
 */
describe("appearance recipe v2 on lives the game creates", () => {
  const rows = measure();

  it("matches the committed report, and refreshes it on a capture run", () => {
    if (process.env.PG_CAPTURE_EVIDENCE === "1") {
      writeFileSync(REPORT, render(rows), "utf8");
      return;
    }
    expect(readFileSync(REPORT, "utf8")).toBe(render(rows));
  });

  it("stamps every person a new life creates, player and household alike", () => {
    expect(rows.length).toBeGreaterThan(SEEDS.length);
    for (const row of rows)
      expect(row.stamped).toBe(COMPLEXION_COHERENT_RECIPE_VERSION);
  });

  it("narrows the measured gap on those same people", () => {
    const v1Gaps = rows.flatMap((row) =>
      row.v1Gap === null ? [] : [row.v1Gap],
    );
    const v2Gaps = rows.flatMap((row) =>
      row.v2Gap === null ? [] : [row.v2Gap],
    );
    expect(v1Gaps.length).toBe(rows.length);
    expect(v2Gaps.length).toBe(rows.length);
    expect(median(v1Gaps)).toBeGreaterThan(40);
    expect(median(v2Gaps)).toBeLessThan(25);
  });
});
