import { describe, expect, it } from "vitest";

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  FIGURE_FRAMING_DIRECTORY,
  measureEveryPlacement,
  renderFigureFramingMarkdown,
  misregistered,
  offTheFloor,
  writeFigureFramingReport,
} from "./figure-framing-report";

/**
 * The figure-framing report, regenerated and checked by the same run.
 *
 * `npm run measure:figures` drives this file; `npm run test` runs it too, so a
 * change to a body, a garment, a pose or a room's anchors changes the checked-in
 * report in the same commit rather than leaving a reviewer reading last week's
 * numbers.
 *
 * The assertions here are deliberately about CONTRACTS the compositor already
 * promises, not about how the art looks. Taste is a human review; these are the
 * things a human review should not have to rediscover.
 */
describe("what the shell actually composes", () => {
  const { production, candidate } = measureEveryPlacement();

  /*
   * Read-only unless a capture run asks otherwise.
   *
   * The first version of this wrote the report on every run, which is the
   * same mistake E had just repaired on the browser side: `docs/agent/evidence`
   * is tracked and the harness asserts nothing under it moved, and the prose
   * corpus measures the same tree live. Regenerating it as a side effect of an
   * ordinary `npm run test` turned two unrelated suites red. The report is
   * still regenerated by test — `npm run measure:figures` sets the flag — but
   * an ordinary run only checks that what is committed matches what the code
   * composes now.
   */
  it("matches the committed report, and refreshes it on a capture run", () => {
    if (process.env.PG_CAPTURE_EVIDENCE === "1") {
      const written = writeFigureFramingReport();
      expect(written.production.measurements.length).toBe(
        production.measurements.length,
      );
      return;
    }
    const committed = readFileSync(
      resolve(FIGURE_FRAMING_DIRECTORY, "figure-framing.md"),
      "utf8",
    );
    expect(committed).toBe(renderFigureFramingMarkdown(production, candidate));
  });

  it("measures every placeable anchor in every paintable room", () => {
    expect(production.measurements.length).toBeGreaterThan(0);
    expect(candidate.measurements.length).toBe(production.measurements.length);
  });

  /*
   * Registration is a contract, not an aesthetic.
   *
   * A component declares an origin and the body anchor it attaches to, and the
   * projection places it so those coincide. Unless a fit bank deliberately
   * moves it, the residual is zero by construction — so a non-zero residual on
   * an UNFITTED layer means the component's metadata and the body's anchors
   * disagree, which is the defect that reads as "the hair sits wrong" and can
   * never be judged by eye at this size.
   */
  it("lands every unfitted component on the anchor it declares", () => {
    for (const report of [production, candidate])
      expect(
        misregistered(report).map((row) => ({
          scene: row.sceneId,
          anchor: row.anchorId,
          layers: row.layers
            .filter(
              (layer) => layer.originResidual && !layer.originResidual.fitted,
            )
            .map((layer) => layer.assetId),
        })),
      ).toEqual([]);
  });

  /*
   * Feet on the floor.
   *
   * The fallback fit exists precisely to put a figure's own contact line on the
   * anchor's declared one; a figure that floats or sinks is the placement bug
   * that fit was written to remove, and it looks identical to bad art.
   */
  it("stands every fitted figure on the contact line its anchor declares", () => {
    for (const report of [production, candidate])
      expect(
        offTheFloor(report).map((row) => ({
          scene: row.sceneId,
          anchor: row.anchorId,
          residual: row.contactResidualPercent?.value,
        })),
      ).toEqual([]);
  });

  /*
   * No fabricated precision, enforced rather than promised.
   *
   * Only the two assumed human-proportion ratios may be estimates. Anything
   * else claiming to be an estimate would be a measurement somebody invented,
   * and this is the boundary the art constraints care most about.
   */
  it("labels every derived number, and estimates only the two ratios", () => {
    for (const report of [production, candidate])
      for (const row of report.measurements)
        for (const value of [
          row.composedHeightPercent,
          row.fittedHeightPercent,
          row.contactResidualPercent,
        ])
          if (value) expect(value.confidence).toBe("exact");
  });

  it("says what is missing in the compositor's own words", () => {
    for (const need of candidate.remainingAssetNeeds)
      expect(need).toMatch(/^[a-z-]+: /);
  });
});
