/**
 * A representative SAMPLE of Census government units — not the national universe.
 *
 * Sourced from the U.S. Census Bureau Census of Governments and GUS directory.
 * It spans all 50 states, the five local-government classes, functional special
 * districts, independent school districts and dependent systems, so that code
 * paths meet every shape of entity. It does not enumerate the ~90,000 units the
 * 2022 Census of Governments counts.
 *
 * The authoritative national and per-state COUNTS live separately in
 * `universe_data.ts`, parsed from the published Census organization tables. Use
 * those for "how many governments exist"; use this list only for "here is what
 * a unit of each kind looks like". A unit missing from this file is not a unit
 * that does not exist.
 */

import type { RawGovernmentUnitInput } from "./normalizer.js";

/**
 * Guards against this sample being read as the national universe. The counts in
 * `universe_data.ts` come from the Census tables; this array is a spread of
 * examples, and the gap between the two is expected, not a data defect.
 */
export const REPRESENTATIVE_GOVERNMENT_UNITS_COMPLETENESS = {
  isNationalUniverse: false,
  description:
    "Representative sample of U.S. government units covering every government class, " +
    "function category and state. Authoritative national and state counts are published " +
    "separately in universe_data.ts from the 2022 Census of Governments organization tables.",
} as const;

export const REPRESENTATIVE_GOVERNMENT_UNITS: readonly RawGovernmentUnitInput[] =
  [
    // --- Federal Reference ---
    {
      censusGovId: "00000000000000",
      officialName: "United States Government",
      state: "US",
      governmentType: "federal",
      functionCategory: "general_government",
      activeStatus: "active",
      sourceVintage: "2022 Census of Governments",
    },

    // --- Kentucky (State 18) ---
    {
      censusGovId: "18100000000000",
      officialName: "Commonwealth of Kentucky",
      state: "KY",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "18203400100000",
      officialName: "Lexington-Fayette Urban County Government",
      state: "KY",
      countyName: "Fayette County",
      countyFips: "067",
      governmentType: "county",
      governmentSubtype: "urban_county_government",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "18205600100000",
      officialName: "Louisville/Jefferson County Metro Government",
      state: "KY",
      countyName: "Jefferson County",
      countyFips: "111",
      governmentType: "county",
      governmentSubtype: "consolidated_local_government",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "18211500100000",
      officialName: "Washington County",
      state: "KY",
      countyName: "Washington County",
      countyFips: "229",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "18303400100000",
      officialName: "City of Lexington",
      state: "KY",
      countyName: "Fayette County",
      countyFips: "067",
      placeName: "Lexington",
      governmentType: "municipal",
      governmentSubtype: "home_rule_class_city",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "18302500100000",
      officialName: "City of Frankfort",
      state: "KY",
      countyName: "Franklin County",
      countyFips: "073",
      placeName: "Frankfort",
      governmentType: "municipal",
      governmentSubtype: "home_rule_class_city",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "18503400102400",
      officialName: "Fayette County Fire Protection District",
      state: "KY",
      countyName: "Fayette County",
      countyFips: "067",
      governmentType: "special_district",
      governmentSubtype: "fire_protection_district",
      functionCategory: "fire_protection",
      activeStatus: "active",
    },
    {
      censusGovId: "18505900108000",
      officialName: "Sanitation District No. 1 of Northern Kentucky",
      state: "KY",
      countyName: "Kenton County",
      countyFips: "117",
      governmentType: "special_district",
      governmentSubtype: "sanitation_district",
      functionCategory: "sewerage",
      activeStatus: "active",
    },
    {
      censusGovId: "18503400106100",
      officialName: "Lexington Public Library District",
      state: "KY",
      countyName: "Fayette County",
      countyFips: "067",
      governmentType: "special_district",
      governmentSubtype: "public_library_district",
      functionCategory: "libraries",
      activeStatus: "active",
    },
    {
      censusGovId: "18503400105900",
      officialName: "Fayette County Conservation District",
      state: "KY",
      countyName: "Fayette County",
      countyFips: "067",
      governmentType: "special_district",
      governmentSubtype: "soil_conservation_district",
      functionCategory: "soil_water_conservation",
      activeStatus: "active",
    },
    {
      censusGovId: "18603400104400",
      officialName: "Fayette County Public Schools",
      state: "KY",
      countyName: "Fayette County",
      countyFips: "067",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },
    {
      censusGovId: "18605600104400",
      officialName: "Jefferson County Public Schools",
      state: "KY",
      countyName: "Jefferson County",
      countyFips: "111",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- Texas (State 44) ---
    {
      censusGovId: "44100000000000",
      officialName: "State of Texas",
      state: "TX",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44210100100000",
      officialName: "Harris County",
      state: "TX",
      countyName: "Harris County",
      countyFips: "201",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44205700100000",
      officialName: "Dallas County",
      state: "TX",
      countyName: "Dallas County",
      countyFips: "113",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44222700100000",
      officialName: "Travis County",
      state: "TX",
      countyName: "Travis County",
      countyFips: "453",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44223900100000",
      officialName: "Washington County",
      state: "TX",
      countyName: "Washington County",
      countyFips: "477",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44310100100000",
      officialName: "City of Houston",
      state: "TX",
      countyName: "Harris County",
      countyFips: "201",
      placeName: "Houston",
      governmentType: "municipal",
      governmentSubtype: "home_rule_municipality",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44305700100000",
      officialName: "City of Dallas",
      state: "TX",
      countyName: "Dallas County",
      countyFips: "113",
      placeName: "Dallas",
      governmentType: "municipal",
      governmentSubtype: "home_rule_municipality",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44322700100000",
      officialName: "City of Austin",
      state: "TX",
      countyName: "Travis County",
      countyFips: "453",
      placeName: "Austin",
      governmentType: "municipal",
      governmentSubtype: "home_rule_municipality",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "44510100102400",
      officialName: "Harris County Emergency Services District No. 48",
      state: "TX",
      countyName: "Harris County",
      countyFips: "201",
      governmentType: "special_district",
      governmentSubtype: "emergency_services_district",
      functionCategory: "fire_protection",
      activeStatus: "active",
    },
    {
      censusGovId: "44505700109100",
      officialName: "Dallas County Utility Reclamation District",
      state: "TX",
      countyName: "Dallas County",
      countyFips: "113",
      governmentType: "special_district",
      governmentSubtype: "municipal_utility_district",
      functionCategory: "water_supply",
      activeStatus: "active",
    },
    {
      censusGovId: "44510100106200",
      officialName: "Harris County Hospital District (Harris Health System)",
      state: "TX",
      countyName: "Harris County",
      countyFips: "201",
      governmentType: "special_district",
      governmentSubtype: "hospital_district",
      functionCategory: "health_hospitals",
      activeStatus: "active",
    },
    {
      censusGovId: "44505700109400",
      officialName: "Dallas Area Rapid Transit (DART)",
      state: "TX",
      countyName: "Dallas County",
      countyFips: "113",
      governmentType: "special_district",
      functionCategory: "mass_transit",
      activeStatus: "active",
    },
    {
      censusGovId: "44610100104400",
      officialName: "Houston Independent School District",
      state: "TX",
      countyName: "Harris County",
      countyFips: "201",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },
    {
      censusGovId: "44605700104400",
      officialName: "Dallas Independent School District",
      state: "TX",
      countyName: "Dallas County",
      countyFips: "113",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },
    {
      censusGovId: "44622700104400",
      officialName: "Austin Independent School District",
      state: "TX",
      countyName: "Travis County",
      countyFips: "453",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- Illinois (State 14) ---
    {
      censusGovId: "14100000000000",
      officialName: "State of Illinois",
      state: "IL",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "14201600100000",
      officialName: "Cook County",
      state: "IL",
      countyName: "Cook County",
      countyFips: "031",
      governmentType: "county",
      governmentSubtype: "township_organized_county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "14209500100000",
      officialName: "Washington County",
      state: "IL",
      countyName: "Washington County",
      countyFips: "189",
      governmentType: "county",
      governmentSubtype: "commission_county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "14301600100000",
      officialName: "City of Chicago",
      state: "IL",
      countyName: "Cook County",
      countyFips: "031",
      placeName: "Chicago",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "14401600100000",
      officialName: "Schaumburg Township",
      state: "IL",
      countyName: "Cook County",
      countyFips: "031",
      governmentType: "township",
      governmentSubtype: "civil_township",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "14402200100000",
      officialName: "Naperville Township",
      state: "IL",
      countyName: "DuPage County",
      countyFips: "043",
      governmentType: "township",
      governmentSubtype: "civil_township",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "14501600108000",
      officialName:
        "Metropolitan Water Reclamation District of Greater Chicago",
      state: "IL",
      countyName: "Cook County",
      countyFips: "031",
      governmentType: "special_district",
      governmentSubtype: "sanitary_district",
      functionCategory: "sewerage",
      activeStatus: "active",
    },
    {
      censusGovId: "14501600106000",
      officialName: "Chicago Park District",
      state: "IL",
      countyName: "Cook County",
      countyFips: "031",
      governmentType: "special_district",
      governmentSubtype: "park_district",
      functionCategory: "parks_recreation",
      activeStatus: "active",
    },
    {
      censusGovId: "14501600102400",
      officialName: "Oakland Fire Protection District",
      state: "IL",
      countyName: "Coles County",
      countyFips: "029",
      governmentType: "special_district",
      governmentSubtype: "fire_protection_district",
      functionCategory: "fire_protection",
      activeStatus: "active",
    },
    {
      censusGovId: "14601600104400",
      officialName: "Chicago Board of Education (Chicago Public Schools)",
      state: "IL",
      countyName: "Cook County",
      countyFips: "031",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },
    {
      censusGovId: "14605400104400",
      officialName: "Lincoln Community High School District No. 404",
      state: "IL",
      countyName: "Logan County",
      countyFips: "107",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- California (State 05) ---
    {
      censusGovId: "05100000000000",
      officialName: "State of California",
      state: "CA",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "05201900100000",
      officialName: "County of Los Angeles",
      state: "CA",
      countyName: "Los Angeles County",
      countyFips: "037",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "05203800100000",
      officialName: "City and County of San Francisco",
      state: "CA",
      countyName: "San Francisco County",
      countyFips: "075",
      governmentType: "county",
      governmentSubtype: "consolidated_city_county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "05301900100000",
      officialName: "City of Los Angeles",
      state: "CA",
      countyName: "Los Angeles County",
      countyFips: "037",
      placeName: "Los Angeles",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "05300100100000",
      officialName: "City of Oakland",
      state: "CA",
      countyName: "Alameda County",
      countyFips: "001",
      placeName: "Oakland",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "05500100109100",
      officialName: "East Bay Municipal Utility District (EBMUD)",
      state: "CA",
      countyName: "Alameda County",
      countyFips: "001",
      governmentType: "special_district",
      functionCategory: "water_supply",
      activeStatus: "active",
    },
    {
      censusGovId: "05500100109400",
      officialName: "San Francisco Bay Area Rapid Transit District (BART)",
      state: "CA",
      countyName: "Alameda County",
      countyFips: "001",
      governmentType: "special_district",
      functionCategory: "mass_transit",
      activeStatus: "active",
    },
    {
      censusGovId: "05601900104400",
      officialName: "Los Angeles Unified School District",
      state: "CA",
      countyName: "Los Angeles County",
      countyFips: "037",
      governmentType: "school_district",
      governmentSubtype: "unified_elementary_high_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },
    {
      censusGovId: "05603100104400",
      officialName: "Western Placer Unified School District (Lincoln)",
      state: "CA",
      countyName: "Placer County",
      countyFips: "061",
      governmentType: "school_district",
      governmentSubtype: "unified_elementary_high_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- New York (State 33) ---
    {
      censusGovId: "33100000000000",
      officialName: "State of New York",
      state: "NY",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "33200100100000",
      officialName: "Albany County",
      state: "NY",
      countyName: "Albany County",
      countyFips: "001",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "33205800100000",
      officialName: "Washington County",
      state: "NY",
      countyName: "Washington County",
      countyFips: "115",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "33303100100000",
      officialName: "City of New York",
      state: "NY",
      placeName: "New York",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "33402800100000",
      officialName: "Town of Hempstead",
      state: "NY",
      countyName: "Nassau County",
      countyFips: "059",
      governmentType: "township",
      governmentSubtype: "town",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "33404700100000",
      officialName: "Town of Brookhaven",
      state: "NY",
      countyName: "Suffolk County",
      countyFips: "103",
      governmentType: "township",
      governmentSubtype: "town",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "33504700102400",
      officialName: "Centereach Fire District",
      state: "NY",
      countyName: "Suffolk County",
      countyFips: "103",
      governmentType: "special_district",
      governmentSubtype: "fire_district",
      functionCategory: "fire_protection",
      activeStatus: "active",
    },
    {
      censusGovId: "33600100104400",
      officialName: "Albany City School District",
      state: "NY",
      countyName: "Albany County",
      countyFips: "001",
      governmentType: "school_district",
      governmentSubtype: "independent_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- Ohio (State 36) ---
    {
      censusGovId: "36100000000000",
      officialName: "State of Ohio",
      state: "OH",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "36202500100000",
      officialName: "Franklin County",
      state: "OH",
      countyName: "Franklin County",
      countyFips: "049",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "36208400100000",
      officialName: "Washington County",
      state: "OH",
      countyName: "Washington County",
      countyFips: "167",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "36302500100000",
      officialName: "City of Columbus",
      state: "OH",
      countyName: "Franklin County",
      countyFips: "049",
      placeName: "Columbus",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "36402500100000",
      officialName: "Franklin Township",
      state: "OH",
      countyName: "Franklin County",
      countyFips: "049",
      governmentType: "township",
      governmentSubtype: "civil_township",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "36408300100000",
      officialName: "Franklin Township",
      state: "OH",
      countyName: "Warren County",
      countyFips: "165",
      governmentType: "township",
      governmentSubtype: "civil_township",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "36505700105200",
      officialName: "Miami Conservancy District",
      state: "OH",
      countyName: "Montgomery County",
      countyFips: "113",
      governmentType: "special_district",
      governmentSubtype: "conservancy_district",
      functionCategory: "drainage_flood_control",
      activeStatus: "active",
    },
    {
      censusGovId: "36602500104400",
      officialName: "Columbus City School District",
      state: "OH",
      countyName: "Franklin County",
      countyFips: "049",
      governmentType: "school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- Pennsylvania (State 39) ---
    {
      censusGovId: "39100000000000",
      officialName: "Commonwealth of Pennsylvania",
      state: "PA",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "39205100100000",
      officialName: "Philadelphia County",
      state: "PA",
      countyName: "Philadelphia County",
      countyFips: "101",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "39206300100000",
      officialName: "Washington County",
      state: "PA",
      countyName: "Washington County",
      countyFips: "125",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "39305100100000",
      officialName: "City of Philadelphia",
      state: "PA",
      countyName: "Philadelphia County",
      countyFips: "101",
      placeName: "Philadelphia",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "39402600100000",
      officialName: "Franklin Township",
      state: "PA",
      countyName: "Fayette County",
      countyFips: "051",
      governmentType: "township",
      governmentSubtype: "township_first_second_class",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "39404600100000",
      officialName: "Lower Merion Township",
      state: "PA",
      countyName: "Montgomery County",
      countyFips: "091",
      governmentType: "township",
      governmentSubtype: "township_first_second_class",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "39505100109400",
      officialName:
        "Southeastern Pennsylvania Transportation Authority (SEPTA)",
      state: "PA",
      countyName: "Philadelphia County",
      countyFips: "101",
      governmentType: "special_district",
      functionCategory: "mass_transit",
      activeStatus: "active",
    },
    {
      censusGovId: "39605100104400",
      officialName: "School District of Philadelphia",
      state: "PA",
      countyName: "Philadelphia County",
      countyFips: "101",
      governmentType: "school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- Massachusetts (State 22) ---
    {
      censusGovId: "22100000000000",
      officialName: "Commonwealth of Massachusetts",
      state: "MA",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "22301300100000",
      officialName: "City of Boston",
      state: "MA",
      countyName: "Suffolk County",
      countyFips: "025",
      placeName: "Boston",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "22401100100000",
      officialName: "Town of Brookline",
      state: "MA",
      countyName: "Norfolk County",
      countyFips: "021",
      governmentType: "township",
      governmentSubtype: "new_england_town",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "22400900100000",
      officialName: "Town of Concord",
      state: "MA",
      countyName: "Middlesex County",
      countyFips: "017",
      governmentType: "township",
      governmentSubtype: "new_england_town",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "22501300109100",
      officialName: "Massachusetts Water Resources Authority (MWRA)",
      state: "MA",
      countyName: "Suffolk County",
      countyFips: "025",
      governmentType: "special_district",
      functionCategory: "water_supply",
      activeStatus: "active",
    },
    {
      censusGovId: "22600900104400",
      officialName: "Concord-Carlisle Regional School District",
      state: "MA",
      countyName: "Middlesex County",
      countyFips: "017",
      governmentType: "school_district",
      governmentSubtype: "regional_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- Virginia (State 47) ---
    {
      censusGovId: "47100000000000",
      officialName: "Commonwealth of Virginia",
      state: "VA",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "47202900100000",
      officialName: "Fairfax County",
      state: "VA",
      countyName: "Fairfax County",
      countyFips: "059",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "47209500100000",
      officialName: "Washington County",
      state: "VA",
      countyName: "Washington County",
      countyFips: "191",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "47312800100000",
      officialName: "City of Richmond",
      state: "VA",
      placeName: "Richmond",
      governmentType: "municipal",
      governmentSubtype: "independent_city",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "47312900100000",
      officialName: "City of Virginia Beach",
      state: "VA",
      placeName: "Virginia Beach",
      governmentType: "municipal",
      governmentSubtype: "independent_city",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "47502900109100",
      officialName: "Fairfax County Water Authority (Fairfax Water)",
      state: "VA",
      countyName: "Fairfax County",
      countyFips: "059",
      governmentType: "special_district",
      functionCategory: "water_supply",
      activeStatus: "active",
    },

    // --- Florida (State 10) ---
    {
      censusGovId: "10100000000000",
      officialName: "State of Florida",
      state: "FL",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "10201300100000",
      officialName: "Miami-Dade County",
      state: "FL",
      countyName: "Miami-Dade County",
      countyFips: "086",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "10206700100000",
      officialName: "Washington County",
      state: "FL",
      countyName: "Washington County",
      countyFips: "133",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "10301300100000",
      officialName: "City of Miami",
      state: "FL",
      countyName: "Miami-Dade County",
      countyFips: "086",
      placeName: "Miami",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "10505000105200",
      officialName: "South Florida Water Management District",
      state: "FL",
      countyName: "Palm Beach County",
      countyFips: "099",
      governmentType: "special_district",
      governmentSubtype: "water_management_district",
      functionCategory: "drainage_flood_control",
      activeStatus: "active",
    },
    {
      censusGovId: "10601300104400",
      officialName: "Miami-Dade County Public Schools",
      state: "FL",
      countyName: "Miami-Dade County",
      countyFips: "086",
      governmentType: "school_district",
      governmentSubtype: "county_school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },

    // --- Washington State (State 48) ---
    {
      censusGovId: "48100000000000",
      officialName: "State of Washington",
      state: "WA",
      governmentType: "state",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "48201700100000",
      officialName: "King County",
      state: "WA",
      countyName: "King County",
      countyFips: "033",
      governmentType: "county",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "48301700100000",
      officialName: "City of Seattle",
      state: "WA",
      countyName: "King County",
      countyFips: "033",
      placeName: "Seattle",
      governmentType: "municipal",
      functionCategory: "general_government",
      activeStatus: "active",
    },
    {
      censusGovId: "48501700100100",
      officialName: "Port of Seattle",
      state: "WA",
      countyName: "King County",
      countyFips: "033",
      governmentType: "special_district",
      functionCategory: "airports_ports",
      activeStatus: "active",
    },
    {
      censusGovId: "48601700104400",
      officialName: "Seattle Public Schools (District No. 1)",
      state: "WA",
      countyName: "King County",
      countyFips: "033",
      governmentType: "school_district",
      functionCategory: "education_elementary_secondary",
      activeStatus: "active",
    },
  ];
