// Generated by scripts/research/compile-irs-business-books.py from IRS
// Statistics of Income, corporation returns for tax year 2022, Table 5.1
// (22co51ccr.xlsx, read September 29, 2026). Do not edit by hand.

/**
 * Each kind of town business, as `kind=margin,pay,salesCost,estimated`
 * joined by `;`: net income over total receipts; officers' pay and
 * salaries over total receipts; cost of goods sold over the costs other
 * than pay; and 1 where that cost is suppressed and estimated, else 0.
 * `*` is every active corporation.
 */
export const IRS_TOWN_BUSINESS_BOOKS: string =
  "farm=0.0491,0.086,0.462,0;quarry=0.0847,0.047,0.731,0;construction=0.0538,0.083,0.829,0;manufacturing=0.1433,0.064,0.841,0;wholesale=0.0513,0.054,0.895,0;retail=0.0455,0.098,0.826,0;trucking=0.0509,0.145,0.474,0;information=0.0819,0.111,0.271,0;insurance=0.1208,0.34,0.34,1;realty=0.1534,0.356,0.34,1;professional=0.0724,0.284,0.5,0;building-services=0.0778,0.263,0.502,0;private-school=0.0593,0.308,0.245,0;clinic=0.0467,0.402,0.21,0;care-home=0.041,0.389,0.081,0;recreation=0.0671,0.209,0.295,0;restaurant=0.0571,0.219,0.547,0;inn=0.1358,0.22,0.141,0;repair=0.0427,0.187,0.632,0;personal-care=0.0766,0.264,0.352,0;*=0.1057,0.112,0.34,1";
