from pathlib import Path
import math,json
p=Path('/tmp/session14-mockups/unified-radial')
labels=['Calendar','People','Politics','News','Journal','Who you are','Money & property','Jobs & study','Travel','Guide','Options']
css='''@font-face{font-family:F;src:url(fira-sans-400.ttf)}@font-face{font-family:C;src:url(cinzel-800.ttf)}*{box-sizing:border-box}body{margin:0;width:1920px;height:1080px;overflow:hidden;background:url(room-art.jpg) center/cover;color:#f2ede4;font:15px/1.4 F}.surface{position:absolute;left:21px;bottom:20px;width:560px;height:112px;background:rgba(24,24,25,.5);border:1px solid #86754e;box-shadow:inset 0 0 0 1px #151616;backdrop-filter:blur(3px);border-radius:5px}.surface:hover,.open .surface{background:rgba(24,24,25,.85)}.bust{position:absolute;bottom:0;left:0;width:135px;height:180px;overflow:hidden;mask-image:linear-gradient(#000 65%,transparent 100%)}.bust img{position:absolute;width:240px;left:-53px;top:-8px}.open .bust{width:160px;height:215px}.open .bust img{width:280px;left:-60px}.clock{position:absolute;left:155px;top:12px}.clock strong{font:18px C;display:block}.time-actions{display:flex;gap:8px;margin-top:10px}.ui-action{font:15px F;color:#efe5d2;background:rgba(44,43,39,.8);border:1px solid #9d8553;padding:7px 12px;position:relative}.ui-action:active:before{content:'›';position:absolute;left:2px}.sheet-frame{position:absolute;background:rgba(24,24,25,.83);border:2px solid #c4a55e;border-radius:9px;box-shadow:0 0 0 1px #171717,inset 0 0 0 1px #d3ae6380;backdrop-filter:blur(2px);padding:26px 30px 20px}.corner{position:absolute;width:32px;height:32px;background-image:url(sheet.png);background-size:973.2px 581.4px}.tl{top:0;left:0;background-position:-33px -29.4px}.tr{top:0;right:0;background-position:-906px -29.4px}.bl{bottom:0;left:0;background-position:-33px -513px}.br{bottom:0;right:0;background-position:-906px -513px}.a-card{left:168px;bottom:150px;width:510px}.open .a-card{left:850px;bottom:150px;width:510px}h2{font:24px/1.2 C;color:#e7d3a7;margin:0 0 12px}.facts{margin:0;display:grid;grid-template-columns:75px 1fr;gap:6px 10px}.facts dt{color:#d6bd84}.facts dd{margin:0}.entry{position:absolute;transform:translate(-50%,-50%);width:160px;height:26px;border:3px solid transparent;border-image:url(iron-frame.svg) 3 stretch;background:rgba(30,32,33,.82);color:#efe9df;font:14px F;white-space:nowrap;overflow:hidden}.entry i{position:absolute;top:0;height:20px;width:50px;background:url(sheet.png) -147px -248px/1622px 969px;opacity:.5}.entry i:last-of-type{width:4px}.entry span{position:relative}.entry:before,.entry:after{content:none!important}.rest .fan{display:none}.note{position:absolute;right:24px;top:24px;font:14px F;background:#171919bc;padding:9px 13px}'''
nodes=''
for i,label in enumerate(labels):
 a=math.radians(i*3);x=83+650*math.cos(a);y=998-650*math.sin(a)
 nodes+=f'<button class="entry" data-angle="{i*3}" style="left:{x}px;top:{y}px"><i style="left:0"></i><i style="left:50px"></i><i style="left:100px"></i><i style="left:150px"></i><span>{label}</span></button>'
js="""import {reviseACard} from './card-content.js';const recorded=await fetch('recorded-content.json').then(r=>r.json());const card=document.querySelector('.a-card');const actions=reviseACard(card,recorded);document.querySelector('.clock').append(actions);await document.fonts.ready;window.ready=true;"""
for state in ['rest','open']:
 body=f'<main id="direction-a" class="{state}"><div class="surface"><div class="bust"><img src="person.png" alt="Brianna Kennedy, recorded game recipe"></div><div class="clock"><strong>9:10 AM</strong>Monday, January 5, 2026</div></div><section class="sheet-frame a-card"><i class="corner tl"></i><i class="corner tr"></i><i class="corner bl"></i><i class="corner br"></i><h2></h2><dl class="facts"></dl><div class="time-actions"><button class="ui-action">Day</button><button class="ui-action">Week</button><button class="ui-action">Until needed</button></div></section><nav class="fan">{nodes}</nav></main><aside class="note">Session 14 + 3 · {state.upper()} review candidate · real game art / recorded handoff · not implemented</aside>'
 (p/f'radial-{state}.html').write_text(f'<!doctype html><html><head><meta charset="utf-8"><style>{css}</style><link rel="stylesheet" href="card-content.css"></head><body>{body}<script type="module">{js}</script></body></html>')
