import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { format } from "prettier";
import { REPO_ROOT } from "./registry";
import { sourceDomain } from "../../src/source/domains/constitutional-process/index";
import type { ArtifactLock } from "../../src/source/core/index";

export async function exportConstitutionalProcess(
  outputPath: string,
): Promise<void> {
  const lock = JSON.parse(
    readFileSync(resolve(REPO_ROOT, sourceDomain.lockPath), "utf8"),
  ) as ArtifactLock;
  const compiled = sourceDomain.compileProduction(lock);
  const rows = compiled.records as readonly {
    artifactId: string;
    url: string;
    sha256: string;
    observedOn: string;
  }[];
  const evidence = Object.fromEntries(
    rows.map((r) => [
      r.artifactId,
      { url: r.url, sha256: r.sha256, observedOn: r.observedOn },
    ]),
  );
  const text = await format(
    `/** GENERATED by scripts/source/export-constitutional-process.ts. */\nexport const CONSTITUTIONAL_EVIDENCE = ${JSON.stringify(evidence, null, 2)} as const;\n`,
    { parser: "typescript" },
  );
  writeFileSync(outputPath, text);
}
if (process.argv[1]?.endsWith("export-constitutional-process.ts"))
  await exportConstitutionalProcess(
    resolve(REPO_ROOT, "src/simulation/constitutional-sources.generated.ts"),
  );
