/** Project the reviewed seat table across the Node/browser source boundary. */
import { readFileSync, writeFileSync } from "fs";
import path from "path";

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const INPUT = path.join(ROOT, "data/research/places/seats-of-government.json");
const OUTPUT = path.join(
  ROOT,
  "src/simulation/seats-of-government.generated.ts",
);

interface SeatTable {
  readonly asOf: string;
  readonly rows: readonly {
    readonly jurisdictionKey: string;
    readonly placeGeoid?: string;
    readonly placeKey?: string;
    readonly matchStatus: "known" | "estimated-territory-place";
  }[];
}

const table = JSON.parse(readFileSync(INPUT, "utf8")) as SeatTable;
const rows = table.rows.map(
  ({ jurisdictionKey, placeGeoid, placeKey, matchStatus }) => {
    const key = placeKey ?? placeGeoid;
    if (!key)
      throw new Error(`Missing seat place identity for ${jurisdictionKey}`);
    return [jurisdictionKey, key, matchStatus];
  },
);
const output = `/** GENERATED by scripts/source/export-seats-of-government.ts. */
export const SEATS_OF_GOVERNMENT_AS_OF = ${JSON.stringify(table.asOf)};
/** [jurisdiction key, ordinary place key, match status]. */
export const SEATS_OF_GOVERNMENT_ROWS: string =
  ${JSON.stringify(JSON.stringify(rows))};
`;

writeFileSync(OUTPUT, output);
process.stdout.write(
  `Wrote ${rows.length} seats to ${path.relative(ROOT, OUTPUT)}.\n`,
);
