/** Export population weights from the already locked 2020 Census county parts. */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ArtifactLock } from "../../src/source/core/index";
import {
  LATIN1_GEOHEADER_STATES,
  PL_STATES,
} from "../../src/source/domains/place-county-relations/acquisition";
import { openPlaceCountyProduction } from "../../src/source/domains/place-county-relations/index";
import { parsePlaceCountyParts } from "../../src/source/domains/place-county-relations/parse";
import { REPO_ROOT } from "./registry";

export const COUNTY_PLACE_POPULATION_OUTPUT =
  "src/simulation/outcome-web/county-place-population.generated.ts";

export function renderCountyPlacePopulation(): string {
  const lock = JSON.parse(
    readFileSync(
      resolve(
        REPO_ROOT,
        "data/source/place-county-relations/artifact-lock.json",
      ),
      "utf8",
    ),
  ) as ArtifactLock;
  const input = openPlaceCountyProduction(lock);
  const byPlace = new Map<string, [string, number][]>();
  const sources: { artifactId: string; sha256: string }[] = [];
  for (const [usps, state] of PL_STATES) {
    const artifact = input.artifacts[usps];
    const parsed = parsePlaceCountyParts(
      artifact.bytes,
      LATIN1_GEOHEADER_STATES.has(usps) ? "latin1" : "utf-8",
    );
    if (parsed.defects.length)
      throw new Error(`${usps}: invalid geographic header`);
    sources.push({
      artifactId: artifact.artifact.artifactId,
      sha256: artifact.artifact.bytes.sha256,
    });
    for (const row of parsed.rows) {
      // Legacy geographic header: POP100 is field 91 (zero-based 90).
      // The locked publisher documentation names this the population count.
      const geocode = row.fields[9] ?? "";
      const rawPopulation = row.fields[90] ?? "";
      const population = Number(rawPopulation);
      if (
        row.fields[2] !== "155" ||
        !/^\d{10}$/.test(geocode) ||
        geocode.slice(0, 2) !== state ||
        row.fields[8] !== `1550000US${geocode}` ||
        !/^\d+$/.test(rawPopulation) ||
        !Number.isSafeInteger(population)
      ) {
        throw new Error(`${usps}:${row.line}: invalid place-county population`);
      }
      const place = geocode.slice(0, 7);
      const county = state + geocode.slice(7);
      const parts = byPlace.get(place) ?? [];
      if (parts.some(([existing]) => existing === county))
        throw new Error(`${place}: duplicate county ${county}`);
      parts.push([county, population]);
      byPlace.set(place, parts);
    }
  }
  // Single-county places need no allocation ratio; their whole population
  // belongs to the one county in the existing geography index.
  const rows = [...byPlace]
    .filter(([, parts]) => parts.length > 1)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([place, parts]) => [
      place,
      parts.sort(([a], [b]) => a.localeCompare(b)),
    ]);
  const metadata = {
    asOf: "2020-04-01",
    source:
      "2020 Census P.L. 94-171 legacy geographic header, SUMLEV 155, POP100 (field 91)",
    documentationUrl: input.artifacts.AL.artifact.publisher.documentationUrl,
    coverage:
      "50 states and DC; 2020 boundaries. No Puerto Rico or island-area population weights.",
    multiCountyPlaceCount: rows.length,
    inputs: sources,
  };
  return `/** GENERATED by scripts/source/export-county-place-population.ts. */\nexport const COUNTY_PLACE_POPULATION_META = ${JSON.stringify(metadata, null, 2)} as const;\nexport const COUNTY_PLACE_POPULATION_ROWS: string = ${JSON.stringify(JSON.stringify(rows))};\n`;
}

if (process.argv[1]?.endsWith("export-county-place-population.ts")) {
  writeFileSync(
    resolve(REPO_ROOT, COUNTY_PLACE_POPULATION_OUTPUT),
    renderCountyPlacePopulation(),
  );
}
