/** Browser projection of the accepted county identities; no geographic joins. */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { format } from "prettier";
import type { CountyRecord } from "../../src/source/domains/counties/types";

const root = path.resolve(import.meta.dirname, "../..");
const bytes = readFileSync(path.join(root, "data/source/counties/corpus.json"));
const manifest = JSON.parse(
  readFileSync(
    path.join(root, "data/source/counties/corpus-manifest.json"),
    "utf8",
  ),
);
if (
  createHash("sha256").update(bytes).digest("hex") !== manifest.canonicalSha256
)
  throw new Error("County corpus checksum differs from the accepted manifest.");
const records = JSON.parse(bytes.toString("utf8")) as CountyRecord[];
if (
  records.length !== manifest.recordCount ||
  manifest.inputClass !== "production"
)
  throw new Error("County corpus count or admission class differs.");
const rows = records
  .map(({ geoid, sourceName, stateUsps }) => [geoid, sourceName, stateUsps])
  .sort((a, b) => a[0]!.localeCompare(b[0]!));
const meta = {
  asOf: manifest.asOf,
  source: manifest.inputs[0].artifactId,
  sourceSha256: manifest.inputs[0].sha256,
  corpusSha256: manifest.canonicalSha256,
  recordCount: rows.length,
};
writeFileSync(
  path.join(root, "src/simulation/national-counties.generated.ts"),
  await format(
    `/** GENERATED by scripts/source/export-life-counties.ts. Identity only; no town membership or government powers. */\nexport const NATIONAL_COUNTIES_META = ${JSON.stringify(meta, null, 2)} as const;\n/** [county GEOID, source name, state USPS]. */\nexport const NATIONAL_COUNTIES_ROWS: string = ${JSON.stringify(JSON.stringify(rows))};\n`,
    { parser: "typescript" },
  ),
);
process.stdout.write(`Exported ${rows.length} county identities.\n`);
