/**
 * The qualification accounting ledger.
 *
 * 31F's disposition table said which of the research wave's claims were
 * compiler-ready. This says what happened to each of them afterwards: compiled,
 * or refused, and on which of five grounds. Every row of both committed
 * research corpora appears in exactly one column, because a row that quietly
 * vanished between a research document and a game rule is the failure this
 * whole lane exists to prevent.
 *
 * Regenerate with `npm run ledger:qualifications`. The output is committed so a
 * reviewer reads the accounting without running anything.
 */

import { readFileSync, writeFileSync } from "fs";
import path from "path";

import {
  QUALIFICATIONS_CORPUS_AS_OF,
  QUALIFICATION_SOURCES,
  compileQualifications,
  openQualificationArtifacts,
} from "../../src/source/domains/state-office-qualifications/index";
import type { QualificationRefusalKind } from "../../src/source/domains/state-office-qualifications/index";
import type { ArtifactLock } from "../../src/source/core/index";

const REPOSITORY_ROOT = path.resolve(import.meta.dirname, "..", "..");
const OUTPUT_PATH = path.join(
  REPOSITORY_ROOT,
  "docs/research/qualification-source-ledger.md",
);

const REFUSAL_HEADINGS: Readonly<Record<QualificationRefusalKind, string>> = {
  "authority-read-claim-unsupported":
    "Authority retrieved; the provision does not carry the claim",
  "citation-does-not-name-provision":
    "Citation names a provision other than the one read",
  "excerpt-absent-from-provision":
    "Transcribed words absent from the provision",
  "authority-not-retrieved": "Authority not retrieved",
  "no-transcription": "No authority retrieved for this claim",
  "office-family-not-modelled": "Office family this domain does not model",
  "field-not-modelled": "Qualification field this domain does not model",
};

function tally<T extends string>(
  values: readonly T[],
): readonly (readonly [T, number])[] {
  const counts = new Map<T, number>();
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1);
  return [...counts.entries()].sort((left, right) => right[1] - left[1]);
}

function main(): void {
  const lock = JSON.parse(
    readFileSync(
      path.join(
        REPOSITORY_ROOT,
        "data/source/state-office-qualifications/artifact-lock.json",
      ),
      "utf-8",
    ),
  ) as ArtifactLock;

  const result = compileQualifications(
    openQualificationArtifacts(lock),
    QUALIFICATIONS_CORPUS_AS_OF,
  );

  const compiled = result.corpus.records;
  const refusals = result.refusals;
  const byState = tally(refusals.map((refusal) => refusal.stateUsps));
  const compiledByState = tally(compiled.map((record) => record.stateUsps));

  const lines: string[] = [];
  const say = (line = "") => lines.push(line);

  say("# Qualification source ledger");
  say();
  say(
    "Generated by `npm run ledger:qualifications`. Every row of both committed research corpora appears below exactly once.",
  );
  say();
  say("## Totals");
  say();
  say("| | Rows |");
  say("|---|---|");
  say(`| Research rows considered | ${result.rowsConsidered} |`);
  say(`| Compiled to production records | ${compiled.length} |`);
  say(`| Refused | ${refusals.length} |`);
  say();
  say(
    `The two corpora are \`docs/research/31F-compiler-ready-claims.tsv\` (118 rows, batch 31C) and \`docs/research/31D-recovered-qualifications.tsv\` (601 rows, batch 31D). ${result.rowsConsidered} = 118 + 601.`,
  );
  say();

  say("## Compiled, by state");
  say();
  say("| State | Records |");
  say("|---|---|");
  for (const [state, count] of compiledByState) say(`| ${state} | ${count} |`);
  say();
  say(
    `Authorities retrieved: ${QUALIFICATION_SOURCES.length} provisions across ${
      new Set(QUALIFICATION_SOURCES.map((spec) => spec.jurisdictionKey)).size
    } states. Each record's value was found in the enacted text of the provision it cites.`,
  );
  say();

  say("## Refused, by ground");
  say();
  say("| Ground | Rows |");
  say("|---|---|");
  for (const [kind, count] of tally(refusals.map((refusal) => refusal.kind))) {
    say(`| ${REFUSAL_HEADINGS[kind]} | ${count} |`);
  }
  say();

  const examined = refusals.filter(
    (refusal) => refusal.kind === "authority-read-claim-unsupported",
  );
  say("## Claims whose authority was retrieved and does not carry them");
  say();
  say(
    "These are findings rather than omissions: the provision the research cites was fetched, hashed and read, and it does not say what the claim says. None is repaired here, because re-citing a claim to a provision that would support it is legal research.",
  );
  say();
  for (const refusal of examined) {
    say(
      `- **${refusal.stateUsps} ${refusal.officeFamily} — ${refusal.field}** (cites \`${refusal.citedLocator}\`)`,
    );
    say(`  ${refusal.reason}`);
  }
  say();

  say("## Refused for want of a retrieved authority, by state");
  say();
  say(
    "No claim below has been shown to be wrong. Each is a claim this repository has not checked, because the authority it cites has not been retrieved. That is a fact about this repository and never a fact about the state's law.",
  );
  say();
  say("| State | Rows | Batch |");
  say("|---|---|---|");
  const notTranscribed = refusals.filter(
    (refusal) => refusal.kind === "no-transcription",
  );
  for (const [state, count] of tally(
    notTranscribed.map((refusal) => refusal.stateUsps),
  )) {
    const batches = [
      ...new Set(
        notTranscribed
          .filter((refusal) => refusal.stateUsps === state)
          .map((refusal) => refusal.batch),
      ),
    ].sort();
    say(`| ${state} | ${count} | ${batches.join(", ")} |`);
  }
  say();
  say(`Total: ${notTranscribed.length} rows across ${byState.length} states.`);
  say();
  say("## What would compile more");
  say();
  say(
    "Retrieving a state's cited authorities and writing the reviewed transcriptions for them. No new legal research is needed for any state in either corpus: both carry a citation and, for all but New Mexico, a URL that resolves to a provision rather than to a site root. The work is acquisition and review, in that order.",
  );

  writeFileSync(OUTPUT_PATH, `${lines.join("\n")}\n`, "utf-8");
  console.log(
    `ledger:qualifications — ${compiled.length} compiled, ${refusals.length} refused, ${result.rowsConsidered} accounted for`,
  );
}

main();
