"""Compiles the shapes of real small banks for the game's town banks.

Reads the FDIC BankFind call-report extracts for June 30, 2026 that the
Emergence Building Blocks research read on September 28, 2026
(`fin_20260630.json`: CERT, ASSET, DEP, CHBAL, STNAME; `sec_20260630.json`:
CERT, ASSET, DEP, CHBAL, SC, SCPLEDGE, SCHA, FREPO; amounts in thousands of
dollars), and Build 19's of September 29, 2026 (`unins_20260630.json`: CERT,
DEP, DEPUNINS, DEPINS), and writes, for every insured institution under
$1 billion in assets, three ratios to its deposits:

1. cushion: cash and balances due, plus securities not pledged, plus federal
   funds sold and reverse repurchase agreements (CHBAL + SC - SCPLEDGE +
   FREPO) / DEP;
2. other assets, mostly loans: (ASSET - CHBAL - SC - FREPO) / DEP;
3. uninsured: its estimated uninsured deposits, DEPUNINS / DEP.

Usage: python3 scripts/research/compile-fdic-town-banks.py <folder>
"""

import json
import sys
from collections import defaultdict

folder = sys.argv[1]
fin = {
    row["data"]["CERT"]: row["data"]
    for row in json.load(open(f"{folder}/fin_20260630.json"))["data"]
}
uninsured = {
    row["data"]["CERT"]: row["data"]
    for row in json.load(open(f"{folder}/unins_20260630.json"))["data"]
}
by_state = defaultdict(list)
for row in json.load(open(f"{folder}/sec_20260630.json"))["data"]:
    bank = row["data"]
    named = fin.get(bank["CERT"])
    if not named or not named["STNAME"] or not bank["DEP"]:
        continue
    if bank["ASSET"] >= 1_000_000:
        continue
    cushion = (bank["CHBAL"] + bank["SC"] - bank["SCPLEDGE"] + bank["FREPO"]) / bank["DEP"]
    other = (bank["ASSET"] - bank["CHBAL"] - bank["SC"] - bank["FREPO"]) / bank["DEP"]
    unins = uninsured[bank["CERT"]]["DEPUNINS"] / bank["DEP"]
    by_state[named["STNAME"].title().replace(" Of ", " of ")].append(
        (round(cushion, 3), round(max(0.0, other), 3), round(unins, 3), bank["CERT"], bank["ASSET"])
    )

out = [
    "// Generated by scripts/research/compile-fdic-town-banks.py from the FDIC",
    "// BankFind call reports for June 30, 2026 (read September 28, 2026).",
    "// Do not edit by hand.",
    "",
    "/**",
    " * Every FDIC-insured institution under $1 billion in assets on June 30,",
    " * 2026, by state: `cushion,otherAssets,uninsured` as shares of its deposits,",
    " * separated by `;`, in FDIC certificate order. The cushion is cash, free",
    " * securities and overnight loans to other banks; other assets are mostly",
    " * loans; uninsured deposits are the bank's own estimate.",
    " */",
    "export const FDIC_SMALL_BANK_SHAPES: Readonly<Record<string, string>> = {",
]
total = 0
for state in sorted(by_state):
    rows = sorted(by_state[state], key=lambda row: row[3])
    total += len(rows)
    text = ";".join(f"{c:g},{o:g},{u:g}" for c, o, u, _, _ in rows)
    out.append(f"  {json.dumps(state)}: {json.dumps(text)},")
out.append("};")
out.append("")
out.extend([
    "/** Observed [assets in thousands of dollars, certificate], in the same row order.",
    " * Source: https://banks.data.fdic.gov/api/financials; June 30, 2026 report.",
    " * Recovered October 2, 2026; all original 3,194 ratio rows are preserved.",
    " */",
    "export const FDIC_SMALL_BANK_RECORDS: Readonly<Record<string, readonly (readonly [number, number])[]>> = {",
])
for state in sorted(by_state):
    rows = sorted(by_state[state], key=lambda row: row[3])
    records = [[asset, cert] for _, _, _, cert, asset in rows]
    out.append(f"  {json.dumps(state)}: {json.dumps(records)},")
out.append("};")
out.append("")
out.append(f"export const FDIC_SMALL_BANK_COUNT = {total};")
out.append('export const FDIC_SMALL_BANK_REPORT_DATE = "2026-06-30";')
open("src/simulation/living-world/town-bank-shapes.generated.ts", "w").write(
    "\n".join(out) + "\n"
)
print(total, "banks in", len(by_state), "states and territories")
