"""Compiles each kind of town business's books from the IRS's corporation
returns.

Reads IRS Statistics of Income, corporation returns for tax year 2022,
Table 5.1 (`22co51ccr.xlsx`, published September 2025, read September 29,
2026) and writes, for each kind of town business, from the industry column
named below:

1. margin: net income less deficit over total receipts;
2. pay: compensation of officers plus salaries and wages, over total
   receipts;
3. sales cost: cost of goods sold over the other deductions (total receipts
   less net income less officers' pay and salaries). Where the IRS
   suppresses cost of goods sold ("d"), the mean of the service kinds whose
   cost is published, marked as estimated.

Usage: python3 scripts/research/compile-irs-business-books.py <22co51ccr.xlsx>
"""

import json
import sys

import openpyxl

# kind: (the industry group heading, the start of the industry's column label)
KINDS = {
    "farm": ("Agriculture", "Agricultural production"),
    "quarry": ("Mining", "Nonmetallic mineral mining"),
    "construction": ("Construction", "Total"),
    "manufacturing": ("Manufacturing", "Total"),
    "wholesale": ("Wholesale", "Total"),
    "retail": ("Retail", "Total"),
    "trucking": ("Transportation", "Truck transportation"),
    "information": ("Information", "Telecommunications"),
    "insurance": ("Finance", "Insurance agencies"),
    "realty": ("Real estate", "Offices of real estate agents"),
    "professional": ("Professional", "Total"),
    "building-services": ("Administrative", "Other administrative"),
    "private-school": ("Educational", ""),
    "clinic": ("Health", "Offices of physicians"),
    "care-home": ("Health", "Hospitals, nursing"),
    "recreation": ("Arts", "Amusement, gambling"),
    "restaurant": ("Accommodation", "Food services"),
    "inn": ("Accommodation", "Accommodation"),
    "repair": ("Other services", "Automotive repair"),
    "personal-care": ("Other services", "Personal and laundry"),
}
# The service kinds whose cost of goods sold is published, averaged for the
# ones whose cost is suppressed.
SERVICE_KINDS = [
    "professional",
    "building-services",
    "private-school",
    "clinic",
    "recreation",
    "information",
    "personal-care",
]

rows = list(
    openpyxl.load_workbook(sys.argv[1], read_only=True, data_only=True)
    .active.iter_rows(values_only=True)
)
label = {str(row[0]).strip(): row for row in rows if row and row[0]}
width = max(len(row) for row in rows[4:6])
groups = []
group = ""
for column in range(width):
    heading = rows[4][column] if column < len(rows[4]) else None
    if heading:
        group = str(heading)
    name = rows[5][column] if column < len(rows[5]) else None
    groups.append((group, str(name or "")))


def value(item, column):
    cell = label[item][column]
    return None if cell in (None, "d", "*d") else float(str(cell).lstrip("*"))


def books(column):
    receipts = value("Total receipts", column)
    income = value("Net income (less deficit)", column)
    pay = value("Compensation of officers", column) + value("Salaries and wages", column)
    goods = value("Cost of goods sold [1]", column)
    other = receipts - income - pay
    return {
        "margin": round(income / receipts, 4),
        "pay": round(pay / receipts, 3),
        "salesCost": None if goods is None else round(goods / other, 3),
        "industry": groups[column][1] or groups[column][0],
    }


found = {}
for kind, (heading, name) in KINDS.items():
    columns = [
        column
        for column, (group, label_) in enumerate(groups)
        if group.startswith(heading) and label_.startswith(name)
    ]
    if not columns:
        sys.exit(f"no column for {kind}")
    found[kind] = books(columns[0])
estimate = round(
    sum(found[kind]["salesCost"] for kind in SERVICE_KINDS) / len(SERVICE_KINDS), 2
)
everyone = books(1)

out = [
    "// Generated by scripts/research/compile-irs-business-books.py from IRS",
    "// Statistics of Income, corporation returns for tax year 2022, Table 5.1",
    "// (22co51ccr.xlsx, read September 29, 2026). Do not edit by hand.",
    "",
    "/**",
    " * Each kind of town business, as `kind=margin,pay,salesCost,estimated`",
    " * joined by `;`: net income over total receipts; officers' pay and",
    " * salaries over total receipts; cost of goods sold over the costs other",
    " * than pay; and 1 where that cost is suppressed and estimated, else 0.",
    " * `*` is every active corporation.",
    " */",
    "export const IRS_TOWN_BUSINESS_BOOKS: string =",
]
cells = []
for kind, row in found.items():
    estimated = row["salesCost"] is None
    cost = estimate if estimated else row["salesCost"]
    cells.append(f"{kind}={row['margin']:g},{row['pay']:g},{cost:g},{int(estimated)}")
cells.append(f"*={everyone['margin']:g},{everyone['pay']:g},{estimate:g},1")
out.append("  " + json.dumps(";".join(cells)) + ";")
out.append("")
open("src/simulation/living-world/town-business-books.generated.ts", "w").write("\n".join(out))
for kind, row in found.items():
    print(kind, row)
print("estimate", estimate, "all", everyone)
