"""Compiles the deposits held in each county's bank branches.

Reads the FDIC Summary of Deposits for June 30, 2026, fetched from the FDIC
BankFind API (https://api.fdic.gov/banks/sod?filters=YEAR:2026, fields
STCNTYBR, DEPSUMBR, CERT, ASSET, BKMO; amounts in thousands of dollars) as
JSON pages in one folder, and writes each county's deposits: the sum of
DEPSUMBR over its branches.

A bank with more than $10 billion in assets books deposits gathered across
the country (online accounts, brokered and sweep deposits) at its main
office, so a main office of such a bank is left out. The $10 billion line
is where federal law treats a bank as large (12 U.S.C. 5515).

Usage: python3 scripts/research/compile-fdic-county-deposits.py <folder>
"""

import glob
import json
import sys
from collections import defaultdict

folder = sys.argv[1]
rows = []
for path in sorted(glob.glob(f"{folder}/*.json")):
    rows += [row["data"] for row in json.load(open(path))["data"]]
if len({row["ID"] for row in rows}) != len(rows):
    sys.exit("duplicate branches across pages")

deposits = defaultdict(int)
branches = 0
left_out = 0
for row in rows:
    if row["STCNTYBR"] is None:
        continue
    if row["BKMO"] == 1 and (row["ASSET"] or 0) > 10_000_000:
        left_out += 1
        continue
    deposits[f"{int(row['STCNTYBR']):05d}"] += row["DEPSUMBR"] or 0
    branches += 1

out = [
    "// Generated by scripts/research/compile-fdic-county-deposits.py from the",
    "// FDIC Summary of Deposits for June 30, 2026 (read September 29, 2026).",
    "// Do not edit by hand.",
    "",
    "export const FDIC_COUNTY_DEPOSITS_META = {",
    '  source: "https://api.fdic.gov/banks/sod?filters=YEAR:2026",',
    '  asOf: "2026-06-30",',
    f"  branches: {branches},",
    f"  largeBankMainOfficesLeftOut: {left_out},",
    f"  counties: {len(deposits)},",
    "} as const;",
    "",
    "/**",
    " * Deposits in each county's bank branches, in thousands of dollars, as",
    ' * "GEOID:deposits" pairs joined by ";". The main offices of banks over',
    " * $10 billion in assets are left out.",
    " */",
    "export const FDIC_COUNTY_DEPOSITS: string =",
    "  " + json.dumps(";".join(f"{k}:{deposits[k]}" for k in sorted(deposits))) + ";",
    "",
]
open("src/simulation/living-world/town-deposits.generated.ts", "w").write("\n".join(out))
print(f"{len(deposits)} counties, {branches} branches, {left_out} main offices left out")
