/**
 * Writes src/simulation/bill-numbering-styles.generated.ts from the recorded
 * research: the verified enacted-bill samples for all 50 states and the state
 * legislature corpus's chamber names. Decision OCD-LEG-NUM-001.
 *
 *   node --import tsx scripts/research/export-bill-numbering-styles.ts
 *   node --import tsx scripts/research/export-bill-numbering-styles.ts --check
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { format } from "prettier";

import {
  deriveStateBillNumberingStyle,
  type BillSampleRow,
  type ChamberNameRow,
  type StateBillNumberingStyle,
} from "../../src/simulation/bill-numbering-derivation";

const root = resolve(import.meta.dirname, "../..");
const SAMPLES = resolve(root, "data/research/bill-samples/state");
const CORPUS = resolve(root, "data/source/state-legislatures/corpus.json");
export const OUTPUT = resolve(
  root,
  "src/simulation/bill-numbering-styles.generated.ts",
);

interface CorpusRecord {
  readonly stateName: string;
  readonly stateUsps: string;
  readonly chambers?: readonly {
    readonly chamberKey: string;
    readonly name?: { readonly state?: string; readonly value?: unknown };
  }[];
}

function slug(stateName: string): string {
  return stateName.toLowerCase().replace(/\s+/g, "-");
}

export function deriveAllStateStyles(): StateBillNumberingStyle[] {
  const corpus = JSON.parse(readFileSync(CORPUS, "utf8")) as CorpusRecord[];
  const files = new Set(readdirSync(SAMPLES));
  return corpus
    .map((record) => {
      const file = `${slug(record.stateName)}.json`;
      if (!files.has(file))
        throw new Error(`No recorded bill samples for ${record.stateName}.`);
      const samples = JSON.parse(
        readFileSync(resolve(SAMPLES, file), "utf8"),
      ) as BillSampleRow[];
      const names: ChamberNameRow[] = [];
      for (const chamber of record.chambers ?? []) {
        if (chamber.name?.state !== "KNOWN") continue;
        if (typeof chamber.name.value !== "string") continue;
        if (chamber.chamberKey === "legislature") continue;
        names.push({
          role: chamber.chamberKey === "senate" ? "upper" : "lower",
          name: chamber.name.value,
        });
      }
      return deriveStateBillNumberingStyle(
        `US-${record.stateUsps}`,
        samples.map((row) => ({
          bill_number: row.bill_number,
          session: row.session,
        })),
        names,
      );
    })
    .sort((a, b) => a.jurisdictionKey.localeCompare(b.jurisdictionKey));
}

export async function renderStyles(): Promise<string> {
  const styles = deriveAllStateStyles();
  const source = [
    "// Generated by scripts/research/export-bill-numbering-styles.ts from",
    "// data/research/bill-samples/state/*.json and",
    "// data/source/state-legislatures/corpus.json. Do not edit by hand.",
    'import type { StateBillNumberingStyle } from "./bill-numbering-derivation";',
    "",
    "export const STATE_BILL_NUMBERING_STYLES: readonly StateBillNumberingStyle[] =",
    `  ${JSON.stringify(styles, null, 2).replace(/\n/g, "\n  ")};`,
    "",
  ].join("\n");
  return format(source, { filepath: OUTPUT });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const rendered = await renderStyles();
  if (process.argv.includes("--check")) {
    const current = readFileSync(OUTPUT, "utf8");
    if (current !== rendered) {
      console.error(
        "bill-numbering-styles.generated.ts is out of date; rerun the export.",
      );
      process.exit(1);
    }
    console.log("bill numbering styles match the recorded research");
  } else {
    writeFileSync(OUTPUT, rendered);
    console.log(`wrote ${OUTPUT}`);
  }
}
